import { PERSONAL_DETAILS_TARGETS } from "./pre-a1-module-05-targets";
import type { LessonV2 } from "./schema";

export const PRE_A1_M05_RETAIN_TRANSFER: LessonV2 = {
  schemaVersion: 2,
  id: "pre-a1-m05-retain-transfer",
  missionId: "pre-a1-m05",
  legacyUnitId: "unit-a0-5",
  titleVi: "Nhớ lại thông tin cá nhân trong bối cảnh mới",
  titleEn: "Recall and transfer basic personal details",
  level: "PRE_A1",
  legacyLevel: "A0",
  estimatedMinutes: 9,
  primaryOutcome: {
    id: "pre-a1-m05-retain-outcome",
    level: "PRE_A1",
    activity: "interaction",
    domain: "public",
    statementEn: "Can recall and reuse age, country and city details in a different registration context and ask for a missing city.",
    statementVi: "Có thể tự nhớ và dùng lại tuổi, quốc gia, thành phố trong một tình huống đăng ký khác, đồng thời hỏi thành phố còn thiếu.",
    source: "ato-adapted",
    sourceReference: "Delayed Pre-A1 transfer of basic personal details",
  },
  prerequisiteLessonIds: ["pre-a1-m05-communicate"],
  targets: PERSONAL_DETAILS_TARGETS,
  steps: [
    {
      id: "m05r-scenario",
      kind: "scenario",
      estimatedMinutes: 1,
      titleVi: "Đăng ký tại phòng khám cộng đồng",
      roleVi: "Bạn hỗ trợ một người điền ba thông tin cơ bản.",
      situationVi: "Bối cảnh đã đổi; không còn thẻ câu hỏi từ bài trước.",
      goalVi: "Tự nhớ câu phù hợp và phát hiện một ô thông tin bị bỏ trống.",
    },
    {
      id: "m05r-model",
      kind: "model",
      estimatedMinutes: 1,
      titleVi: "Nghe một mẫu mới duy nhất",
      replayRates: [0.9],
      turns: [
        { speaker: "Staff", text: "How old are you?", targetIds: ["m05-age-question"] },
        { speaker: "Visitor", text: "I am thirty years old. I am from Thailand.", targetIds: ["m05-age-answer", "m05-from-answer"] },
        { speaker: "Staff", text: "And your city?", targetIds: ["m05-missing-detail"] },
        { speaker: "Visitor", text: "I live in Chiang Mai.", targetIds: ["m05-live-answer"] },
      ],
    },
    {
      id: "m05r-notice",
      kind: "notice",
      estimatedMinutes: 1,
      titleVi: "Giữ chức năng, đổi dữ kiện",
      targetIds: ["m05-age-answer", "m05-from-answer", "m05-live-answer", "m05-missing-detail"],
      explanationVi: "Địa điểm và con số thay đổi nhưng bốn chức năng không đổi: nói tuổi, nói quốc gia, nói nơi sống và hỏi chi tiết bị thiếu.",
    },
    {
      id: "m05r-practice",
      kind: "practice",
      estimatedMinutes: 2,
      titleVi: "Delayed recall không nhìn mẫu cũ",
      exercises: [
        { id: "m05r-p1", kind: "listen", promptVi: "Người nói bao nhiêu tuổi?", audioText: "I am thirty years old.", options: ["13 tuổi", "30 tuổi", "33 tuổi"], answer: "30 tuổi", targetIds: ["m05-age-answer"] },
        { id: "m05r-p2", kind: "select", promptVi: "Câu nào nói nơi đang sống, không phải quốc gia?", options: ["I live in Chiang Mai.", "I am from Thailand.", "I am thirty years old."], answer: "I live in Chiang Mai.", targetIds: ["m05-live-answer"] },
        { id: "m05r-p3", kind: "order", promptVi: "Xếp câu: Tôi đến từ Thái Lan.", tokens: ["Thailand", "from", "am", "I"], answer: "I am from Thailand", targetIds: ["m05-from-answer"] },
        { id: "m05r-p4", kind: "recall", promptVi: "Tự nhớ câu hỏi ngắn khi còn thiếu thành phố.", answer: "And your city?", acceptedAnswers: ["And your city"], targetIds: ["m05-missing-detail"] },
      ],
    },
    {
      id: "m05r-rehearsal",
      kind: "rehearsal",
      estimatedMinutes: 1,
      titleVi: "Chuẩn bị bằng bốn từ khóa",
      promptVi: "Nhìn 26 — Japan — Kyoto — city missing. Tự tạo các lượt nói; không quay lại bài communicate.",
      keyWords: ["26", "Japan", "Kyoto", "missing city"],
      targetIds: ["m05-age-answer", "m05-from-answer", "m05-live-answer", "m05-missing-detail"],
    },
    {
      id: "m05r-performance",
      kind: "performance",
      estimatedMinutes: 1,
      titleVi: "Transfer sang quầy đăng ký",
      task: {
        roleVi: "Người hỗ trợ đăng ký",
        contextVi: "Lượt một điền thông tin cho khách 26/Japan/Kyoto. Lượt hai khách 24/Vietnam bỏ quên thành phố.",
        goalVi: "Hoàn thành ba trường thông tin và hỏi tiếp khi thành phố chưa được nói.",
        promptVi: "Không đọc kịch bản. Ở lượt hai, tự dùng And your city? rồi nhận câu trả lời I live in Can Tho.",
        successCriteriaVi: [
          "Bạn phân biệt đúng tuổi, quốc gia và nơi đang sống.",
          "Bạn tự hỏi chi tiết bị thiếu trong bối cảnh mới.",
          "Người nghe hiểu được con số và tên địa điểm.",
        ],
        targetIds: ["m05-age-answer", "m05-from-answer", "m05-live-answer", "m05-missing-detail"],
        evidence: ["task_checklist", "self_assessment"],
        attempts: 2,
        preparationSeconds: 10,
        responseSeconds: 25,
        rubric: ["task_achievement", "comprehensibility", "interaction_repair"],
      },
    },
    {
      id: "m05r-feedback",
      kind: "feedback",
      estimatedMinutes: 1,
      titleVi: "Đánh giá giữ được và chuyển được",
      priorityOrder: ["task_achievement", "comprehensibility", "interaction_repair"],
      repairPromptsVi: [
        "Bạn có tự nhớ câu mà không mở bài cũ không?",
        "Bạn có phân biệt quốc gia với thành phố đang sống không?",
        "Bạn có tự hỏi ô còn thiếu ở lượt hai không?",
      ],
    },
    {
      id: "m05r-exit",
      kind: "exit",
      estimatedMinutes: 1,
      titleVi: "Chốt evidence transfer",
      canDoCheckVi: "Tôi tự dùng tuổi, quốc gia và nơi sống trong một bối cảnh đăng ký mới và hỏi được chi tiết còn thiếu.",
      reviewTargetIds: ["m05-age-answer", "m05-from-answer", "m05-live-answer", "m05-missing-detail"],
      confidencePromptVi: "Bạn làm được lượt hai mà không xem lại bài communicate chứ?",
    },
  ],
  tags: ["pre-a1", "module-05", "retain-transfer", "personal-details"],
};
