import { PERSONAL_DETAILS_TARGETS } from "./pre-a1-module-05-targets";
import type { LessonV2 } from "./schema";

export const PRE_A1_M05_COMMUNICATE: LessonV2 = {
  schemaVersion: 2,
  id: "pre-a1-m05-communicate",
  missionId: "pre-a1-m05",
  legacyUnitId: "unit-a0-5",
  titleVi: "Hỏi và trao đổi thông tin cá nhân cơ bản",
  titleEn: "Exchange basic age, country and city details",
  level: "PRE_A1",
  legacyLevel: "A0",
  estimatedMinutes: 11,
  primaryOutcome: {
    id: "pre-a1-m05-communicate-outcome",
    level: "PRE_A1",
    activity: "interaction",
    domain: "personal",
    statementEn: "Can ask for and give age, country and city details in a short supported exchange and request one missing detail.",
    statementVi: "Có thể hỏi, trả lời tuổi, quốc gia, thành phố trong trao đổi ngắn có hỗ trợ và hỏi thêm một thông tin còn thiếu.",
    source: "ato-adapted",
    sourceReference: "CEFR Pre-A1 exchange of basic personal information",
  },
  prerequisiteLessonIds: ["pre-a1-m05-encounter"],
  targets: PERSONAL_DETAILS_TARGETS,
  steps: [
    {
      id: "m05c-scenario",
      kind: "scenario",
      estimatedMinutes: 1,
      titleVi: "Làm quen với một thành viên mới",
      roleVi: "Bạn và một người mới cùng tham gia lớp học.",
      situationVi: "Hai người cần biết tuổi, quốc gia và thành phố của nhau để hoàn thành thẻ giới thiệu.",
      goalVi: "Hỏi và trả lời đủ ba chi tiết, đồng thời phát hiện chi tiết bị thiếu.",
    },
    {
      id: "m05c-model",
      kind: "model",
      estimatedMinutes: 2,
      titleVi: "Nghe trao đổi có một chi tiết bị thiếu",
      replayRates: [0.8, 1],
      turns: [
        { speaker: "A", text: "How old are you?", targetIds: ["m05-age-question"] },
        { speaker: "B", text: "I am twenty years old.", targetIds: ["m05-age-answer"] },
        { speaker: "A", text: "Where are you from?", targetIds: ["m05-from-question"] },
        { speaker: "B", text: "I am from Japan.", targetIds: ["m05-from-answer"] },
        { speaker: "A", text: "And your city?", targetIds: ["m05-missing-detail"] },
        { speaker: "B", text: "I live in Osaka.", targetIds: ["m05-live-answer"] },
      ],
    },
    {
      id: "m05c-notice",
      kind: "notice",
      estimatedMinutes: 1,
      titleVi: "Hỏi đúng trường còn thiếu",
      targetIds: ["m05-age-question", "m05-from-question", "m05-live-question", "m05-missing-detail"],
      explanationVi: "Dùng câu hỏi đầy đủ khi bắt đầu một chủ đề. Khi đã biết quốc gia nhưng thiếu thành phố, And your city? là cách hỏi tiếp ngắn và rõ.",
    },
    {
      id: "m05c-practice",
      kind: "practice",
      estimatedMinutes: 2,
      titleVi: "Tạo từng lượt hỏi–đáp",
      adaptive: true,
      exercises: [
        { id: "m05c-p1", kind: "listen", promptVi: "Thông tin nào vẫn còn thiếu?", audioText: "I am twenty years old. I am from Japan.", options: ["Tuổi", "Quốc gia", "Thành phố"], answer: "Thành phố", targetIds: ["m05-age-answer", "m05-from-answer", "m05-missing-detail"] },
        { id: "m05c-p2", kind: "select", promptVi: "Chọn câu hỏi về tuổi.", options: ["How old are you?", "Where are you from?", "Where do you live?"], answer: "How old are you?", targetIds: ["m05-age-question"] },
        { id: "m05c-p3", kind: "order", promptVi: "Xếp câu: Tôi hai mươi tuổi.", tokens: ["years", "twenty", "old", "am", "I"], answer: "I am twenty years old", targetIds: ["m05-age-answer"] },
        { id: "m05c-p4", kind: "recall", promptVi: "Tự nhớ câu hỏi: Bạn sống ở đâu?", answer: "Where do you live?", acceptedAnswers: ["Where do you live"], targetIds: ["m05-live-question"] },
        { id: "m05c-p5", kind: "recall", promptVi: "Đã biết quốc gia nhưng thiếu thành phố. Tự nhớ câu hỏi ngắn.", answer: "And your city?", acceptedAnswers: ["And your city"], targetIds: ["m05-missing-detail"] },
      ],
    },
    {
      id: "m05c-rehearsal",
      kind: "rehearsal",
      estimatedMinutes: 1,
      titleVi: "Chuẩn bị hai thẻ người",
      promptVi: "Thẻ A: 21 — Korea — Seoul. Thẻ B: 19 — Vietnam — Hue. Chỉ ghi từ khóa; không viết cả hội thoại.",
      keyWords: ["21 / Korea / Seoul", "19 / Vietnam / Hue"],
      targetIds: ["m05-age-answer", "m05-from-answer", "m05-live-answer", "m05-missing-detail"],
    },
    {
      id: "m05c-performance",
      kind: "performance",
      estimatedMinutes: 2,
      titleVi: "Trao đổi thông tin hai lượt",
      task: {
        roleVi: "Hai thành viên mới",
        contextVi: "Mỗi người có một thẻ danh tính. Một lượt cố ý bỏ sót thành phố.",
        goalVi: "Hỏi và trả lời tuổi, quốc gia, thành phố; tự hỏi tiếp khi thiếu chi tiết.",
        promptVi: "Lượt một dùng thẻ A. Sau góp ý, lượt hai đổi sang thẻ B và người kia chỉ nói tuổi cùng quốc gia; bạn phải hỏi And your city?",
        successCriteriaVi: [
          "Bạn hỏi hoặc trả lời đủ tuổi, quốc gia và thành phố.",
          "Người nghe ghi đúng các chi tiết quan trọng.",
          "Bạn chủ động hỏi thông tin còn thiếu thay vì bỏ qua.",
        ],
        targetIds: ["m05-age-question", "m05-age-answer", "m05-from-question", "m05-from-answer", "m05-live-question", "m05-live-answer", "m05-missing-detail"],
        evidence: ["task_checklist", "self_assessment"],
        attempts: 2,
        preparationSeconds: 15,
        responseSeconds: 25,
        rubric: ["task_achievement", "comprehensibility", "interaction_repair"],
      },
    },
    {
      id: "m05c-feedback",
      kind: "feedback",
      estimatedMinutes: 1,
      titleVi: "Sửa một lỗi rồi làm lại",
      priorityOrder: ["task_achievement", "comprehensibility", "interaction_repair"],
      repairPromptsVi: [
        "Bạn có hỏi đúng loại thông tin thay vì lặp một câu hỏi không?",
        "Tên quốc gia và thành phố có được nói đủ rõ không?",
        "Khi thiếu thành phố, bạn có chủ động dùng And your city? không?",
      ],
    },
    {
      id: "m05c-exit",
      kind: "exit",
      estimatedMinutes: 1,
      titleVi: "Chốt trao đổi độc lập",
      canDoCheckVi: "Tôi hỏi và trả lời được tuổi, quốc gia, thành phố và nhận ra khi một chi tiết còn thiếu.",
      reviewTargetIds: ["m05-age-answer", "m05-from-answer", "m05-live-answer", "m05-missing-detail"],
      confidencePromptVi: "Ở lượt hai, bạn có tự hỏi tiếp mà không nhìn mẫu câu không?",
    },
  ],
  tags: ["pre-a1", "module-05", "communicate", "personal-details"],
};
