import { OBJECT_TARGETS } from "./pre-a1-module-03-targets";
import type { LessonV2 } from "./schema";

export const PRE_A1_M03_ENCOUNTER: LessonV2 = {
  schemaVersion: 2,
  id: "pre-a1-m03-encounter",
  missionId: "pre-a1-m03",
  legacyUnitId: "unit-a0-3",
  titleVi: "Nhận ra tên và màu của đồ vật",
  titleEn: "Recognise an object's name and colour",
  level: "PRE_A1",
  legacyLevel: "A0",
  estimatedMinutes: 10,
  primaryOutcome: {
    id: "pre-a1-m03-encounter-outcome",
    level: "PRE_A1",
    activity: "reception",
    domain: "personal",
    statementEn:
      "Can recognise a very short exchange that identifies a familiar object and its colour.",
    statementVi:
      "Có thể nhận ra một trao đổi rất ngắn về tên và màu của đồ vật quen thuộc.",
    source: "ato-adapted",
    sourceReference: "CEFR Pre-A1 reception with familiar concrete objects",
  },
  prerequisiteLessonIds: ["pre-a1-m02-retain-transfer"],
  targets: OBJECT_TARGETS,
  steps: [
    {
      id: "m03e-scenario",
      kind: "scenario",
      estimatedMinutes: 1,
      titleVi: "Tìm đồ trên bàn",
      roleVi: "Bạn đang tìm đồ dùng cá nhân.",
      situationVi: "Một người chỉ vào vài món đồ và hỏi tên, màu của chúng.",
      goalVi: "Nhận ra câu hỏi về đồ vật, tên đồ vật và màu sắc.",
    },
    {
      id: "m03e-model",
      kind: "model",
      estimatedMinutes: 2,
      titleVi: "Nghe trao đổi về một chiếc chìa khóa",
      replayRates: [0.65, 0.85],
      turns: [
        {
          speaker: "A",
          text: "What is this?",
          translationVi: "Đây là gì?",
          targetIds: ["m03-what-this"],
        },
        {
          speaker: "B",
          text: "This is a key.",
          translationVi: "Đây là một chiếc chìa khóa.",
          targetIds: ["m03-this-is"],
        },
        {
          speaker: "A",
          text: "What color is it?",
          translationVi: "Nó màu gì?",
          targetIds: ["m03-what-color"],
        },
        {
          speaker: "B",
          text: "It is black.",
          translationVi: "Nó màu đen.",
          targetIds: ["m03-it-is-color"],
        },
      ],
    },
    {
      id: "m03e-notice",
      kind: "notice",
      estimatedMinutes: 1,
      titleVi: "Tách hai câu hỏi",
      targetIds: [
        "m03-what-this",
        "m03-this-is",
        "m03-what-color",
        "m03-it-is-color",
      ],
      explanationVi:
        "What is this hỏi tên đồ vật; What color is it hỏi màu. Nghe từ cuối để biết người nói cần thông tin nào.",
    },
    {
      id: "m03e-practice",
      kind: "practice",
      estimatedMinutes: 2,
      titleVi: "Nghe, chọn, xếp và tự nhớ",
      adaptive: true,
      exercises: [
        {
          id: "m03e-p1",
          kind: "listen",
          promptVi: "Người nói đang hỏi thông tin nào?",
          audioText: "What color is it?",
          options: ["Tên đồ vật", "Màu đồ vật", "Giá đồ vật"],
          answer: "Màu đồ vật",
          targetIds: ["m03-what-color"],
        },
        {
          id: "m03e-p2",
          kind: "select",
          promptVi: "Chọn câu có nghĩa: Đây là một chiếc điện thoại.",
          options: ["This is a phone.", "It is blue.", "What is this?"],
          answer: "This is a phone.",
          targetIds: ["m03-this-is"],
        },
        {
          id: "m03e-p3",
          kind: "order",
          promptVi: "Xếp câu nói màu đen.",
          tokens: ["black", "is", "It"],
          answer: "It is black",
          targetIds: ["m03-it-is-color"],
        },
        {
          id: "m03e-p4",
          kind: "recall",
          promptVi: "Tự nhớ và gõ câu hỏi: Đây là gì?",
          answer: "What is this?",
          acceptedAnswers: ["What is this"],
          targetIds: ["m03-what-this"],
        },
      ],
    },
    {
      id: "m03e-rehearsal",
      kind: "rehearsal",
      estimatedMinutes: 1,
      titleVi: "Đổi đồ vật và màu",
      promptVi:
        "Đọc khung với key/black, sau đó đổi sang phone/blue mà không nhìn bản dịch.",
      frameEn: "This is a ___. It is ___.",
      keyWords: ["key", "black", "phone", "blue"],
      targetIds: ["m03-this-is", "m03-it-is-color"],
    },
    {
      id: "m03e-performance",
      kind: "performance",
      estimatedMinutes: 1,
      titleVi: "Trả lời về đồ vật trong 15 giây",
      task: {
        roleVi: "Người trả lời",
        contextVi: "Người đối diện giơ một chiếc chìa khóa rồi một chiếc điện thoại.",
        goalVi: "Nghe câu hỏi và nói câu trả lời phù hợp về tên hoặc màu.",
        promptVi:
          "Lượt hai, đổi đồ vật và màu; tập trung nghe What is this hay What color is it.",
        successCriteriaVi: [
          "Bạn trả lời What is this? bằng câu This is a....",
          "Bạn trả lời What color is it? bằng câu It is....",
        ],
        targetIds: [
          "m03-what-this",
          "m03-this-is",
          "m03-what-color",
          "m03-it-is-color",
        ],
        evidence: ["task_checklist", "self_assessment"],
        attempts: 2,
        preparationSeconds: 15,
        responseSeconds: 15,
        rubric: ["task_achievement", "comprehensibility"],
      },
    },
    {
      id: "m03e-feedback",
      kind: "feedback",
      estimatedMinutes: 1,
      titleVi: "Sửa điểm dễ nhầm",
      priorityOrder: ["task_achievement", "comprehensibility"],
      repairPromptsVi: [
        "Bạn có nghe được từ color để biết câu hỏi về màu không?",
        "Bạn có giữ is trong This is và It is không?",
      ],
    },
    {
      id: "m03e-exit",
      kind: "exit",
      estimatedMinutes: 1,
      titleVi: "Chốt tên và màu",
      canDoCheckVi:
        "Tôi nhận ra câu hỏi về tên đồ vật và màu của đồ vật quen thuộc.",
      reviewTargetIds: [
        "m03-what-this",
        "m03-this-is",
        "m03-what-color",
        "m03-it-is-color",
      ],
      confidencePromptVi: "Không nhìn mẫu, bạn phân biệt được hai câu hỏi chứ?",
    },
  ],
  tags: ["pre-a1", "module-03", "encounter", "objects", "colours"],
};
