import type { LanguageTarget } from "./schema";

export const SURVIVAL_HELP_TARGETS: LanguageTarget[] = [
  {
    id: "m08-help",
    kind: "chunk",
    form: "Help, please.",
    meaningVi: "Thu hút sự chú ý và xin trợ giúp ngay.",
    exampleEn: "Help, please.",
    exampleVi: "Làm ơn giúp tôi.",
    priority: "core",
  },
  {
    id: "m08-lost",
    kind: "chunk",
    form: "I am lost.",
    meaningVi: "Nói rằng bạn đang bị lạc.",
    exampleEn: "I am lost.",
    exampleVi: "Tôi đang bị lạc.",
    priority: "core",
  },
  {
    id: "m08-hurt",
    kind: "chunk",
    form: "I am hurt.",
    meaningVi: "Nói rằng bạn đang bị đau hoặc bị thương.",
    exampleEn: "I am hurt.",
    exampleVi: "Tôi đang bị đau/bị thương.",
    priority: "core",
  },
  {
    id: "m08-call",
    kind: "chunk",
    form: "Call a doctor / the police, please.",
    meaningVi: "Yêu cầu người khác gọi đúng loại hỗ trợ.",
    exampleEn: "Call a doctor, please.",
    exampleVi: "Làm ơn gọi bác sĩ.",
    priority: "core",
  },
  {
    id: "m08-location",
    kind: "grammar_pattern",
    form: "I am at ...",
    meaningVi: "Nói vị trí hiện tại bằng một địa điểm quen thuộc.",
    exampleEn: "I am at the bus station.",
    exampleVi: "Tôi đang ở bến xe buýt.",
    priority: "core",
    l1NoteVi: "Dùng at trước một điểm cụ thể như station, park hoặc hotel.",
  },
  {
    id: "m08-repeat-place",
    kind: "repair_strategy",
    form: "Please say the place again.",
    meaningVi: "Yêu cầu nhắc lại địa điểm khi chưa nghe rõ.",
    exampleEn: "Please say the place again.",
    exampleVi: "Làm ơn nói lại địa điểm.",
    priority: "support",
  },
  {
    id: "m08-correct-place",
    kind: "repair_strategy",
    form: "No, at the ...",
    meaningVi: "Sửa lại vị trí khi người kia nghe nhầm.",
    exampleEn: "No, at the park.",
    exampleVi: "Không, ở công viên.",
    priority: "support",
  },
];
