import type { LanguageTarget } from "./schema";

export const FAMILY_TARGETS: LanguageTarget[] = [
  {
    id: "m06-who-this",
    kind: "chunk",
    form: "Who is this?",
    meaningVi: "Hỏi người trong ảnh hoặc thẻ là ai.",
    exampleEn: "Who is this?",
    exampleVi: "Đây là ai?",
    priority: "core",
  },
  {
    id: "m06-this-my",
    kind: "chunk",
    form: "This is my ...",
    meaningVi: "Giới thiệu mối quan hệ của một người.",
    exampleEn: "This is my sister.",
    exampleVi: "Đây là chị/em gái của tôi.",
    priority: "core",
  },
  {
    id: "m06-his-name",
    kind: "grammar_pattern",
    form: "His name is ...",
    meaningVi: "Nói tên của một người nam.",
    exampleEn: "His name is Nam.",
    exampleVi: "Tên anh ấy là Nam.",
    priority: "core",
    l1NoteVi: "His đi với người nam; không dùng he trước danh từ name.",
  },
  {
    id: "m06-her-name",
    kind: "grammar_pattern",
    form: "Her name is ...",
    meaningVi: "Nói tên của một người nữ.",
    exampleEn: "Her name is Mai.",
    exampleVi: "Tên cô ấy là Mai.",
    priority: "core",
    l1NoteVi: "Her đi với người nữ; không dùng she trước danh từ name.",
  },
  {
    id: "m06-he-she",
    kind: "pronunciation",
    form: "he / she; his / her",
    meaningVi: "Phân biệt đại từ và từ sở hữu khi nghe, nói.",
    exampleEn: "She is my sister. Her name is Mai.",
    exampleVi: "Cô ấy là chị/em gái tôi. Tên cô ấy là Mai.",
    priority: "support",
    pronunciationGoal: "Giữ âm đầu /h/ trong he, his và âm /ʃ/ trong she.",
  },
  {
    id: "m06-confirm-person",
    kind: "repair_strategy",
    form: "This person?",
    meaningVi: "Chỉ và xác nhận đúng người khi ảnh có nhiều người.",
    exampleEn: "This person? Yes, my brother.",
    exampleVi: "Người này à? Đúng, anh/em trai tôi.",
    priority: "support",
  },
];
