import type { LanguageTarget, LessonV2 } from "./schema";

export const GREETING_TARGETS: LanguageTarget[] = [
  {
    id: "m04-greeting",
    kind: "pragmatics",
    form: "Hello. / Good morning.",
    meaningVi: "Lời chào trung tính hoặc lời chào buổi sáng.",
    exampleEn: "Good morning, Mai.",
    exampleVi: "Chào buổi sáng, Mai.",
    priority: "core",
    pronunciationGoal: "Giữ trọng âm rõ ở morning và không nuốt âm cuối.",
  },
  {
    id: "m04-how-are-you",
    kind: "chunk",
    form: "How are you?",
    meaningVi: "Bạn khỏe không?/Bạn thế nào?",
    exampleEn: "Hello. How are you?",
    exampleVi: "Xin chào. Bạn thế nào?",
    priority: "core",
  },
  {
    id: "m04-state",
    kind: "grammar_pattern",
    form: "I'm fine / okay / tired.",
    meaningVi: "Nói trạng thái rất cơ bản của bản thân.",
    exampleEn: "I'm okay, thank you.",
    exampleVi: "Tôi ổn, cảm ơn.",
    priority: "core",
    l1NoteVi: "Dùng I'm trước tính từ trạng thái; không bỏ động từ be.",
  },
  {
    id: "m04-and-you",
    kind: "discourse_move",
    form: "And you?",
    meaningVi: "Hỏi lại người đối diện sau khi đã trả lời.",
    exampleEn: "I'm fine, thank you. And you?",
    exampleVi: "Tôi khỏe, cảm ơn. Còn bạn?",
    priority: "core",
  },
  {
    id: "m04-closing",
    kind: "pragmatics",
    form: "See you later. / Goodbye.",
    meaningVi: "Kết thúc một trao đổi ngắn.",
    exampleEn: "See you later.",
    exampleVi: "Hẹn gặp lại.",
    priority: "core",
    pronunciationGoal: "Nói liền See you nhưng vẫn giữ âm đầu của later rõ.",
  },
];

export const PRE_A1_M04_ENCOUNTER: LessonV2 = {
  schemaVersion: 2,
  id: "pre-a1-m04-encounter",
  missionId: "pre-a1-m04",
  legacyUnitId: "unit-a0-4",
  titleVi: "Nhận ra lời chào, trạng thái và lời kết",
  titleEn: "Recognise greetings, basic states and closings",
  level: "PRE_A1",
  legacyLevel: "A0",
  estimatedMinutes: 10,
  primaryOutcome: {
    id: "pre-a1-m04-encounter-outcome",
    level: "PRE_A1",
    activity: "reception",
    domain: "personal",
    statementEn:
      "Can recognise a simple greeting, a basic wellbeing question, a short state answer and a closing.",
    statementVi:
      "Có thể nhận ra lời chào, câu hỏi thăm, câu trả lời trạng thái và lời kết thúc rất đơn giản.",
    source: "ato-adapted",
    sourceReference: "CEFR Pre-A1 recognition of formulaic social expressions",
  },
  prerequisiteLessonIds: ["pre-a1-m03-retain-transfer"],
  targets: GREETING_TARGETS,
  steps: [
    {
      id: "m04e-scenario",
      kind: "scenario",
      estimatedMinutes: 1,
      titleVi: "Gặp người quen vào buổi sáng",
      roleVi: "Bạn đi vào lớp hoặc nơi làm việc.",
      situationVi: "Một người quen chào, hỏi thăm rồi rời đi.",
      goalVi: "Nhận ra chức năng của từng câu trong trao đổi.",
    },
    {
      id: "m04e-model",
      kind: "model",
      estimatedMinutes: 2,
      titleVi: "Nghe một trao đổi xã giao ngắn",
      replayRates: [0.7, 0.9],
      turns: [
        {
          speaker: "A",
          text: "Good morning.",
          translationVi: "Chào buổi sáng.",
          targetIds: ["m04-greeting"],
        },
        {
          speaker: "B",
          text: "Hello. How are you?",
          translationVi: "Xin chào. Bạn thế nào?",
          targetIds: ["m04-greeting", "m04-how-are-you"],
        },
        {
          speaker: "A",
          text: "I'm fine, thank you. And you?",
          translationVi: "Tôi khỏe, cảm ơn. Còn bạn?",
          targetIds: ["m04-state", "m04-and-you"],
        },
        {
          speaker: "B",
          text: "I'm okay. See you later.",
          translationVi: "Tôi ổn. Hẹn gặp lại.",
          targetIds: ["m04-state", "m04-closing"],
        },
      ],
    },
    {
      id: "m04e-notice",
      kind: "notice",
      estimatedMinutes: 1,
      titleVi: "Nhìn bốn vị trí trong trao đổi",
      targetIds: [
        "m04-greeting",
        "m04-how-are-you",
        "m04-state",
        "m04-closing",
      ],
      explanationVi:
        "Trao đổi đi theo thứ tự: chào → hỏi thăm → trả lời ngắn → kết thúc. And you? giúp trả lượt nói lại.",
    },
    {
      id: "m04e-practice",
      kind: "practice",
      estimatedMinutes: 2,
      titleVi: "Nghe, chọn và tự nhớ",
      adaptive: true,
      exercises: [
        {
          id: "m04e-p1",
          kind: "listen",
          promptVi: "Người nói đang làm gì?",
          audioText: "Good morning.",
          options: ["Chào buổi sáng", "Hỏi giá", "Nói màu"],
          answer: "Chào buổi sáng",
          targetIds: ["m04-greeting"],
        },
        {
          id: "m04e-p2",
          kind: "select",
          promptVi: "Chọn câu hỏi thăm trạng thái.",
          options: ["How are you?", "What is this?", "How much is it?"],
          answer: "How are you?",
          targetIds: ["m04-how-are-you"],
        },
        {
          id: "m04e-p3",
          kind: "order",
          promptVi: "Xếp câu: Tôi ổn, cảm ơn.",
          tokens: ["thank", "I'm", "you", "fine"],
          answer: "I'm fine thank you",
          targetIds: ["m04-state"],
        },
        {
          id: "m04e-p4",
          kind: "recall",
          promptVi: "Tự nhớ câu có nghĩa: Còn bạn?",
          answer: "And you?",
          acceptedAnswers: ["And you"],
          targetIds: ["m04-and-you"],
        },
      ],
    },
    {
      id: "m04e-rehearsal",
      kind: "rehearsal",
      estimatedMinutes: 1,
      titleVi: "Ghép đúng chức năng",
      promptVi:
        "Nói bốn mảnh theo đúng thứ tự: lời chào, câu hỏi thăm, trạng thái của bạn, lời kết.",
      keyWords: ["morning", "how", "fine", "later"],
      targetIds: [
        "m04-greeting",
        "m04-how-are-you",
        "m04-state",
        "m04-closing",
      ],
    },
    {
      id: "m04e-performance",
      kind: "performance",
      estimatedMinutes: 1,
      titleVi: "Phản xạ xã giao 15 giây",
      task: {
        roleVi: "Người vừa gặp một người quen",
        contextVi: "Bạn chỉ có vài giây trước khi mỗi người đi một hướng.",
        goalVi: "Chào, trả lời trạng thái và kết thúc đúng lúc.",
        promptVi:
          "Lượt một dùng Good morning và fine. Lượt hai đổi sang Hello và okay.",
        successCriteriaVi: [
          "Bạn dùng đúng lời chào và lời kết.",
          "Người nghe hiểu được trạng thái bạn nói.",
        ],
        targetIds: ["m04-greeting", "m04-state", "m04-closing"],
        evidence: ["task_checklist", "self_assessment"],
        attempts: 2,
        preparationSeconds: 10,
        responseSeconds: 15,
        rubric: ["task_achievement", "comprehensibility"],
      },
    },
    {
      id: "m04e-feedback",
      kind: "feedback",
      estimatedMinutes: 1,
      titleVi: "Sửa tín hiệu xã giao",
      priorityOrder: ["task_achievement", "comprehensibility"],
      repairPromptsVi: [
        "Người nghe có biết lúc nào bạn bắt đầu và kết thúc không?",
        "Bạn có nói đủ I'm trước fine hoặc okay không?",
      ],
    },
    {
      id: "m04e-exit",
      kind: "exit",
      estimatedMinutes: 1,
      titleVi: "Chốt trình tự trao đổi",
      canDoCheckVi:
        "Tôi nhận ra lời chào, câu hỏi thăm, trạng thái và lời kết trong trao đổi rất ngắn.",
      reviewTargetIds: [
        "m04-greeting",
        "m04-how-are-you",
        "m04-state",
        "m04-closing",
      ],
      confidencePromptVi: "Bạn nhận ra được bốn vị trí mà không cần bản dịch chứ?",
    },
  ],
  tags: ["pre-a1", "module-04", "encounter", "greetings", "wellbeing"],
};

export const PRE_A1_M04_COMMUNICATE: LessonV2 = {
  schemaVersion: 2,
  id: "pre-a1-m04-communicate",
  missionId: "pre-a1-m04",
  legacyUnitId: "unit-a0-4",
  titleVi: "Bắt đầu và kết thúc một trao đổi xã giao",
  titleEn: "Open and close a basic social exchange",
  level: "PRE_A1",
  legacyLevel: "A0",
  estimatedMinutes: 10,
  primaryOutcome: {
    id: "pre-a1-m04-communicate-outcome",
    level: "PRE_A1",
    activity: "interaction",
    domain: "personal",
    statementEn:
      "Can greet someone, answer a basic wellbeing question, return the question and close the exchange.",
    statementVi:
      "Có thể chào, trả lời câu hỏi thăm, hỏi lại và kết thúc một trao đổi xã giao ngắn.",
    source: "ato-adapted",
    sourceReference: "CEFR Pre-A1 formulaic social interaction",
  },
  prerequisiteLessonIds: ["pre-a1-m04-encounter"],
  targets: GREETING_TARGETS,
  steps: [
    {
      id: "m04c-scenario",
      kind: "scenario",
      estimatedMinutes: 1,
      titleVi: "Gặp đồng nghiệp ở cửa thang máy",
      roleVi: "Bạn gặp một người quen trước giờ làm.",
      situationVi: "Hai người có thời gian cho một cuộc nói chuyện rất ngắn.",
      goalVi: "Tự mở, duy trì hai lượt và đóng trao đổi.",
    },
    {
      id: "m04c-model",
      kind: "model",
      estimatedMinutes: 1,
      titleVi: "Nghe một mẫu không có bản dịch",
      replayRates: [0.8, 1],
      turns: [
        {
          speaker: "A",
          text: "Good morning. How are you?",
          targetIds: ["m04-greeting", "m04-how-are-you"],
        },
        {
          speaker: "B",
          text: "I'm tired, thank you. And you?",
          targetIds: ["m04-state", "m04-and-you"],
        },
        {
          speaker: "A",
          text: "I'm okay. See you later.",
          targetIds: ["m04-state", "m04-closing"],
        },
      ],
    },
    {
      id: "m04c-notice",
      kind: "notice",
      estimatedMinutes: 1,
      titleVi: "Giữ lượt bằng And you?",
      targetIds: ["m04-state", "m04-and-you", "m04-closing"],
      explanationVi:
        "Sau câu trả lời ngắn, And you? trả lượt cho người đối diện. See you later đóng cuộc nói chuyện mà không bị cụt.",
    },
    {
      id: "m04c-practice",
      kind: "practice",
      estimatedMinutes: 2,
      titleVi: "Tự tạo từng lượt nói",
      adaptive: true,
      exercises: [
        {
          id: "m04c-p1",
          kind: "listen",
          promptVi: "Câu trả lời phù hợp nhất là gì?",
          audioText: "How are you?",
          options: ["I'm fine, thank you.", "This is a key.", "Card, please."],
          answer: "I'm fine, thank you.",
          targetIds: ["m04-how-are-you", "m04-state"],
        },
        {
          id: "m04c-p2",
          kind: "select",
          promptVi: "Chọn câu để hỏi lại người đối diện.",
          options: ["And you?", "See you later.", "Good morning."],
          answer: "And you?",
          targetIds: ["m04-and-you"],
        },
        {
          id: "m04c-p3",
          kind: "order",
          promptVi: "Xếp câu kết thúc.",
          tokens: ["later", "you", "See"],
          answer: "See you later",
          targetIds: ["m04-closing"],
        },
        {
          id: "m04c-p4",
          kind: "recall",
          promptVi: "Tự nhớ câu nói: Tôi mệt, cảm ơn.",
          answer: "I'm tired, thank you.",
          acceptedAnswers: ["I'm tired thank you", "I am tired, thank you."],
          targetIds: ["m04-state"],
        },
      ],
    },
    {
      id: "m04c-rehearsal",
      kind: "rehearsal",
      estimatedMinutes: 1,
      titleVi: "Đổi trạng thái mà không đổi cấu trúc",
      promptVi:
        "Chuẩn bị hai lượt bằng từ khóa. Lượt một fine; lượt hai tired. Không viết nguyên câu.",
      keyWords: ["morning", "fine", "and you", "later", "tired"],
      targetIds: [
        "m04-greeting",
        "m04-how-are-you",
        "m04-state",
        "m04-and-you",
        "m04-closing",
      ],
    },
    {
      id: "m04c-performance",
      kind: "performance",
      estimatedMinutes: 2,
      titleVi: "Trao đổi xã giao hai lượt",
      task: {
        roleVi: "Hai người quen gặp nhanh",
        contextVi: "Bạn cần chào, hỏi thăm, trả lời và rời đi lịch sự.",
        goalVi: "Hoàn thành một trao đổi có mở đầu, hai lượt và kết thúc.",
        promptVi:
          "Lượt một dùng Good morning/fine. Nhận góp ý rồi lượt hai dùng Hello/tired và tự hỏi lại bằng And you?",
        successCriteriaVi: [
          "Bạn hoàn thành đủ chào, hỏi, trả lời, hỏi lại và kết thúc.",
          "Người nghe hiểu trạng thái fine hoặc tired.",
          "Bạn không dừng đột ngột trước lời kết.",
        ],
        targetIds: [
          "m04-greeting",
          "m04-how-are-you",
          "m04-state",
          "m04-and-you",
          "m04-closing",
        ],
        evidence: ["task_checklist", "self_assessment"],
        attempts: 2,
        preparationSeconds: 15,
        responseSeconds: 20,
        rubric: ["task_achievement", "comprehensibility", "fluency"],
      },
    },
    {
      id: "m04c-feedback",
      kind: "feedback",
      estimatedMinutes: 1,
      titleVi: "Sửa một điểm rồi thực hiện lại",
      priorityOrder: ["task_achievement", "comprehensibility", "fluency"],
      repairPromptsVi: [
        "Bạn có hỏi lại bằng And you? hay chỉ trả lời một chiều?",
        "Bạn có giữ I'm trước tính từ trạng thái không?",
        "Bạn có kết thúc bằng See you later hoặc Goodbye không?",
      ],
    },
    {
      id: "m04c-exit",
      kind: "exit",
      estimatedMinutes: 1,
      titleVi: "Chốt trao đổi độc lập",
      canDoCheckVi:
        "Tôi bắt đầu, duy trì và kết thúc được một trao đổi xã giao rất ngắn.",
      reviewTargetIds: [
        "m04-greeting",
        "m04-how-are-you",
        "m04-state",
        "m04-and-you",
        "m04-closing",
      ],
      confidencePromptVi: "Lượt hai của bạn có chạy mà không nhìn mẫu chứ?",
    },
  ],
  tags: ["pre-a1", "module-04", "communicate", "greetings", "closing"],
};

export const PRE_A1_M04_RETAIN_TRANSFER: LessonV2 = {
  schemaVersion: 2,
  id: "pre-a1-m04-retain-transfer",
  missionId: "pre-a1-m04",
  legacyUnitId: "unit-a0-4",
  titleVi: "Nhớ lại lời chào trong bối cảnh mới",
  titleEn: "Recall and transfer a short greeting exchange",
  level: "PRE_A1",
  legacyLevel: "A0",
  estimatedMinutes: 9,
  primaryOutcome: {
    id: "pre-a1-m04-retain-outcome",
    level: "PRE_A1",
    activity: "interaction",
    domain: "public",
    statementEn:
      "Can recall and reuse a short greeting, wellbeing answer and closing in a different everyday encounter.",
    statementVi:
      "Có thể tự nhớ và dùng lại lời chào, câu trả lời trạng thái và lời kết trong một cuộc gặp khác.",
    source: "ato-adapted",
    sourceReference: "CEFR Pre-A1 transfer of formulaic social exchange",
  },
  prerequisiteLessonIds: ["pre-a1-m04-communicate"],
  targets: GREETING_TARGETS,
  steps: [
    {
      id: "m04r-scenario",
      kind: "scenario",
      estimatedMinutes: 1,
      titleVi: "Gặp hàng xóm vào cuối ngày",
      roleVi: "Bạn gặp hàng xóm ở hành lang.",
      situationVi: "Thời điểm và người nói thay đổi; bạn không được xem lại khung cũ.",
      goalVi: "Tự dùng lại trao đổi xã giao trong bối cảnh mới.",
    },
    {
      id: "m04r-model",
      kind: "model",
      estimatedMinutes: 1,
      titleVi: "Nghe một mẫu chuyển giao duy nhất",
      replayRates: [0.9],
      turns: [
        {
          speaker: "Neighbour",
          text: "Hello. How are you?",
          targetIds: ["m04-greeting", "m04-how-are-you"],
        },
        {
          speaker: "You",
          text: "I'm okay, thank you. And you?",
          targetIds: ["m04-state", "m04-and-you"],
        },
        {
          speaker: "Neighbour",
          text: "I'm fine. Goodbye.",
          targetIds: ["m04-state", "m04-closing"],
        },
      ],
    },
    {
      id: "m04r-notice",
      kind: "notice",
      estimatedMinutes: 1,
      titleVi: "Nhận ra phần thay đổi",
      targetIds: ["m04-greeting", "m04-state", "m04-closing"],
      explanationVi:
        "Người, thời điểm và trạng thái thay đổi; cấu trúc chức năng vẫn là chào → hỏi → trả lời → kết.",
    },
    {
      id: "m04r-practice",
      kind: "practice",
      estimatedMinutes: 2,
      titleVi: "Delayed recall không nhìn bài cũ",
      exercises: [
        {
          id: "m04r-p1",
          kind: "recall",
          promptVi: "Tự nhớ câu hỏi thăm.",
          answer: "How are you?",
          acceptedAnswers: ["How are you"],
          targetIds: ["m04-how-are-you"],
        },
        {
          id: "m04r-p2",
          kind: "listen",
          promptVi: "Người nói đang ở trạng thái nào?",
          audioText: "I'm tired, thank you.",
          options: ["Mệt", "Khỏe", "Không biết"],
          answer: "Mệt",
          targetIds: ["m04-state"],
        },
        {
          id: "m04r-p3",
          kind: "select",
          promptVi: "Chọn câu kết phù hợp.",
          options: ["See you later.", "What color is it?", "How much is it?"],
          answer: "See you later.",
          targetIds: ["m04-closing"],
        },
        {
          id: "m04r-p4",
          kind: "order",
          promptVi: "Xếp câu hỏi lại người đối diện.",
          tokens: ["you", "And"],
          answer: "And you",
          targetIds: ["m04-and-you"],
        },
      ],
    },
    {
      id: "m04r-rehearsal",
      kind: "rehearsal",
      estimatedMinutes: 1,
      titleVi: "Chuẩn bị bằng ý, không bằng câu",
      promptVi:
        "Chỉ nhìn ba ý: hello — tired — goodbye. Tự tạo phần còn lại.",
      keyWords: ["hello", "tired", "goodbye"],
      targetIds: [
        "m04-greeting",
        "m04-how-are-you",
        "m04-state",
        "m04-and-you",
        "m04-closing",
      ],
    },
    {
      id: "m04r-performance",
      kind: "performance",
      estimatedMinutes: 1,
      titleVi: "Transfer sang cuộc gặp khác",
      task: {
        roleVi: "Người gặp hàng xóm",
        contextVi: "Lượt hai người kia nói quá nhanh trước khi hỏi thăm.",
        goalVi: "Tự mở và đóng trao đổi, đồng thời xử lý một trục trặc.",
        promptVi:
          "Lượt một dùng okay. Lượt hai dùng tired và dùng Please say that again từ Module 1 nếu không nghe rõ.",
        successCriteriaVi: [
          "Bạn tự tạo được toàn bộ trao đổi mà không mở bài cũ.",
          "Bạn dùng lại được một câu sửa hiểu nhầm khi cần.",
          "Bạn kết thúc rõ ràng bằng lời chào tạm biệt.",
        ],
        targetIds: [
          "m04-greeting",
          "m04-how-are-you",
          "m04-state",
          "m04-and-you",
          "m04-closing",
        ],
        evidence: ["task_checklist", "self_assessment"],
        attempts: 2,
        preparationSeconds: 10,
        responseSeconds: 20,
        rubric: [
          "task_achievement",
          "comprehensibility",
          "interaction_repair",
        ],
      },
    },
    {
      id: "m04r-feedback",
      kind: "feedback",
      estimatedMinutes: 1,
      titleVi: "Đánh giá giữ được và chuyển được",
      priorityOrder: [
        "task_achievement",
        "comprehensibility",
        "interaction_repair",
      ],
      repairPromptsVi: [
        "Bạn có tự nhớ trình tự mà không nhìn Module 4 không?",
        "Bạn có dùng câu sửa hiểu nhầm từ Module 1 đúng lúc không?",
      ],
    },
    {
      id: "m04r-exit",
      kind: "exit",
      estimatedMinutes: 1,
      titleVi: "Chốt evidence transfer",
      canDoCheckVi:
        "Tôi tự chào, hỏi thăm, trả lời và kết thúc được trong một cuộc gặp mới.",
      reviewTargetIds: [
        "m04-greeting",
        "m04-how-are-you",
        "m04-state",
        "m04-and-you",
        "m04-closing",
      ],
      confidencePromptVi: "Bạn làm được mà không cần mở lại bài communicate chứ?",
    },
  ],
  tags: ["pre-a1", "module-04", "retain-transfer", "greetings", "repair"],
};

export const PRE_A1_MODULE_04_LESSONS: LessonV2[] = [
  PRE_A1_M04_ENCOUNTER,
  PRE_A1_M04_COMMUNICATE,
  PRE_A1_M04_RETAIN_TRANSFER,
];
