import type { LanguageTarget } from "./schema";

export const PERSONAL_DETAILS_TARGETS: LanguageTarget[] = [
  {
    id: "m05-age-question",
    kind: "chunk",
    form: "How old are you?",
    meaningVi: "Bạn bao nhiêu tuổi?",
    exampleEn: "How old are you?",
    exampleVi: "Bạn bao nhiêu tuổi?",
    priority: "support",
  },
  {
    id: "m05-age-answer",
    kind: "chunk",
    form: "I am ... years old.",
    meaningVi: "Tôi ... tuổi.",
    exampleEn: "I am eighteen years old.",
    exampleVi: "Tôi mười tám tuổi.",
    priority: "core",
    pronunciationGoal: "Nói rõ số tuổi và cụm years old.",
  },
  {
    id: "m05-from-question",
    kind: "chunk",
    form: "Where are you from?",
    meaningVi: "Bạn đến từ đâu?",
    exampleEn: "Where are you from?",
    exampleVi: "Bạn đến từ đâu?",
    priority: "support",
  },
  {
    id: "m05-from-answer",
    kind: "chunk",
    form: "I am from ...",
    meaningVi: "Tôi đến từ ...",
    exampleEn: "I am from Vietnam.",
    exampleVi: "Tôi đến từ Việt Nam.",
    priority: "core",
    pronunciationGoal: "Giữ from khác form và nhấn rõ tên quốc gia.",
  },
  {
    id: "m05-live-question",
    kind: "chunk",
    form: "Where do you live?",
    meaningVi: "Bạn sống ở đâu?",
    exampleEn: "Where do you live?",
    exampleVi: "Bạn sống ở đâu?",
    priority: "support",
  },
  {
    id: "m05-live-answer",
    kind: "chunk",
    form: "I live in ...",
    meaningVi: "Tôi sống ở ...",
    exampleEn: "I live in Da Nang.",
    exampleVi: "Tôi sống ở Đà Nẵng.",
    priority: "core",
  },
  {
    id: "m05-missing-detail",
    kind: "repair_strategy",
    form: "And your city?",
    meaningVi: "Còn thành phố của bạn?",
    exampleEn: "You are from Vietnam. And your city?",
    exampleVi: "Bạn đến từ Việt Nam. Còn thành phố của bạn?",
    priority: "core",
  },
];
