import { PRICE_TARGETS } from "./pre-a1-module-02-targets";
import type { LessonV2 } from "./schema";

export const PRE_A1_M02_ENCOUNTER: LessonV2 = {
  schemaVersion: 2,
  id: "pre-a1-m02-encounter",
  missionId: "pre-a1-m02",
  legacyUnitId: "unit-a0-2",
  titleVi: "Nhận ra câu hỏi giá và cách thanh toán",
  titleEn: "Recognise prices and payment choices",
  level: "PRE_A1",
  legacyLevel: "A0",
  estimatedMinutes: 10,
  primaryOutcome: {
    id: "pre-a1-m02-encounter-outcome",
    level: "PRE_A1",
    activity: "reception",
    domain: "public",
    statementEn:
      "Can recognise a basic price question, a short price answer and the words cash or card.",
    statementVi:
      "Có thể nhận ra câu hỏi giá, câu trả lời số tiền ngắn và lựa chọn tiền mặt hoặc thẻ.",
    source: "ato-adapted",
    sourceReference: "CEFR Pre-A1 reception in simple transactions",
  },
  prerequisiteLessonIds: ["pre-a1-m01-retain-transfer"],
  targets: PRICE_TARGETS,
  steps: [
    {
      id: "m02e-scenario",
      kind: "scenario",
      estimatedMinutes: 1,
      titleVi: "Mua nước ở quầy nhỏ",
      roleVi: "Bạn là khách mua hàng.",
      situationVi: "Bạn cần nghe giá và chọn trả tiền mặt hoặc thẻ.",
      goalVi: "Nhận ra câu hỏi giá, số tiền và hai cách thanh toán.",
    },
    {
      id: "m02e-model",
      kind: "model",
      estimatedMinutes: 2,
      titleVi: "Nghe giao dịch cực ngắn",
      replayRates: [0.65, 0.85],
      turns: [
        {
          speaker: "Customer",
          text: "How much is it?",
          translationVi: "Món này giá bao nhiêu?",
          targetIds: ["m02-how-much"],
        },
        {
          speaker: "Cashier",
          text: "It is five dollars.",
          translationVi: "Giá là năm đô-la.",
          targetIds: ["m02-price"],
        },
        {
          speaker: "Cashier",
          text: "Cash or card?",
          translationVi: "Tiền mặt hay thẻ?",
        },
        {
          speaker: "Customer",
          text: "Card, please.",
          translationVi: "Thẻ nhé.",
          targetIds: ["m02-card"],
        },
      ],
    },
    {
      id: "m02e-notice",
      kind: "notice",
      estimatedMinutes: 1,
      titleVi: "Nhìn bốn tín hiệu giao dịch",
      targetIds: ["m02-how-much", "m02-price", "m02-cash", "m02-card"],
      explanationVi:
        "Tập trung vào How much, số tiền và từ cuối cash/card; chưa cần hiểu mọi từ.",
    },
    {
      id: "m02e-practice",
      kind: "practice",
      estimatedMinutes: 2,
      titleVi: "Nghe, chọn và tự nhớ",
      adaptive: true,
      exercises: [
        {
          id: "m02e-p1",
          kind: "listen",
          promptVi: "Người nói đang hỏi gì?",
          audioText: "How much is it?",
          options: ["Hỏi giá", "Hỏi tên", "Chào tạm biệt"],
          answer: "Hỏi giá",
          targetIds: ["m02-how-much"],
        },
        {
          id: "m02e-p2",
          kind: "select",
          promptVi: "Chọn câu có nghĩa: Giá là năm đô-la.",
          options: [
            "It is five dollars.",
            "Cash, please.",
            "How much is it?",
          ],
          answer: "It is five dollars.",
          targetIds: ["m02-price"],
        },
        {
          id: "m02e-p3",
          kind: "order",
          promptVi: "Xếp câu chọn trả bằng thẻ.",
          tokens: ["please", "Card"],
          answer: "Card please",
          targetIds: ["m02-card"],
        },
        {
          id: "m02e-p4",
          kind: "recall",
          promptVi: "Tự nhớ và gõ câu hỏi giá.",
          answer: "How much is it?",
          acceptedAnswers: ["How much is it"],
          targetIds: ["m02-how-much"],
        },
      ],
    },
    {
      id: "m02e-rehearsal",
      kind: "rehearsal",
      estimatedMinutes: 1,
      titleVi: "Đổi số tiền",
      promptVi: "Đọc khung với 5, rồi đổi sang 8 mà không nhìn bản dịch.",
      frameEn: "How much is it? It is ____ dollars.",
      keyWords: ["five", "eight", "dollars"],
      targetIds: ["m02-how-much", "m02-price"],
    },
    {
      id: "m02e-performance",
      kind: "performance",
      estimatedMinutes: 1,
      titleVi: "Phản xạ giao dịch 15 giây",
      task: {
        roleVi: "Khách mua hàng",
        contextVi: "Bạn nhìn thấy một món đồ không có bảng giá.",
        goalVi: "Hỏi giá, nhận số tiền và chọn cash hoặc card.",
        promptVi: "Lượt hai, đổi số tiền và đổi cách thanh toán.",
        successCriteriaVi: [
          "Bạn nhận ra đúng số tiền.",
          "Bạn chọn được cash hoặc card bằng tiếng Anh.",
        ],
        targetIds: ["m02-how-much", "m02-price", "m02-cash", "m02-card"],
        evidence: ["task_checklist", "self_assessment"],
        attempts: 2,
        preparationSeconds: 15,
        responseSeconds: 15,
        rubric: ["task_achievement", "comprehensibility"],
      },
    },
    {
      id: "m02e-feedback",
      kind: "feedback",
      estimatedMinutes: 1,
      titleVi: "Sửa điểm gây nhầm",
      priorityOrder: ["task_achievement", "comprehensibility"],
      repairPromptsVi: [
        "Bạn có nghe đúng số tiền không?",
        "Cash và card có được nói đủ rõ để người nghe phân biệt không?",
      ],
    },
    {
      id: "m02e-exit",
      kind: "exit",
      estimatedMinutes: 1,
      titleVi: "Chốt tín hiệu giao dịch",
      canDoCheckVi:
        "Tôi nhận ra câu hỏi giá, số tiền và lựa chọn tiền mặt hoặc thẻ.",
      reviewTargetIds: ["m02-how-much", "m02-price", "m02-cash", "m02-card"],
      confidencePromptVi: "Không nhìn mẫu, bạn nhận ra được mấy tín hiệu?",
    },
  ],
  tags: ["pre-a1", "module-02", "encounter", "transaction"],
};
