import { getMissionForLesson } from "@/lib/missions/mission-catalog";

export interface UnitMetadata {
  id: string;
  title: string;
  description: string;
  level: string;
  route: string;
  xp: number;
  estimatedTime: number;
  tags: string[];
}

// A0 Foundation Curriculum — 8 units — Pre-CEFR / True Beginner
// For Vietnamese adult learners with zero prior English exposure.
// Grammar progression: Verb BE (name) → Numbers → Adjective order →
//   Greetings → Personal info → Family pronouns → AT/ON/IN → Imperative
//
// A1 Curriculum — 12 units — CEFR-aligned progression
// Grammar progression: To be → Wh-Q → Possessives → Present Simple →
//   like+V-ing → There is/are → How much → Countable/Uncountable →
//   Prepositions → Can/Can't → have/feel → Review
const BASE_UNITS: UnitMetadata[] = [
  // ─── A0 Foundation — 8 units ─────────────────────────────────────────────────
  {
    id: "unit-a0-1",
    title: "Unit A0-1: Bảng Chữ Cái & Âm Cơ Bản",
    description: "Học 26 chữ cái tiếng Anh và cách phát âm cơ bản — nền tảng đầu tiên của hành trình học tiếng Anh.",
    level: "A0",
    route: "/learn/unit-a0-1",
    xp: 60,
    estimatedTime: 45,
    tags: ["Từ vựng +10", "Bảng chữ cái", "My name is"],
  },
  {
    id: "unit-a0-2",
    title: "Unit A0-2: Số Đếm & Đếm Số",
    description: "Học số từ 1–20 và cách hỏi giá tiền — từ vựng thiết yếu trong mọi giao dịch hàng ngày.",
    level: "A0",
    route: "/learn/unit-a0-2",
    xp: 60,
    estimatedTime: 40,
    tags: ["Từ vựng +10", "Số đếm", "How much/many"],
  },
  {
    id: "unit-a0-3",
    title: "Unit A0-3: Màu Sắc & Mô Tả",
    description: "Học từ vựng về màu sắc và kích thước — nền tảng để mô tả mọi thứ xung quanh bạn.",
    level: "A0",
    route: "/learn/unit-a0-3",
    xp: 60,
    estimatedTime: 40,
    tags: ["Từ vựng +10", "Màu sắc", "Tính từ trước danh từ"],
  },
  {
    id: "unit-a0-4",
    title: "Unit A0-4: Chào Hỏi & Câu Xã Giao",
    description: "Học cách chào hỏi lịch sự và những câu xã giao thiết yếu — ấn tượng đầu tiên là ấn tượng quan trọng nhất!",
    level: "A0",
    route: "/learn/unit-a0-4",
    xp: 60,
    estimatedTime: 40,
    tags: ["Từ vựng +10", "Chào hỏi", "How are you?"],
  },
  {
    id: "unit-a0-5",
    title: "Unit A0-5: Thông Tin Cá Nhân",
    description: "Học cách giới thiệu bản thân đầy đủ: tên, tuổi, quốc tịch và nơi sống — những thông tin cơ bản nhất.",
    level: "A0",
    route: "/learn/unit-a0-5",
    xp: 60,
    estimatedTime: 45,
    tags: ["Từ vựng +10", "Giới thiệu", "Verb BE đầy đủ"],
  },
  {
    id: "unit-a0-6",
    title: "Unit A0-6: Gia Đình & Những Người Thân",
    description: "Học từ vựng về gia đình và cách mô tả người thân — nội dung giao tiếp hàng ngày không thể thiếu.",
    level: "A0",
    route: "/learn/unit-a0-6",
    xp: 60,
    estimatedTime: 40,
    tags: ["Từ vựng +10", "Gia đình", "He/She/They"],
  },
  {
    id: "unit-a0-7",
    title: "Unit A0-7: Thời Gian, Ngày & Tháng",
    description: "Học cách nói giờ, ngày trong tuần và các buổi trong ngày — thiết yếu để đặt lịch và hẹn hò bằng tiếng Anh.",
    level: "A0",
    route: "/learn/unit-a0-7",
    xp: 60,
    estimatedTime: 40,
    tags: ["Từ vựng +10", "Thời gian", "AT/ON/IN"],
  },
  {
    id: "unit-a0-8",
    title: "Unit A0-8: Khẩn Cấp & Cụm Từ Sinh Tồn",
    description: "Học những câu tiếng Anh quan trọng nhất trong tình huống khẩn cấp — kiến thức có thể cứu mạng bạn!",
    level: "A0",
    route: "/learn/unit-a0-8",
    xp: 80,
    estimatedTime: 45,
    tags: ["Từ vựng +10", "Khẩn cấp", "Imperative + Please"],
  },
  {
    id: "unit-1",
    title: "Unit 1: Greetings & Self-Introduction",
    description: "Học cách chào hỏi cơ bản, tự giới thiệu bản thân bằng tiếng Anh và thực hành phản xạ nói Shadowing / Roleplay.",
    level: "A1",
    route: "/learn/unit-1",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +10", "Giao tiếp", "To be"],
  },
  {
    id: "unit-2",
    title: "Unit 2: Personal Information",
    description: "Học cách hỏi và trả lời về thông tin cá nhân: tên, tuổi, nghề nghiệp và nơi sống bằng Wh- questions.",
    level: "A1",
    route: "/learn/unit-2",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Wh- Questions", "Nghề nghiệp"],
  },
  {
    id: "unit-3",
    title: "Unit 3: Family & Friends",
    description: "Mô tả gia đình, bạn bè và học cách sử dụng đại từ sở hữu cơ bản (my, his, her, their...).",
    level: "A1",
    route: "/learn/unit-3",
    xp: 80,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Gia đình", "Đại từ sở hữu"],
  },
  {
    id: "unit-4",
    title: "Unit 4: Daily Routines",
    description: "Học từ vựng về hoạt động thường nhật và cách dùng thì Hiện Tại Đơn để mô tả thói quen.",
    level: "A1",
    route: "/learn/unit-4",
    xp: 80,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Lịch trình", "Present Simple"],
  },
  {
    id: "unit-5",
    title: "Unit 5: Free Time & Hobbies",
    description: "Học cách nói về sở thích và hoạt động giải trí bằng cấu trúc 'like + V-ing'.",
    level: "A1",
    route: "/learn/unit-5",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Sở thích", "like + V-ing"],
  },
  {
    id: "unit-6",
    title: "Unit 6: Home & Daily Life",
    description: "Học từ vựng về nhà ở, đồ đạc và cách dùng 'There is/are' để mô tả không gian.",
    level: "A1",
    route: "/learn/unit-6",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Nhà cửa", "There is/are"],
  },
  {
    id: "unit-7",
    title: "Unit 7: Shopping & Prices",
    description: "Học từ vựng mua sắm, cách hỏi giá bằng 'How much is/are...?' và mặc cả tự nhiên.",
    level: "A1",
    route: "/learn/unit-7",
    xp: 85,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Mua sắm", "How much"],
  },
  {
    id: "unit-8",
    title: "Unit 8: Food & Ordering",
    description: "Học từ vựng đồ ăn, cách gọi món và phân biệt Countable/Uncountable nouns.",
    level: "A1",
    route: "/learn/unit-8",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Đồ ăn", "Countable/Uncountable"],
  },
  {
    id: "unit-9",
    title: "Unit 9: Places & Directions",
    description: "Học từ vựng địa điểm, cách hỏi và chỉ đường bằng giới từ nơi chốn (next to, opposite, between).",
    level: "A1",
    route: "/learn/unit-9",
    xp: 80,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Địa điểm", "Giới từ"],
  },
  {
    id: "unit-10",
    title: "Unit 10: Abilities & Daily Skills",
    description: "Học cách nói về khả năng bản thân bằng 'can/can't' và hỏi về kỹ năng của người khác.",
    level: "A1",
    route: "/learn/unit-10",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Kỹ năng", "Can / Can't"],
  },
  {
    id: "unit-11",
    title: "Unit 11: Health & Feelings",
    description: "Học từ vựng về sức khỏe, cảm xúc và cách diễn đạt tình trạng bản thân bằng 'have/feel'.",
    level: "A1",
    route: "/learn/unit-11",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Sức khỏe", "have / feel"],
  },
  {
    id: "unit-12",
    title: "Unit 12: Review & Real-life Application",
    description: "Ôn tập toàn bộ ngữ pháp và từ vựng A1, áp dụng vào các tình huống giao tiếp thực tế. Tổng hợp hành trình A1.",
    level: "A1",
    route: "/learn/unit-12",
    xp: 120,
    estimatedTime: 60,
    tags: ["Ôn tập tổng hợp", "Giao tiếp thực tế", "A1 Complete"],
  },

  // ─── A2 Curriculum — 6 units ─────────────────────────────────────────────────
  // Grammar progression: Past Simple → will/going to → Comparatives →
  //   Directions/Prepositions → Present Perfect → A2 Review
  {
    id: "unit-13",
    title: "Unit 13: Past Experiences",
    description: "Học cách kể về sự kiện và trải nghiệm đã xảy ra bằng Past Simple. Động từ quy tắc và bất quy tắc thông dụng nhất.",
    level: "A2",
    route: "/learn/unit-13",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Trải nghiệm", "Past Simple"],
  },
  {
    id: "unit-14",
    title: "Unit 14: Future Plans & Predictions",
    description: "Học cách nói về kế hoạch đã lên sẵn bằng 'going to' và đưa ra dự đoán bằng 'will' trong ngữ cảnh công việc.",
    level: "A2",
    route: "/learn/unit-14",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Kế hoạch", "will / going to"],
  },
  {
    id: "unit-15",
    title: "Unit 15: Shopping & Comparing",
    description: "Học từ vựng mua sắm và so sánh sản phẩm bằng Comparative (-er/more) và Superlative (-est/most).",
    level: "A2",
    route: "/learn/unit-15",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Mua sắm", "Comparatives"],
  },
  {
    id: "unit-16",
    title: "Unit 16: Travel & Directions",
    description: "Học cách hỏi và chỉ đường, mô tả địa điểm và đặt phòng khách sạn bằng tiếng Anh chuẩn.",
    level: "A2",
    route: "/learn/unit-16",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Du lịch", "Prepositions of Place"],
  },
  {
    id: "unit-17",
    title: "Unit 17: Experiences & Present Perfect",
    description: "Học Present Perfect để nói về kinh nghiệm sống, thành tích sự nghiệp và những điều bạn đã từng làm.",
    level: "A2",
    route: "/learn/unit-17",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Kinh nghiệm", "Present Perfect"],
  },
  {
    id: "unit-18",
    title: "Unit 18: A2 Review & Real-life Communication",
    description: "Ôn tập toàn bộ A2: Past Simple, will/going to, Comparatives và Present Perfect trong ngữ cảnh họp quốc tế.",
    level: "A2",
    route: "/learn/unit-18",
    xp: 120,
    estimatedTime: 55,
    tags: ["Ôn tập A2", "Giao tiếp quốc tế", "A2 Complete"],
  },

  // ─── B1 Curriculum — 14 units ─────────────────────────────────────────────
  // Target: TOEIC 450–600 | IELTS 4.5–5.5
  // Grammar progression: Past Continuous → Past Perfect → Future Advanced →
  //   Modals → Zero/First Conditional → Passive → Relative Clauses →
  //   Gerund/Infinitive → Phrasal Verbs → Present Perfect Continuous →
  //   Discussion → Abstract Topics → Formal Writing → B1 Review
  {
    id: "unit-19",
    title: "Unit 19: Stories & Narratives",
    description: "Học Past Continuous để kể chuyện có diễn tiến — 'I was working when the power went out.' Nền tảng storytelling chuyên nghiệp.",
    level: "B1",
    route: "/learn/unit-19",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Past Continuous", "Storytelling"],
  },
  {
    id: "unit-20",
    title: "Unit 20: News & Current Events",
    description: "Học Past Perfect để nói về sự kiện xảy ra trước một mốc thời gian quá khứ — 'By the time I arrived, the meeting had already started.'",
    level: "B1",
    route: "/learn/unit-20",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Past Perfect", "Tin tức"],
  },
  {
    id: "unit-21",
    title: "Unit 21: Predictions & Trends",
    description: "Nắm vững Future Continuous và Future Perfect — 'By 2030, AI will have transformed most industries.' Thảo luận xu hướng như người bản ngữ.",
    level: "B1",
    route: "/learn/unit-21",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Future Advanced", "Xu hướng"],
  },
  {
    id: "unit-22",
    title: "Unit 22: Rules & Obligations",
    description: "Phân biệt must/have to/should/needn't trong ngữ cảnh quy định nơi làm việc và cuộc sống hàng ngày.",
    level: "B1",
    route: "/learn/unit-22",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Must/Have to", "Quy định"],
  },
  {
    id: "unit-23",
    title: "Unit 23: If & When",
    description: "Thành thạo Zero & First Conditionals — nói về điều kiện thực tế trong kinh doanh và cuộc sống: 'If you heat water to 100°C, it boils.'",
    level: "B1",
    route: "/learn/unit-23",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Conditionals 0&1", "Điều kiện"],
  },
  {
    id: "unit-24",
    title: "Unit 24: How Things Are Made",
    description: "Học Passive Voice để mô tả quy trình và sự kiện không cần nhấn mạnh chủ thể — 'The report was submitted yesterday.'",
    level: "B1",
    route: "/learn/unit-24",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Passive Voice", "Quy trình"],
  },
  {
    id: "unit-25",
    title: "Unit 25: Describing People & Places",
    description: "Dùng Relative Clauses (who, which, that, where) để mô tả chi tiết và phức tạp hơn — 'The colleague who helped me is very experienced.'",
    level: "B1",
    route: "/learn/unit-25",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Relative Clauses", "Mô tả"],
  },
  {
    id: "unit-26",
    title: "Unit 26: Likes, Dislikes & Preferences",
    description: "Phân biệt Gerund vs Infinitive trong ngữ cảnh thực tế — enjoy doing vs want to do. Lỗi người Việt cực hay mắc.",
    level: "B1",
    route: "/learn/unit-26",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Gerund vs Infinitive", "Sở thích"],
  },
  {
    id: "unit-27",
    title: "Unit 27: Get Things Done",
    description: "Nắm 20 phrasal verbs thiết yếu nhất trong tiếng Anh công sở và học thuật — look up, give up, carry out, deal with...",
    level: "B1",
    route: "/learn/unit-27",
    xp: 100,
    estimatedTime: 55,
    tags: ["Phrasal Verbs +12", "Công sở", "Giao tiếp tự nhiên"],
  },
  {
    id: "unit-28",
    title: "Unit 28: How Long Have You Been...?",
    description: "Học Present Perfect Continuous để nói về hoạt động đang diễn ra từ quá khứ đến hiện tại — 'I've been studying English for 6 months.'",
    level: "B1",
    route: "/learn/unit-28",
    xp: 100,
    estimatedTime: 50,
    tags: ["Từ vựng +12", "Pres. Perfect Continuous", "Kinh nghiệm"],
  },
  {
    id: "unit-29",
    title: "Unit 29: Problems & Solutions",
    description: "Phát triển kỹ năng thảo luận vấn đề và đề xuất giải pháp — nền tảng cho IELTS Speaking Part 3 và TOEIC Part 3 conversations.",
    level: "B1",
    route: "/learn/unit-29",
    xp: 100,
    estimatedTime: 55,
    tags: ["Từ vựng +12", "Discussion Skills", "IELTS Speaking"],
  },
  {
    id: "unit-30",
    title: "Unit 30: Health & Global Issues",
    description: "Thảo luận các vấn đề sức khỏe và môi trường — vocabulary và structures để nói về abstract topics như người B1+.",
    level: "B1",
    route: "/learn/unit-30",
    xp: 100,
    estimatedTime: 55,
    tags: ["Từ vựng +12", "Abstract Topics", "IELTS Vocab"],
  },
  {
    id: "unit-31",
    title: "Unit 31: Business Communication",
    description: "Học ngôn ngữ formal và reporting verbs (suggest/recommend/advise) để viết email và báo cáo chuyên nghiệp.",
    level: "B1",
    route: "/learn/unit-31",
    xp: 100,
    estimatedTime: 55,
    tags: ["Từ vựng +12", "Formal Writing", "Email"],
  },
  {
    id: "unit-32",
    title: "Unit 32: B1 Review & Mock Test",
    description: "Ôn tập toàn bộ B1. Mini mock test IELTS/TOEIC level B1. Điểm dự kiến sau unit này: IELTS ~5.0, TOEIC ~500.",
    level: "B1",
    route: "/learn/unit-32",
    xp: 150,
    estimatedTime: 70,
    tags: ["Ôn tập B1", "Mock Test", "B1 Complete"],
  },

  // ─── B2 Curriculum — 10 units ─────────────────────────────────────────────
  // Target: TOEIC 785+ | IELTS 6.5+
  // Grammar progression: Second Conditional → Third Conditional → Mixed →
  //   Advanced Passive → Participle Clauses → Inversion/Cleft →
  //   Modal Perfect → Discourse Markers → Thematic Vocab → B2 Final
  {
    id: "unit-33",
    title: "Unit 33: Imagining & Hypothesizing",
    description: "Second Conditional — nói về điều không có thật ở hiện tại: 'If I were the CEO, I would change the strategy.' Thiết yếu cho phỏng vấn xin việc.",
    level: "B2",
    route: "/learn/unit-33",
    xp: 120,
    estimatedTime: 60,
    tags: ["Từ vựng +12", "Second Conditional", "Hypothetical"],
  },
  {
    id: "unit-34",
    title: "Unit 34: Past Regrets & What-ifs",
    description: "Third Conditional — phân tích điều đã không xảy ra: 'If we had launched earlier, we would have captured the market.' Thiết yếu cho IELTS Writing.",
    level: "B2",
    route: "/learn/unit-34",
    xp: 120,
    estimatedTime: 60,
    tags: ["Từ vựng +12", "Third Conditional", "Phân tích"],
  },
  {
    id: "unit-35",
    title: "Unit 35: Advanced Conditions",
    description: "Mixed Conditionals và các biến thể: unless/provided that/even if/as long as. Đàm phán và điều kiện trong hợp đồng như người bản ngữ.",
    level: "B2",
    route: "/learn/unit-35",
    xp: 120,
    estimatedTime: 60,
    tags: ["Từ vựng +12", "Mixed Conditionals", "Đàm phán"],
  },
  {
    id: "unit-36",
    title: "Unit 36: Academic & Formal Passive",
    description: "Advanced Passive với reporting verbs — 'It is claimed that / It has been found that.' Nền tảng cho IELTS Writing Task 1 & 2.",
    level: "B2",
    route: "/learn/unit-36",
    xp: 120,
    estimatedTime: 60,
    tags: ["Từ vựng +12", "Advanced Passive", "Academic"],
  },
  {
    id: "unit-37",
    title: "Unit 37: Concise & Precise Language",
    description: "Participle Clauses để viết súc tích và chuyên nghiệp — 'Having finished the report, she presented it.' Đặc trưng của B2+ writing.",
    level: "B2",
    route: "/learn/unit-37",
    xp: 120,
    estimatedTime: 60,
    tags: ["Từ vựng +12", "Participle Clauses", "Writing B2"],
  },
  {
    id: "unit-38",
    title: "Unit 38: Emphasis & Persuasion",
    description: "Inversion và Cleft sentences để nhấn mạnh và thuyết phục — 'Not only did he finish early, but he also exceeded the target.' IELTS Band 7+ structures.",
    level: "B2",
    route: "/learn/unit-38",
    xp: 120,
    estimatedTime: 60,
    tags: ["Từ vựng +12", "Inversion", "Persuasion"],
  },
  {
    id: "unit-39",
    title: "Unit 39: Speculation & Deduction",
    description: "Modal Perfect để suy luận về quá khứ — 'She must have worked all night / He can't have forgotten the meeting.' Quan trọng cho IELTS Listening.",
    level: "B2",
    route: "/learn/unit-39",
    xp: 120,
    estimatedTime: 60,
    tags: ["Từ vựng +12", "Modal Perfect", "Suy luận"],
  },
  {
    id: "unit-40",
    title: "Unit 40: Linking & Cohesion",
    description: "30 discourse markers quan trọng nhất — nevertheless, consequently, furthermore, thereby. Chìa khoá để đạt IELTS Writing 6.5+.",
    level: "B2",
    route: "/learn/unit-40",
    xp: 120,
    estimatedTime: 60,
    tags: ["Discourse Markers +8", "Writing Cohesion", "IELTS 6.5"],
  },
  {
    id: "unit-41",
    title: "Unit 41: IELTS & TOEIC Topics",
    description: "60 từ vựng học thuật về 5 chủ đề IELTS phổ biến: môi trường, công nghệ, giáo dục, sức khỏe, xã hội. TOEIC business vocab nâng cao.",
    level: "B2",
    route: "/learn/unit-41",
    xp: 120,
    estimatedTime: 65,
    tags: ["Academic Vocab +16", "IELTS Topics", "TOEIC Advanced"],
  },
  {
    id: "unit-42",
    title: "Unit 42: B2 Final Assessment",
    description: "Ôn tập toàn diện A0→B2. Practice test IELTS Reading + Listening + TOEIC Part 5/6/7. Mục tiêu: IELTS 6.5+ / TOEIC 785+.",
    level: "B2",
    route: "/learn/unit-42",
    xp: 200,
    estimatedTime: 90,
    tags: ["Final Assessment", "IELTS 6.5", "TOEIC 785+"],
  },
];

/**
 * Canonical unit catalog used by dashboard, roadmap and server actions.
 * Pilot mission metadata overrides legacy curriculum labels so every product
 * surface describes the same lesson the learner will actually open.
 */
export const UNITS: UnitMetadata[] = BASE_UNITS.map((unit) => {
  const mission = getMissionForLesson(unit.id);
  if (!mission) return unit;

  return {
    ...unit,
    title: `Bài ${unit.id.replace("unit-", "").toUpperCase()}: ${mission.titleVi}`,
    description: mission.canDoVi,
    estimatedTime: mission.estimatedMinutes,
    tags: [
      "Nhiệm vụ giao tiếp",
      ...mission.targetChunks.slice(0, 2).map((chunk) => chunk.english),
    ],
  };
});
