export interface UnitMetadata {
  id: string;
  title: string;
  description: string;
  level: string;
  route: string;
  xp: number;
  estimatedTime: number;
  tags: string[];
}

// A1 Curriculum — 12 units — CEFR-aligned progression
// Grammar progression: To be → Wh-Q → Possessives → Present Simple →
//   like+V-ing → There is/are → How much → Countable/Uncountable →
//   Prepositions → Can/Can't → have/feel → Review
export const UNITS: UnitMetadata[] = [
  {
    id: "unit-1",
    title: "Unit 1: Greetings & Self-Introduction",
    description: "Học cách chào hỏi cơ bản, tự giới thiệu bản thân bằng tiếng Anh và thực hành phản xạ nói Shadowing / Roleplay.",
    level: "A1",
    route: "/learn/unit-1",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Giao tiếp", "To be"],
  },
  {
    id: "unit-2",
    title: "Unit 2: Personal Information",
    description: "Học cách hỏi và trả lời về thông tin cá nhân: tên, tuổi, nghề nghiệp và nơi sống bằng Wh- questions.",
    level: "A1",
    route: "/learn/unit-2",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Wh- Questions", "Nghề nghiệp"],
  },
  {
    id: "unit-3",
    title: "Unit 3: Family & Friends",
    description: "Mô tả gia đình, bạn bè và học cách sử dụng đại từ sở hữu cơ bản (my, his, her, their...).",
    level: "A1",
    route: "/learn/unit-3",
    xp: 80,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Gia đình", "Đại từ sở hữu"],
  },
  {
    id: "unit-4",
    title: "Unit 4: Daily Routines",
    description: "Học từ vựng về hoạt động thường nhật và cách dùng thì Hiện Tại Đơn để mô tả thói quen.",
    level: "A1",
    route: "/learn/unit-4",
    xp: 80,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Lịch trình", "Present Simple"],
  },
  {
    id: "unit-5",
    title: "Unit 5: Free Time & Hobbies",
    description: "Học cách nói về sở thích và hoạt động giải trí bằng cấu trúc 'like + V-ing'.",
    level: "A1",
    route: "/learn/unit-5",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Sở thích", "like + V-ing"],
  },
  {
    id: "unit-6",
    title: "Unit 6: Home & Daily Life",
    description: "Học từ vựng về nhà ở, đồ đạc và cách dùng 'There is/are' để mô tả không gian.",
    level: "A1",
    route: "/learn/unit-6",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Nhà cửa", "There is/are"],
  },
  {
    id: "unit-7",
    title: "Unit 7: Shopping & Prices",
    description: "Học từ vựng mua sắm, cách hỏi giá bằng 'How much is/are...?' và mặc cả tự nhiên.",
    level: "A1",
    route: "/learn/unit-7",
    xp: 85,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Mua sắm", "How much"],
  },
  {
    id: "unit-8",
    title: "Unit 8: Food & Ordering",
    description: "Học từ vựng đồ ăn, cách gọi món và phân biệt Countable/Uncountable nouns.",
    level: "A1",
    route: "/learn/unit-8",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Đồ ăn", "Countable/Uncountable"],
  },
  {
    id: "unit-9",
    title: "Unit 9: Places & Directions",
    description: "Học từ vựng địa điểm, cách hỏi và chỉ đường bằng giới từ nơi chốn (next to, opposite, between).",
    level: "A1",
    route: "/learn/unit-9",
    xp: 80,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Địa điểm", "Giới từ"],
  },
  {
    id: "unit-10",
    title: "Unit 10: Abilities & Daily Skills",
    description: "Học cách nói về khả năng bản thân bằng 'can/can't' và hỏi về kỹ năng của người khác.",
    level: "A1",
    route: "/learn/unit-10",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Kỹ năng", "Can / Can't"],
  },
  {
    id: "unit-11",
    title: "Unit 11: Health & Feelings",
    description: "Học từ vựng về sức khỏe, cảm xúc và cách diễn đạt tình trạng bản thân bằng 'have/feel'.",
    level: "A1",
    route: "/learn/unit-11",
    xp: 80,
    estimatedTime: 40,
    tags: ["Từ vựng +12", "Sức khỏe", "have / feel"],
  },
  {
    id: "unit-12",
    title: "Unit 12: Review & Real-life Application",
    description: "Ôn tập toàn bộ ngữ pháp và từ vựng A1, áp dụng vào các tình huống giao tiếp thực tế. Tổng hợp hành trình A1.",
    level: "A1",
    route: "/learn/unit-12",
    xp: 120,
    estimatedTime: 60,
    tags: ["Ôn tập tổng hợp", "Giao tiếp thực tế", "A1 Complete"],
  },

  // ─── A2 Curriculum — 6 units ─────────────────────────────────────────────────
  // Grammar progression: Past Simple → will/going to → Comparatives →
  //   Directions/Prepositions → Present Perfect → A2 Review
  {
    id: "unit-13",
    title: "Unit 13: Past Experiences",
    description: "Học cách kể về sự kiện và trải nghiệm đã xảy ra bằng Past Simple. Động từ quy tắc và bất quy tắc thông dụng nhất.",
    level: "A2",
    route: "/learn/unit-13",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Trải nghiệm", "Past Simple"],
  },
  {
    id: "unit-14",
    title: "Unit 14: Future Plans & Predictions",
    description: "Học cách nói về kế hoạch đã lên sẵn bằng 'going to' và đưa ra dự đoán bằng 'will' trong ngữ cảnh công việc.",
    level: "A2",
    route: "/learn/unit-14",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Kế hoạch", "will / going to"],
  },
  {
    id: "unit-15",
    title: "Unit 15: Shopping & Comparing",
    description: "Học từ vựng mua sắm và so sánh sản phẩm bằng Comparative (-er/more) và Superlative (-est/most).",
    level: "A2",
    route: "/learn/unit-15",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Mua sắm", "Comparatives"],
  },
  {
    id: "unit-16",
    title: "Unit 16: Travel & Directions",
    description: "Học cách hỏi và chỉ đường, mô tả địa điểm và đặt phòng khách sạn bằng tiếng Anh chuẩn.",
    level: "A2",
    route: "/learn/unit-16",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Du lịch", "Prepositions of Place"],
  },
  {
    id: "unit-17",
    title: "Unit 17: Experiences & Present Perfect",
    description: "Học Present Perfect để nói về kinh nghiệm sống, thành tích sự nghiệp và những điều bạn đã từng làm.",
    level: "A2",
    route: "/learn/unit-17",
    xp: 90,
    estimatedTime: 45,
    tags: ["Từ vựng +12", "Kinh nghiệm", "Present Perfect"],
  },
  {
    id: "unit-18",
    title: "Unit 18: A2 Review & Real-life Communication",
    description: "Ôn tập toàn bộ A2: Past Simple, will/going to, Comparatives và Present Perfect trong ngữ cảnh họp quốc tế.",
    level: "A2",
    route: "/learn/unit-18",
    xp: 120,
    estimatedTime: 55,
    tags: ["Ôn tập A2", "Giao tiếp quốc tế", "A2 Complete"],
  },
];
