export interface VocabularyItem {
  word: string;
  phonetic: string;
  meaning_vn: string;
  example_en: string;
  topic: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1";
}

export const UNIT_VOCABULARY: Record<string, VocabularyItem[]> = {
  "unit-1": [
    {
      word: "hello",
      phonetic: "/həˈləʊ/",
      meaning_vn: "Xin chào",
      example_en: "Hello! How are you doing today?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "hi",
      phonetic: "/haɪ/",
      meaning_vn: "Chào (thân mật)",
      example_en: "Hi! Nice to meet you.",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "good morning",
      phonetic: "/ɡʊd ˈmɔː.nɪŋ/",
      meaning_vn: "Chào buổi sáng",
      example_en: "Good morning, teacher! How are you?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "goodbye",
      phonetic: "/ˌɡʊdˈbaɪ/",
      meaning_vn: "Tạm biệt",
      example_en: "Goodbye, see you again tomorrow.",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "nice to meet you",
      phonetic: "/naɪs tuː miːt juː/",
      meaning_vn: "Rất vui được gặp bạn",
      example_en: "I am Alex. Nice to meet you!",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "my name is",
      phonetic: "/maɪ neɪm ɪz/",
      meaning_vn: "Tên tôi là...",
      example_en: "My name is Linh and I am from Vietnam.",
      topic: "Self-Introduction",
      level: "A1",
    },
    {
      word: "i am from",
      phonetic: "/aɪ æm frɒm/",
      meaning_vn: "Tôi đến từ...",
      example_en: "I am from Hanoi, Vietnam.",
      topic: "Self-Introduction",
      level: "A1",
    },
    {
      word: "how are you",
      phonetic: "/haʊ ɑː juː/",
      meaning_vn: "Bạn có khỏe không?",
      example_en: "Hi Bob, how are you?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "i am fine thank you",
      phonetic: "/aɪ æm faɪn θæŋk juː/",
      meaning_vn: "Tôi khỏe, cảm ơn bạn",
      example_en: "I am fine thank you, and you?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "and you",
      phonetic: "/ænd juː/",
      meaning_vn: "Còn bạn thì sao?",
      example_en: "I am doing great, and you?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "thank you",
      phonetic: "/θæŋk juː/",
      meaning_vn: "Cảm ơn bạn",
      example_en: "Thank you for your warm welcome.",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "please",
      phonetic: "/pliːz/",
      meaning_vn: "Làm ơn / Vui lòng",
      example_en: "Please excuse me, I must go now.",
      topic: "Greetings",
      level: "A1",
    },
  ],
  "unit-2": [
    {
      word: "wake up",
      phonetic: "/weɪk ʌp/",
      meaning_vn: "Thức dậy",
      example_en: "I usually wake up at 6 AM.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "brush teeth",
      phonetic: "/brʌʃ tiːθ/",
      meaning_vn: "Đánh răng",
      example_en: "You should brush your teeth twice a day.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "wash face",
      phonetic: "/wɒʃ feɪs/",
      meaning_vn: "Rửa mặt",
      example_en: "I wash my face with cold water.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "eat breakfast",
      phonetic: "/iːt ˈbrek.fəst/",
      meaning_vn: "Ăn sáng",
      example_en: "Do you eat breakfast every morning?",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "go to school",
      phonetic: "/ɡəʊ tuː skuːl/",
      meaning_vn: "Đi học",
      example_en: "We go to school by bus.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "go to work",
      phonetic: "/ɡəʊ tuː wɜːk/",
      meaning_vn: "Đi làm",
      example_en: "My father goes to work at 8 o'clock.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "watch tv",
      phonetic: "/wɒtʃ ˌtiːˈviː/",
      meaning_vn: "Xem tivi",
      example_en: "I watch TV for an hour after dinner.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "go to bed",
      phonetic: "/ɡəʊ tuː bed/",
      meaning_vn: "Đi ngủ",
      example_en: "I go to bed at 10 PM.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "what time is it?",
      phonetic: "/wɒt taɪm ɪz ɪt/",
      meaning_vn: "Mấy giờ rồi?",
      example_en: "Excuse me, what time is it?",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "o'clock",
      phonetic: "/əˈklɒk/",
      meaning_vn: "Giờ đúng",
      example_en: "It is exactly 7 o'clock.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "half past",
      phonetic: "/hɑːf pɑːst/",
      meaning_vn: "Giờ rưỡi / Qua 30 phút",
      example_en: "We meet at half past eight.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "quarter",
      phonetic: "/ˈkwɔː.tər/",
      meaning_vn: "15 phút",
      example_en: "It is a quarter past nine.",
      topic: "Daily Routines",
      level: "A1",
    }
  ],
  "unit-3": [
    {
      word: "mother",
      phonetic: "/ˈmʌð.ər/",
      meaning_vn: "Mẹ",
      example_en: "My mother is a teacher.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "father",
      phonetic: "/ˈfɑː.ðər/",
      meaning_vn: "Bố",
      example_en: "My father loves cooking.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "brother",
      phonetic: "/ˈbrʌð.ər/",
      meaning_vn: "Anh/Em trai",
      example_en: "I have one older brother.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "sister",
      phonetic: "/ˈsɪs.tər/",
      meaning_vn: "Chị/Em gái",
      example_en: "She is my younger sister.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "parents",
      phonetic: "/ˈpeə.rənts/",
      meaning_vn: "Bố mẹ",
      example_en: "My parents live in Da Nang.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "friend",
      phonetic: "/frend/",
      meaning_vn: "Bạn bè",
      example_en: "We are good friends.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "classmate",
      phonetic: "/ˈklɑːs.meɪt/",
      meaning_vn: "Bạn cùng lớp",
      example_en: "Minh is my classmate.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "happy",
      phonetic: "/ˈhæp.i/",
      meaning_vn: "Hạnh phúc",
      example_en: "They are a happy family.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "my",
      phonetic: "/maɪ/",
      meaning_vn: "Của tôi",
      example_en: "This is my book.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "your",
      phonetic: "/jɔːr/",
      meaning_vn: "Của bạn",
      example_en: "What is your phone number?",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "his",
      phonetic: "/hɪz/",
      meaning_vn: "Của anh ấy",
      example_en: "His name is Peter.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "her",
      phonetic: "/hɜːr/",
      meaning_vn: "Của cô ấy",
      example_en: "Her hair is brown.",
      topic: "Family & Friends",
      level: "A1",
    }
  ],
  "unit-4": [
    { 
      word: "artificial intelligence", 
      phonetic: "/ˌɑː.tɪ.fɪʃ.əl ɪnˈtel.ɪ.dʒəns/", 
      meaning_vn: "Trí tuệ nhân tạo",
      example_en: "In the 21st century, artificial intelligence has become omnipresent.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "omnipresent", 
      phonetic: "/ˌɒm.nɪˈprez.ənt/", 
      meaning_vn: "Có mặt ở khắp mọi nơi",
      example_en: "Smartphones have become omnipresent in modern society.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "revolutionize", 
      phonetic: "/ˌrev.əˈluː.ʃən.aɪz/", 
      meaning_vn: "Cách mạng hóa",
      example_en: "AI technologies are beginning to revolutionize how society operates.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "ethics", 
      phonetic: "/ˈeθ.ɪks/", 
      meaning_vn: "Đạo đức",
      example_en: "We need to discuss the ethics of artificial intelligence.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "security", 
      phonetic: "/sɪˈkjʊə.rə.ti/", 
      meaning_vn: "Bảo mật / An ninh",
      example_en: "Data security is very important online.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "algorithm", 
      phonetic: "/ˈæl.ɡə.rɪ.ðəm/", 
      meaning_vn: "Thuật toán",
      example_en: "The search engine uses a complex algorithm.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "integrate", 
      phonetic: "/ˈɪn.tɪ.ɡreɪt/", 
      meaning_vn: "Tích hợp",
      example_en: "We should integrate technology into our classroom.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "fabric", 
      phonetic: "/ˈfæb.rɪk/", 
      meaning_vn: "Cấu trúc / Sợi vải",
      example_en: "Technology is woven into our social fabric.",
      topic: "Technology",
      level: "B1"
    }
  ]
};
