export interface VocabularyItem {
  word: string;
  phonetic: string;
  meaning_vn: string;
  example_en: string;
  topic: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1";
}

export const UNIT_VOCABULARY: Record<string, VocabularyItem[]> = {
  "unit-1": [
    {
      word: "hello",
      phonetic: "/həˈləʊ/",
      meaning_vn: "Xin chào",
      example_en: "Hello! How are you doing today?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "hi",
      phonetic: "/haɪ/",
      meaning_vn: "Chào (thân mật)",
      example_en: "Hi! Nice to meet you.",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "good morning",
      phonetic: "/ɡʊd ˈmɔː.nɪŋ/",
      meaning_vn: "Chào buổi sáng",
      example_en: "Good morning, teacher! How are you?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "goodbye",
      phonetic: "/ˌɡʊdˈbaɪ/",
      meaning_vn: "Tạm biệt",
      example_en: "Goodbye, see you again tomorrow.",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "nice to meet you",
      phonetic: "/naɪs tuː miːt juː/",
      meaning_vn: "Rất vui được gặp bạn",
      example_en: "I am Alex. Nice to meet you!",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "my name is",
      phonetic: "/maɪ neɪm ɪz/",
      meaning_vn: "Tên tôi là...",
      example_en: "My name is Linh and I am from Vietnam.",
      topic: "Self-Introduction",
      level: "A1",
    },
    {
      word: "i am from",
      phonetic: "/aɪ æm frɒm/",
      meaning_vn: "Tôi đến từ...",
      example_en: "I am from Hanoi, Vietnam.",
      topic: "Self-Introduction",
      level: "A1",
    },
    {
      word: "how are you",
      phonetic: "/haʊ ɑː juː/",
      meaning_vn: "Bạn có khỏe không?",
      example_en: "Hi Bob, how are you?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "i am fine thank you",
      phonetic: "/aɪ æm faɪn θæŋk juː/",
      meaning_vn: "Tôi khỏe, cảm ơn bạn",
      example_en: "I am fine thank you, and you?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "and you",
      phonetic: "/ænd juː/",
      meaning_vn: "Còn bạn thì sao?",
      example_en: "I am doing great, and you?",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "thank you",
      phonetic: "/θæŋk juː/",
      meaning_vn: "Cảm ơn bạn",
      example_en: "Thank you for your warm welcome.",
      topic: "Greetings",
      level: "A1",
    },
    {
      word: "please",
      phonetic: "/pliːz/",
      meaning_vn: "Làm ơn / Vui lòng",
      example_en: "Please excuse me, I must go now.",
      topic: "Greetings",
      level: "A1",
    },
  ],
  "unit-2": [
    {
      word: "wake up",
      phonetic: "/weɪk ʌp/",
      meaning_vn: "Thức dậy",
      example_en: "I usually wake up at 6 AM.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "brush teeth",
      phonetic: "/brʌʃ tiːθ/",
      meaning_vn: "Đánh răng",
      example_en: "You should brush your teeth twice a day.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "wash face",
      phonetic: "/wɒʃ feɪs/",
      meaning_vn: "Rửa mặt",
      example_en: "I wash my face with cold water.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "eat breakfast",
      phonetic: "/iːt ˈbrek.fəst/",
      meaning_vn: "Ăn sáng",
      example_en: "Do you eat breakfast every morning?",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "go to school",
      phonetic: "/ɡəʊ tuː skuːl/",
      meaning_vn: "Đi học",
      example_en: "We go to school by bus.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "go to work",
      phonetic: "/ɡəʊ tuː wɜːk/",
      meaning_vn: "Đi làm",
      example_en: "My father goes to work at 8 o'clock.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "watch tv",
      phonetic: "/wɒtʃ ˌtiːˈviː/",
      meaning_vn: "Xem tivi",
      example_en: "I watch TV for an hour after dinner.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "go to bed",
      phonetic: "/ɡəʊ tuː bed/",
      meaning_vn: "Đi ngủ",
      example_en: "I go to bed at 10 PM.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "what time is it?",
      phonetic: "/wɒt taɪm ɪz ɪt/",
      meaning_vn: "Mấy giờ rồi?",
      example_en: "Excuse me, what time is it?",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "o'clock",
      phonetic: "/əˈklɒk/",
      meaning_vn: "Giờ đúng",
      example_en: "It is exactly 7 o'clock.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "half past",
      phonetic: "/hɑːf pɑːst/",
      meaning_vn: "Giờ rưỡi / Qua 30 phút",
      example_en: "We meet at half past eight.",
      topic: "Daily Routines",
      level: "A1",
    },
    {
      word: "quarter",
      phonetic: "/ˈkwɔː.tər/",
      meaning_vn: "15 phút",
      example_en: "It is a quarter past nine.",
      topic: "Daily Routines",
      level: "A1",
    }
  ],
  "unit-3": [
    {
      word: "mother",
      phonetic: "/ˈmʌð.ər/",
      meaning_vn: "Mẹ",
      example_en: "My mother is a teacher.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "father",
      phonetic: "/ˈfɑː.ðər/",
      meaning_vn: "Bố",
      example_en: "My father loves cooking.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "brother",
      phonetic: "/ˈbrʌð.ər/",
      meaning_vn: "Anh/Em trai",
      example_en: "I have one older brother.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "sister",
      phonetic: "/ˈsɪs.tər/",
      meaning_vn: "Chị/Em gái",
      example_en: "She is my younger sister.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "parents",
      phonetic: "/ˈpeə.rənts/",
      meaning_vn: "Bố mẹ",
      example_en: "My parents live in Da Nang.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "friend",
      phonetic: "/frend/",
      meaning_vn: "Bạn bè",
      example_en: "We are good friends.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "classmate",
      phonetic: "/ˈklɑːs.meɪt/",
      meaning_vn: "Bạn cùng lớp",
      example_en: "Minh is my classmate.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "happy",
      phonetic: "/ˈhæp.i/",
      meaning_vn: "Hạnh phúc",
      example_en: "They are a happy family.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "my",
      phonetic: "/maɪ/",
      meaning_vn: "Của tôi",
      example_en: "This is my book.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "your",
      phonetic: "/jɔːr/",
      meaning_vn: "Của bạn",
      example_en: "What is your phone number?",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "his",
      phonetic: "/hɪz/",
      meaning_vn: "Của anh ấy",
      example_en: "His name is Peter.",
      topic: "Family & Friends",
      level: "A1",
    },
    {
      word: "her",
      phonetic: "/hɜːr/",
      meaning_vn: "Của cô ấy",
      example_en: "Her hair is brown.",
      topic: "Family & Friends",
      level: "A1",
    }
  ],
  // A2 Shopping vocabulary — matches /learn/unit-4 content (unit5.ts data)
  "unit-4": [
    { word: "buy", phonetic: "/baɪ/", meaning_vn: "mua", example_en: "I want to buy some fruit.", topic: "Shopping", level: "A2" },
    { word: "sell", phonetic: "/sɛl/", meaning_vn: "bán", example_en: "They sell vegetables here.", topic: "Shopping", level: "A2" },
    { word: "price", phonetic: "/praɪs/", meaning_vn: "giá cả", example_en: "What is the price of this shirt?", topic: "Shopping", level: "A2" },
    { word: "cheap", phonetic: "/tʃiːp/", meaning_vn: "rẻ", example_en: "This market is cheap and fresh.", topic: "Shopping", level: "A2" },
    { word: "expensive", phonetic: "/ɪkˈspɛnsɪv/", meaning_vn: "đắt tiền", example_en: "That bag is too expensive for me.", topic: "Shopping", level: "A2" },
    { word: "discount", phonetic: "/ˈdɪskɑʊnt/", meaning_vn: "giảm giá", example_en: "Is there a discount for students?", topic: "Shopping", level: "A2" },
    { word: "market", phonetic: "/ˈmɑːrkɪt/", meaning_vn: "chợ", example_en: "The night market opens at 6 PM.", topic: "Shopping", level: "A2" },
    { word: "money", phonetic: "/ˈmʌni/", meaning_vn: "tiền", example_en: "I don't have enough money today.", topic: "Shopping", level: "A2" },
    { word: "receipt", phonetic: "/rɪˈsiːt/", meaning_vn: "hóa đơn / biên lai", example_en: "Please keep your receipt for a refund.", topic: "Shopping", level: "A2" },
    { word: "cashier", phonetic: "/kæˈʃɪər/", meaning_vn: "thu ngân", example_en: "The cashier gave me the wrong change.", topic: "Shopping", level: "A2" },
    { word: "refund", phonetic: "/ˈriːfʌnd/", meaning_vn: "hoàn tiền", example_en: "Can I get a refund for this broken item?", topic: "Shopping", level: "A2" },
    { word: "exchange", phonetic: "/ɪksˈtʃeɪndʒ/", meaning_vn: "đổi hàng", example_en: "I would like to exchange this for a larger size.", topic: "Shopping", level: "A2" },
  ],
  // B1 Technology vocabulary — matches /learn/unit-5 content (unit4.ts data)
  "unit-5": [
    { 
      word: "artificial intelligence", 
      phonetic: "/ˌɑː.tɪ.fɪʃ.əl ɪnˈtel.ɪ.dʒəns/", 
      meaning_vn: "Trí tuệ nhân tạo",
      example_en: "In the 21st century, artificial intelligence has become omnipresent.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "omnipresent", 
      phonetic: "/ˌɒm.nɪˈprez.ənt/", 
      meaning_vn: "Có mặt ở khắp mọi nơi",
      example_en: "Smartphones have become omnipresent in modern society.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "revolutionize", 
      phonetic: "/ˌrev.əˈluː.ʃən.aɪz/", 
      meaning_vn: "Cách mạng hóa",
      example_en: "AI technologies are beginning to revolutionize how society operates.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "ethics", 
      phonetic: "/ˈeθ.ɪks/", 
      meaning_vn: "Đạo đức",
      example_en: "We need to discuss the ethics of artificial intelligence.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "security", 
      phonetic: "/sɪˈkjʊə.rə.ti/", 
      meaning_vn: "Bảo mật / An ninh",
      example_en: "Data security is very important online.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "algorithm", 
      phonetic: "/ˈæl.ɡə.rɪ.ðəm/", 
      meaning_vn: "Thuật toán",
      example_en: "The search engine uses a complex algorithm.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "integrate", 
      phonetic: "/ˈɪn.tɪ.ɡreɪt/", 
      meaning_vn: "Tích hợp",
      example_en: "We should integrate technology into our classroom.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "fabric", 
      phonetic: "/ˈfæb.rɪk/", 
      meaning_vn: "Cấu trúc / Sợi vải",
      example_en: "Technology is woven into our social fabric.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "innovation", 
      phonetic: "/ˌɪn.əˈveɪ.ʃən/", 
      meaning_vn: "Sự đổi mới / Đổi sáng tạo",
      example_en: "Technological innovation is changing every industry.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "automation", 
      phonetic: "/ˌɔː.təˈmeɪ.ʃən/", 
      meaning_vn: "Tự động hóa",
      example_en: "Automation may replace many factory jobs in the future.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "bandwidth", 
      phonetic: "/ˈbænd.wɪdθ/", 
      meaning_vn: "Băng thông",
      example_en: "You need high bandwidth to stream 4K videos.",
      topic: "Technology",
      level: "B1"
    },
    { 
      word: "privacy", 
      phonetic: "/ˈprɪv.ə.si/", 
      meaning_vn: "Quyền riêng tư",
      example_en: "Online privacy is a major concern for internet users.",
      topic: "Technology",
      level: "B1"
    }
  ],
};

// ─── A2 Vocabulary ────────────────────────────────────────────────────────────
// Extend UNIT_VOCABULARY with A2 unit entries
Object.assign(UNIT_VOCABULARY, {
  "unit-13": [
    { word: "went", phonetic: "/went/", meaning_vn: "đã đi (quá khứ của go)", example_en: "I went to the beach last weekend.", topic: "Past Experiences", level: "A2" },
    { word: "had", phonetic: "/hæd/", meaning_vn: "đã có / đã ăn", example_en: "We had a great time at the party.", topic: "Past Experiences", level: "A2" },
    { word: "visited", phonetic: "/ˈvɪzɪtɪd/", meaning_vn: "đã thăm / đã ghé thăm", example_en: "She visited her family last Sunday.", topic: "Past Experiences", level: "A2" },
    { word: "traveled", phonetic: "/ˈtrævəld/", meaning_vn: "đã du lịch", example_en: "We traveled to Japan last year.", topic: "Past Experiences", level: "A2" },
    { word: "stayed", phonetic: "/steɪd/", meaning_vn: "đã ở lại", example_en: "They stayed at a hotel near the beach.", topic: "Past Experiences", level: "A2" },
    { word: "met", phonetic: "/met/", meaning_vn: "đã gặp (quá khứ của meet)", example_en: "I met an old friend at the coffee shop.", topic: "Past Experiences", level: "A2" },
    { word: "watched", phonetic: "/wɒtʃt/", meaning_vn: "đã xem", example_en: "We watched a great movie last night.", topic: "Past Experiences", level: "A2" },
    { word: "enjoyed", phonetic: "/ɪnˈdʒɔɪd/", meaning_vn: "đã thích / đã thưởng thức", example_en: "I really enjoyed the trip.", topic: "Past Experiences", level: "A2" },
    { word: "ago", phonetic: "/əˈɡəʊ/", meaning_vn: "trước đây", example_en: "She started this job two years ago.", topic: "Past Experiences", level: "A2" },
    { word: "last", phonetic: "/lɑːst/", meaning_vn: "trước (tuần/tháng/năm)", example_en: "I saw the doctor last week.", topic: "Past Experiences", level: "A2" },
    { word: "yesterday", phonetic: "/ˈjestədeɪ/", meaning_vn: "hôm qua", example_en: "I worked from home yesterday.", topic: "Past Experiences", level: "A2" },
    { word: "cooked", phonetic: "/kʊkt/", meaning_vn: "đã nấu ăn", example_en: "He cooked dinner for the whole family.", topic: "Past Experiences", level: "A2" },
  ] as const,
  "unit-14": [
    { word: "plan", phonetic: "/plæn/", meaning_vn: "kế hoạch", example_en: "What are your plans for next month?", topic: "Future Plans", level: "A2" },
    { word: "meeting", phonetic: "/ˈmiːtɪŋ/", meaning_vn: "cuộc họp", example_en: "I have an important meeting at 10 AM.", topic: "Future Plans", level: "A2" },
    { word: "deadline", phonetic: "/ˈdedlaɪn/", meaning_vn: "hạn chót", example_en: "The project deadline is next Friday.", topic: "Future Plans", level: "A2" },
    { word: "project", phonetic: "/ˈprɒdʒekt/", meaning_vn: "dự án", example_en: "We are going to start a new project.", topic: "Future Plans", level: "A2" },
    { word: "launch", phonetic: "/lɔːntʃ/", meaning_vn: "ra mắt / khởi chạy", example_en: "They will launch the new app next quarter.", topic: "Future Plans", level: "A2" },
    { word: "probably", phonetic: "/ˈprɒbəbli/", meaning_vn: "có thể / chắc là", example_en: "It will probably be a very busy week.", topic: "Future Plans", level: "A2" },
    { word: "soon", phonetic: "/suːn/", meaning_vn: "sớm", example_en: "The results will be ready soon.", topic: "Future Plans", level: "A2" },
    { word: "hope", phonetic: "/həʊp/", meaning_vn: "hy vọng", example_en: "I hope to get a promotion this year.", topic: "Future Plans", level: "A2" },
    { word: "prepare", phonetic: "/prɪˈpeər/", meaning_vn: "chuẩn bị", example_en: "I am going to prepare the presentation tonight.", topic: "Future Plans", level: "A2" },
    { word: "improve", phonetic: "/ɪmˈpruːv/", meaning_vn: "cải thiện / tiến bộ", example_en: "I'm going to improve my English this year.", topic: "Future Plans", level: "A2" },
    { word: "schedule", phonetic: "/ˈʃedjuːl/", meaning_vn: "lịch trình / lên lịch", example_en: "Let's schedule a call for Monday morning.", topic: "Future Plans", level: "A2" },
    { word: "next", phonetic: "/nekst/", meaning_vn: "tiếp theo / tới", example_en: "I'm going to start a new course next month.", topic: "Future Plans", level: "A2" },
  ] as const,
  "unit-15": [
    { word: "cheap", phonetic: "/tʃiːp/", meaning_vn: "rẻ", example_en: "This market has cheap and fresh vegetables.", topic: "Shopping", level: "A2" },
    { word: "expensive", phonetic: "/ɪkˈspensɪv/", meaning_vn: "đắt tiền", example_en: "That designer bag is too expensive for me.", topic: "Shopping", level: "A2" },
    { word: "quality", phonetic: "/ˈkwɒlɪti/", meaning_vn: "chất lượng", example_en: "The quality of this product is excellent.", topic: "Shopping", level: "A2" },
    { word: "discount", phonetic: "/ˈdɪskaʊnt/", meaning_vn: "giảm giá", example_en: "The store offers a 20% discount on weekends.", topic: "Shopping", level: "A2" },
    { word: "receipt", phonetic: "/rɪˈsiːt/", meaning_vn: "hóa đơn", example_en: "Always ask for a receipt when you buy something.", topic: "Shopping", level: "A2" },
    { word: "refund", phonetic: "/ˈriːfʌnd/", meaning_vn: "hoàn tiền", example_en: "Can I get a refund if the product is broken?", topic: "Shopping", level: "A2" },
    { word: "better", phonetic: "/ˈbetər/", meaning_vn: "tốt hơn", example_en: "This model is better than the previous one.", topic: "Shopping", level: "A2" },
    { word: "best", phonetic: "/best/", meaning_vn: "tốt nhất", example_en: "That shop has the best deals in the city.", topic: "Shopping", level: "A2" },
    { word: "warranty", phonetic: "/ˈwɒrənti/", meaning_vn: "bảo hành", example_en: "This laptop comes with a two-year warranty.", topic: "Shopping", level: "A2" },
    { word: "brand", phonetic: "/brænd/", meaning_vn: "thương hiệu", example_en: "Which brand of phone do you prefer?", topic: "Shopping", level: "A2" },
    { word: "afford", phonetic: "/əˈfɔːrd/", meaning_vn: "có khả năng chi trả", example_en: "I can't afford a new car right now.", topic: "Shopping", level: "A2" },
    { word: "compare", phonetic: "/kəmˈpeər/", meaning_vn: "so sánh", example_en: "Compare the prices before you buy.", topic: "Shopping", level: "A2" },
  ] as const,
  "unit-16": [
    { word: "straight", phonetic: "/streɪt/", meaning_vn: "thẳng", example_en: "Go straight for two blocks then turn right.", topic: "Travel", level: "A2" },
    { word: "turn", phonetic: "/tɜːrn/", meaning_vn: "rẽ / quay", example_en: "Turn left at the traffic lights.", topic: "Travel", level: "A2" },
    { word: "corner", phonetic: "/ˈkɔːrnər/", meaning_vn: "góc đường", example_en: "The pharmacy is on the corner.", topic: "Travel", level: "A2" },
    { word: "opposite", phonetic: "/ˈɒpəzɪt/", meaning_vn: "đối diện", example_en: "The bank is opposite the post office.", topic: "Travel", level: "A2" },
    { word: "nearby", phonetic: "/ˌnɪərˈbaɪ/", meaning_vn: "gần đây", example_en: "Is there a coffee shop nearby?", topic: "Travel", level: "A2" },
    { word: "book", phonetic: "/bʊk/", meaning_vn: "đặt trước", example_en: "I'd like to book a room for three nights.", topic: "Travel", level: "A2" },
    { word: "available", phonetic: "/əˈveɪləbəl/", meaning_vn: "còn trống / có sẵn", example_en: "Is a double room available for tonight?", topic: "Travel", level: "A2" },
    { word: "check in", phonetic: "/tʃek ɪn/", meaning_vn: "nhận phòng", example_en: "Check-in time is 2 PM at this hotel.", topic: "Travel", level: "A2" },
    { word: "distance", phonetic: "/ˈdɪstəns/", meaning_vn: "khoảng cách", example_en: "The office is within walking distance.", topic: "Travel", level: "A2" },
    { word: "landmark", phonetic: "/ˈlændmɑːrk/", meaning_vn: "địa danh / mốc nhà", example_en: "Use the tall red building as a landmark.", topic: "Travel", level: "A2" },
    { word: "traffic lights", phonetic: "/ˈtræfɪk laɪts/", meaning_vn: "đèn giao thông", example_en: "Stop at the traffic lights and wait.", topic: "Travel", level: "A2" },
    { word: "block", phonetic: "/blɒk/", meaning_vn: "dãy nhà", example_en: "Walk three blocks north to reach the park.", topic: "Travel", level: "A2" },
  ] as const,
  "unit-17": [
    { word: "experience", phonetic: "/ɪkˈspɪəriəns/", meaning_vn: "kinh nghiệm / trải nghiệm", example_en: "She has five years of experience in marketing.", topic: "Experiences", level: "A2" },
    { word: "ever", phonetic: "/ˈevər/", meaning_vn: "từng / bao giờ", example_en: "Have you ever worked in another country?", topic: "Experiences", level: "A2" },
    { word: "never", phonetic: "/ˈnevər/", meaning_vn: "chưa bao giờ", example_en: "I have never eaten durian before.", topic: "Experiences", level: "A2" },
    { word: "already", phonetic: "/ɔːlˈredi/", meaning_vn: "đã (rồi)", example_en: "I've already sent the email to the client.", topic: "Experiences", level: "A2" },
    { word: "yet", phonetic: "/jet/", meaning_vn: "chưa / rồi chưa", example_en: "Have you finished the project report yet?", topic: "Experiences", level: "A2" },
    { word: "just", phonetic: "/dʒʌst/", meaning_vn: "vừa mới", example_en: "I've just arrived at the airport.", topic: "Experiences", level: "A2" },
    { word: "achieve", phonetic: "/əˈtʃiːv/", meaning_vn: "đạt được", example_en: "She has achieved excellent results this year.", topic: "Experiences", level: "A2" },
    { word: "since", phonetic: "/sɪns/", meaning_vn: "từ khi (mốc thời gian)", example_en: "He has lived in Hanoi since 2018.", topic: "Experiences", level: "A2" },
    { word: "for", phonetic: "/fɔːr/", meaning_vn: "trong (khoảng thời gian)", example_en: "I've worked here for three years.", topic: "Experiences", level: "A2" },
    { word: "recently", phonetic: "/ˈriːsəntli/", meaning_vn: "gần đây", example_en: "She has recently joined our team.", topic: "Experiences", level: "A2" },
    { word: "certificate", phonetic: "/sərˈtɪfɪkət/", meaning_vn: "chứng chỉ / chứng nhận", example_en: "She received a certificate in project management.", topic: "Experiences", level: "A2" },
    { word: "accomplished", phonetic: "/əˈkʌmplɪʃt/", meaning_vn: "có thành tích / đã hoàn thành", example_en: "He is a very accomplished software engineer.", topic: "Experiences", level: "A2" },
  ] as const,
  "unit-18": [
    { word: "achieved", phonetic: "/əˈtʃiːvd/", meaning_vn: "đã đạt được", example_en: "We achieved 120% of our annual sales target.", topic: "Review", level: "A2" },
    { word: "report", phonetic: "/rɪˈpɔːrt/", meaning_vn: "báo cáo", example_en: "I need to submit my weekly report by Friday.", topic: "Review", level: "A2" },
    { word: "quarter", phonetic: "/ˈkwɔːrtər/", meaning_vn: "quý (3 tháng)", example_en: "Our targets for next quarter are more ambitious.", topic: "Review", level: "A2" },
    { word: "increased", phonetic: "/ɪnˈkriːst/", meaning_vn: "đã tăng lên", example_en: "Revenue increased by 15% compared to last year.", topic: "Review", level: "A2" },
    { word: "target", phonetic: "/ˈtɑːrɡɪt/", meaning_vn: "mục tiêu / chỉ tiêu", example_en: "We met our sales target three months in a row.", topic: "Review", level: "A2" },
    { word: "challenge", phonetic: "/ˈtʃælɪndʒ/", meaning_vn: "thách thức", example_en: "The biggest challenge was acquiring new customers.", topic: "Review", level: "A2" },
    { word: "successful", phonetic: "/səkˈsesfəl/", meaning_vn: "thành công", example_en: "The product launch was very successful.", topic: "Review", level: "A2" },
    { word: "strategy", phonetic: "/ˈstrætɪdʒi/", meaning_vn: "chiến lược", example_en: "We need a new marketing strategy for next year.", topic: "Review", level: "A2" },
    { word: "progress", phonetic: "/ˈprɒɡres/", meaning_vn: "tiến độ / tiến bộ", example_en: "My English progress has been excellent this year.", topic: "Review", level: "A2" },
    { word: "opportunity", phonetic: "/ˌɒpərˈtjuːnɪti/", meaning_vn: "cơ hội", example_en: "This project is a great opportunity to grow.", topic: "Review", level: "A2" },
    { word: "fluent", phonetic: "/ˈfluːənt/", meaning_vn: "thành thạo / trôi chảy", example_en: "After 18 units, I'm becoming more fluent in English.", topic: "Review", level: "A2" },
    { word: "compared to", phonetic: "/kəmˈpeərd tuː/", meaning_vn: "so với", example_en: "This year's results are better compared to last year.", topic: "Review", level: "A2" },
  ] as const,
} satisfies Record<string, VocabularyItem[]>);
