import type { LessonSpec } from "@/lib/v2/lesson-spec";

/** P0 — parts of day + Good morning… + basic o'clock */
export const lessonA006: LessonSpec = {
  id: "l-a0-06",
  phase: "P0",
  cefr: "A0",
  title_vi: "Thời gian trong ngày",
  estimatedMin: 32,
  canDo: [
    "Nói các phần trong ngày: morning, afternoon, evening, night",
    "Chào theo thời gian: Good morning / afternoon / evening / Good night",
    "Nói giờ tròn cơ bản: … o'clock (It's seven o'clock)",
  ],
  situation:
    "Bạn gặp đồng nghiệp hoặc khách nước ngoài vào buổi sáng, chiều, tối. Bạn cần chào đúng (Good morning…), và khi họ hỏi What time is it? bạn trả lời giờ tròn đơn giản — It's nine o'clock.",
  culturalNote_vi:
    "Good morning / afternoon / evening dùng khi gặp người; Good night dùng khi chia tay buổi tối (không phải chào lúc mới gặp). o'clock chỉ giờ tròn (7:00), không dùng cho 7:15. Người bản ngữ hay nói morning! ngắn; học viên A0 giữ full Good morning.",
  jobAngle: "Chào đồng nghiệp / khách theo buổi; hỏi giờ họp tròn",
  lexis: [
    {
      id: "v1",
      word: "morning",
      phonetic: "/ˈmɔːrnɪŋ/",
      meaning_vi: "buổi sáng",
      example_en: "Good morning!",
      l1_note_vi: "morning ≈ sáng đến trưa. Good morning (chào), không: Good morning night.",
    },
    {
      id: "v2",
      word: "afternoon",
      phonetic: "/ˌæftərˈnuːn/",
      meaning_vi: "buổi chiều",
      example_en: "Good afternoon!",
      l1_note_vi: "afternoon = sau trưa. Trọng âm: after-NOON.",
    },
    {
      id: "v3",
      word: "evening",
      phonetic: "/ˈiːvnɪŋ/",
      meaning_vi: "buổi tối (sớm)",
      example_en: "Good evening!",
      l1_note_vi: "evening = tối khi gặp người. Khác Good night (chia tay).",
    },
    {
      id: "v4",
      word: "night",
      phonetic: "/naɪt/",
      meaning_vi: "ban đêm / tối muộn",
      example_en: "Good night!",
      l1_note_vi: "Good night = tạm biệt buổi tối. Không dùng thay Good evening khi mới gặp.",
    },
    {
      id: "v5",
      word: "Good morning",
      phonetic: "/ɡʊd ˈmɔːrnɪŋ/",
      meaning_vi: "Chào buổi sáng",
      example_en: "Good morning, Lan!",
      l1_note_vi: "Chào buổi sáng. Viết hoa Good. Không: Good mornings.",
    },
    {
      id: "v6",
      word: "Good afternoon",
      phonetic: "/ɡʊd ˌæftərˈnuːn/",
      meaning_vi: "Chào buổi chiều",
      example_en: "Good afternoon!",
      l1_note_vi: "Dùng sau trưa đến chiều. Cùng khung Good + time-of-day.",
    },
    {
      id: "v7",
      word: "Good evening",
      phonetic: "/ɡʊd ˈiːvnɪŋ/",
      meaning_vi: "Chào buổi tối",
      example_en: "Good evening!",
      l1_note_vi: "Chào khi mới gặp tối. ≠ Good night.",
    },
    {
      id: "v8",
      word: "Good night",
      phonetic: "/ɡʊd naɪt/",
      meaning_vi: "Chúc ngủ ngon / tạm biệt tối",
      example_en: "Good night. See you tomorrow.",
      l1_note_vi: "Chia tay buổi tối. Không: Good night! lúc 9h sáng khi mới gặp.",
    },
    {
      id: "v9",
      word: "o'clock",
      phonetic: "/əˈklɒk/",
      meaning_vi: "giờ đúng (tròn)",
      example_en: "It's seven o'clock.",
      l1_note_vi: "It's + số + o'clock. Chỉ giờ tròn. Không: It's seven o'clock fifteen.",
    },
    {
      id: "v10",
      word: "What time is it?",
      phonetic: "/wɒt taɪm ɪz ɪt/",
      meaning_vi: "Mấy giờ rồi?",
      example_en: "What time is it? — It's nine o'clock.",
    },
  ],
  grammar: {
    title: "Good + time of day / It's … o'clock",
    rule: "Good morning/afternoon/evening (greet). Good night (leave). It's + number + o'clock.",
    examples: [
      { en: "Good morning!", vi: "Chào buổi sáng!" },
      { en: "Good evening!", vi: "Chào buổi tối!" },
      { en: "What time is it?", vi: "Mấy giờ rồi?" },
      { en: "It's seven o'clock.", vi: "Bây giờ là 7 giờ." },
    ],
    vnNote:
      "Good + morning/afternoon/evening = chào. Good night = chia tay tối. Giờ tròn: It's + số (one–twelve) + o'clock. Lỗi L1: Good night khi mới gặp; It is seven clock (thiếu o').",
    ccq: {
      question: "Câu nào đúng khi mới gặp lúc 8 giờ tối?",
      options: [
        "Good night!",
        "Good evening!",
        "Good morning!",
        "It's o'clock seven.",
      ],
      answer: "Good evening!",
      explanation_vi: "Mới gặp buổi tối → Good evening. Good night chỉ khi chia tay.",
    },
  },
  controlled: [
    {
      id: "c1",
      type: "mcq",
      prompt_vi: "Chào đồng nghiệp lúc 8 giờ sáng:",
      options: [
        "Good morning!",
        "Good night!",
        "Good afternoon!",
        "It's morning o'clock.",
      ],
      answer: "Good morning!",
    },
    {
      id: "c2",
      type: "mcq",
      prompt_vi: "Hỏi 'Mấy giờ rồi?'",
      options: [
        "What time is it?",
        "Who is this?",
        "Where are you from?",
        "How are you?",
      ],
      answer: "What time is it?",
    },
    {
      id: "c3",
      type: "scramble",
      prompt_vi: "Sắp xếp: seven / It's / o'clock",
      words: ["It's", "seven", "o'clock"],
      answer: "It's seven o'clock",
    },
    {
      id: "c4",
      type: "mcq",
      prompt_vi: "Chia tay buổi tối — nói gì?",
      options: [
        "Good night!",
        "Good evening!",
        "Good morning!",
        "Good afternoon!",
      ],
      answer: "Good night!",
    },
    {
      id: "c5",
      type: "mcq",
      prompt_vi: "afternoon nghĩa là…",
      options: ["buổi chiều", "buổi sáng", "ban đêm", "gia đình"],
      answer: "buổi chiều",
    },
  ],
  input: {
    dialogues: [
      {
        id: "d1",
        title_vi: "Chào và hỏi giờ",
        context_vi: "Sáng sớm tại văn phòng; đồng nghiệp hỏi giờ họp.",
        lines: [
          {
            id: "1",
            speaker: "Alex",
            text: "Good morning, Lan!",
            translation_vi: "Chào buổi sáng, Lan!",
          },
          {
            id: "2",
            speaker: "Lan",
            text: "Good morning, Alex!",
            translation_vi: "Chào buổi sáng, Alex!",
          },
          {
            id: "3",
            speaker: "Alex",
            text: "What time is it?",
            translation_vi: "Mấy giờ rồi?",
          },
          {
            id: "4",
            speaker: "Lan",
            text: "It's nine o'clock.",
            translation_vi: "Bây giờ là 9 giờ.",
          },
          {
            id: "5",
            speaker: "Alex",
            text: "Thanks! See you this afternoon.",
            translation_vi: "Cảm ơn! Gặp lại chiều nay.",
          },
          {
            id: "6",
            speaker: "Lan",
            text: "OK. Good morning!",
            translation_vi: "OK. Chào buổi sáng!",
          },
        ],
      },
    ],
    listenItems: [
      {
        id: "lac1",
        audio_text: "Good morning",
        options: [
          "Good morning",
          "Good night",
          "Good evening",
          "Good afternoon",
        ],
        answer: "Good morning",
      },
      {
        id: "lac2",
        audio_text: "What time is it?",
        options: [
          "What time is it?",
          "What day is it?",
          "Who is this?",
          "Where are you from?",
        ],
        answer: "What time is it?",
      },
      {
        id: "lac3",
        audio_text: "It's seven o'clock",
        options: [
          "It's seven o'clock",
          "It's seven clock",
          "Seven it's o'clock",
          "It's o'clock seven",
        ],
        answer: "It's seven o'clock",
      },
      {
        id: "lac4",
        audio_text: "Good evening",
        options: [
          "Good evening",
          "Good night",
          "Good morning",
          "Good afternoon",
        ],
        answer: "Good evening",
      },
    ],
  },
  fluency: {
    items: [
      { en: "Good morning!", vi: "Chào buổi sáng!" },
      { en: "Good afternoon!", vi: "Chào buổi chiều!" },
      { en: "Good evening!", vi: "Chào buổi tối!" },
      { en: "Good night!", vi: "Chúc ngủ ngon / tạm biệt tối!" },
      { en: "What time is it?", vi: "Mấy giờ rồi?" },
      { en: "It's nine o'clock.", vi: "Bây giờ là 9 giờ." },
    ],
  },
  task: {
    type: "speak",
    prompt_vi:
      "Nói theo chuỗi: (1) Good morning (2) Good afternoon (3) Good evening (4) What time is it? (5) It's seven o'clock (6) Good night.",
    successCriteria_vi: [
      "Chào đúng ít nhất 2 buổi (morning/afternoon/evening)",
      "Phân biệt Good evening (gặp) vs Good night (chia tay)",
      "Nói được It's + số + o'clock",
    ],
    scaffold_en: [
      "Good morning!",
      "Good afternoon!",
      "Good evening!",
      "What time is it?",
      "It's seven o'clock.",
      "Good night!",
    ],
  },
  review: {
    quiz: [
      {
        id: "q1",
        type: "mcq",
        question: "Chào lúc 8 giờ sáng:",
        options: [
          "Good morning!",
          "Good night!",
          "Good evening!",
          "It's morning.",
        ],
        answer: "Good morning!",
      },
      {
        id: "q2",
        type: "mcq",
        question: "It's ___ o'clock.",
        options: ["seven", "sevens", "morning", "good"],
        answer: "seven",
      },
      {
        id: "q3",
        type: "true-false",
        question: "Good night dùng khi mới gặp lúc 7 giờ tối.",
        options: ["True", "False"],
        answer: "False",
      },
      {
        id: "q4",
        type: "mcq",
        question: "Hỏi mấy giờ:",
        options: [
          "What time is it?",
          "Who is this?",
          "Where are you from?",
          "How are you?",
        ],
        answer: "What time is it?",
      },
      {
        id: "q5",
        type: "mcq",
        question: "evening nghĩa là…",
        options: ["buổi tối (sớm)", "buổi sáng", "buổi chiều", "gia đình"],
        answer: "buổi tối (sớm)",
      },
    ],
    spiral: [
      {
        id: "s1",
        type: "mcq",
        question: "This is ___ mother.",
        options: ["my", "me", "I", "from"],
        answer: "my",
      },
      {
        id: "s2",
        type: "mcq",
        question: "I'm ___ Vietnam.",
        options: ["from", "my", "morning", "o'clock"],
        answer: "from",
      },
      {
        id: "s3",
        type: "mcq",
        question: "Who is this? — trả lời:",
        options: [
          "This is my sister.",
          "It's seven o'clock.",
          "Good morning!",
          "I'm from Hanoi.",
        ],
        answer: "This is my sister.",
      },
    ],
  },
};
