import type { LessonSpec } from "@/lib/v2/lesson-spec";

/** P0 gate — survival chunks + spiral full A0 block */
export const lessonA008: LessonSpec = {
  id: "l-a0-08",
  phase: "P0",
  cefr: "A0",
  title_vi: "Cụm sinh tồn",
  estimatedMin: 34,
  canDo: [
    "Dùng Excuse me / Sorry / Thank you lịch sự trong giao tiếp",
    "Nói I don't understand và nhờ giúp: Can you help me?",
    "Ghép survival chunks với chào hỏi, ngày, giờ đã học (P0)",
  ],
  situation:
    "Bạn ở sân bay, văn phòng, hoặc cửa hàng. Người nói tiếng Anh nhanh; bạn chưa hiểu. Bạn cần ngắt lời lịch sự (Excuse me), xin lỗi (Sorry), nói I don't understand, nhờ Can you help me?, và cảm ơn (Thank you).",
  culturalNote_vi:
    "Excuse me = xin phép / gọi chú ý (bắt đầu hỏi). Sorry = xin lỗi vì lỗi hoặc làm phiền. Thank you / Thanks = cảm ơn; You're welcome = không có gì. I don't understand lịch sự hơn im lặng. Can you help me, please? thân thiện hơn Help!",
  jobAngle: "Nhờ đồng nghiệp / IT / lễ tân: Excuse me — I don't understand. Can you help me?",
  lexis: [
    {
      id: "v1",
      word: "Excuse me",
      phonetic: "/ɪkˈskjuːz miː/",
      meaning_vi: "Xin lỗi / cho hỏi (gọi chú ý)",
      example_en: "Excuse me, can you help me?",
      l1_note_vi: "Bắt đầu hỏi đường/hỏi người lạ. s giữa = /z/. Khác Sorry (xin lỗi lỗi).",
    },
    {
      id: "v2",
      word: "I don't understand",
      phonetic: "/aɪ doʊnt ˌʌndərˈstænd/",
      meaning_vi: "Tôi không hiểu",
      example_en: "Sorry, I don't understand.",
      l1_note_vi: "don't = do not. Không: I no understand / I not understand.",
    },
    {
      id: "v3",
      word: "Can you help me?",
      phonetic: "/kæn juː help miː/",
      meaning_vi: "Bạn có thể giúp tôi không?",
      example_en: "Excuse me, can you help me?",
      l1_note_vi: "Can you + V? Lịch sự hơn Help me! Thêm please nếu muốn.",
    },
    {
      id: "v4",
      word: "Sorry",
      phonetic: "/ˈsɒri/",
      meaning_vi: "Xin lỗi",
      example_en: "Sorry, I don't understand.",
      l1_note_vi: "Sorry = lỗi/xin lỗi. Excuse me = gọi chú ý trước khi hỏi.",
    },
    {
      id: "v5",
      word: "Thank you",
      phonetic: "/ˈθæŋk juː/",
      meaning_vi: "Cảm ơn",
      example_en: "Thank you very much!",
      l1_note_vi: "Thank you / Thanks. th /θ/ — lưỡi giữa răng. Very much = rất nhiều.",
    },
    {
      id: "v6",
      word: "please",
      phonetic: "/pliːz/",
      meaning_vi: "làm ơn / xin vui lòng",
      example_en: "Can you help me, please?",
      l1_note_vi: "please làm câu lịch sự. Đặt cuối: …, please?",
    },
    {
      id: "v7",
      word: "You're welcome",
      phonetic: "/jʊr ˈwelkəm/",
      meaning_vi: "Không có gì",
      example_en: "Thank you! — You're welcome.",
      l1_note_vi: "You're = you are. Trả lời Thank you. Không: No problem only (OK nhưng formal hơn welcome).",
    },
    {
      id: "v8",
      word: "Can you repeat?",
      phonetic: "/kæn juː rɪˈpiːt/",
      meaning_vi: "Bạn nói lại được không?",
      example_en: "Sorry, can you repeat?",
      l1_note_vi: "repeat = nói lại. Kết hợp: Sorry, I don't understand. Can you repeat?",
    },
    {
      id: "v9",
      word: "help",
      phonetic: "/help/",
      meaning_vi: "giúp đỡ",
      example_en: "I need help.",
      l1_note_vi: "help (n/v). Can you help me? — me sau help.",
    },
    {
      id: "v10",
      word: "Thank you very much",
      phonetic: "/ˈθæŋk juː ˈveri mʌtʃ/",
      meaning_vi: "Cảm ơn rất nhiều",
      example_en: "Thank you very much!",
      l1_note_vi: "Lịch sự hơn Thanks. Dùng sau khi được giúp.",
    },
  ],
  grammar: {
    title: "Survival chunks: Excuse me / Sorry / Thank you",
    rule: "Excuse me + request. Sorry, I don't understand. Can you help me?",
    examples: [
      { en: "Excuse me, can you help me?", vi: "Xin lỗi, bạn giúp tôi được không?" },
      { en: "Sorry, I don't understand.", vi: "Xin lỗi, tôi không hiểu." },
      { en: "Can you repeat, please?", vi: "Bạn nói lại được không ạ?" },
      { en: "Thank you very much!", vi: "Cảm ơn rất nhiều!" },
    ],
    vnNote:
      "Chunk nguyên khối — học cả cụm. Lỗi L1: I no understand; Help me! (thô); Excuse me vs Sorry lẫn lộn; quên please/thank you.",
    ccq: {
      question: "Bạn không hiểu — nói gì?",
      options: [
        "Sorry, I don't understand.",
        "Today is Monday.",
        "My name is Lan.",
        "Good night!",
      ],
      answer: "Sorry, I don't understand.",
      explanation_vi: "I don't understand = không hiểu. Có thể thêm Can you repeat?",
    },
  },
  controlled: [
    {
      id: "c1",
      type: "mcq",
      prompt_vi: "Gọi chú ý người lạ trước khi hỏi:",
      options: [
        "Excuse me",
        "Good night",
        "Today is Friday",
        "This is my mother",
      ],
      answer: "Excuse me",
    },
    {
      id: "c2",
      type: "mcq",
      prompt_vi: "Bạn không hiểu — nói:",
      options: [
        "I don't understand.",
        "I no understand.",
        "I not understand.",
        "Understand no.",
      ],
      answer: "I don't understand.",
    },
    {
      id: "c3",
      type: "scramble",
      prompt_vi: "Sắp xếp: help / Can / me / you",
      words: ["Can", "you", "help", "me"],
      answer: "Can you help me",
    },
    {
      id: "c4",
      type: "mcq",
      prompt_vi: "Sau khi được giúp, bạn nói:",
      options: [
        "Thank you.",
        "Excuse me.",
        "I don't understand.",
        "What day is it?",
      ],
      answer: "Thank you.",
    },
    {
      id: "c5",
      type: "mcq",
      prompt_vi: "Trả lời 'Thank you':",
      options: [
        "You're welcome.",
        "I don't understand.",
        "Today is Monday.",
        "Can you help me?",
      ],
      answer: "You're welcome.",
    },
  ],
  input: {
    dialogues: [
      {
        id: "d1",
        title_vi: "Nhờ giúp ở văn phòng",
        context_vi: "Bạn mới; đồng nghiệp nói nhanh. Bạn cần survival chunks.",
        lines: [
          {
            id: "1",
            speaker: "Lan",
            text: "Excuse me, Alex.",
            translation_vi: "Xin lỗi, Alex.",
          },
          {
            id: "2",
            speaker: "Alex",
            text: "Yes?",
            translation_vi: "Vâng?",
          },
          {
            id: "3",
            speaker: "Lan",
            text: "Sorry, I don't understand.",
            translation_vi: "Xin lỗi, tôi không hiểu.",
          },
          {
            id: "4",
            speaker: "Alex",
            text: "OK. The meeting is on Monday.",
            translation_vi: "OK. Cuộc họp vào thứ Hai.",
          },
          {
            id: "5",
            speaker: "Lan",
            text: "Can you help me, please?",
            translation_vi: "Bạn giúp tôi được không ạ?",
          },
          {
            id: "6",
            speaker: "Alex",
            text: "Sure. Today is Friday. See you on Monday!",
            translation_vi: "Được. Hôm nay thứ Sáu. Hẹn thứ Hai!",
          },
          {
            id: "7",
            speaker: "Lan",
            text: "Thank you very much!",
            translation_vi: "Cảm ơn rất nhiều!",
          },
          {
            id: "8",
            speaker: "Alex",
            text: "You're welcome.",
            translation_vi: "Không có gì.",
          },
        ],
      },
    ],
    listenItems: [
      {
        id: "lac1",
        audio_text: "Excuse me",
        options: ["Excuse me", "Good morning", "Thank you", "Today is Monday"],
        answer: "Excuse me",
      },
      {
        id: "lac2",
        audio_text: "I don't understand",
        options: [
          "I don't understand",
          "I no understand",
          "Can you help me",
          "Thank you very much",
        ],
        answer: "I don't understand",
      },
      {
        id: "lac3",
        audio_text: "Can you help me?",
        options: [
          "Can you help me?",
          "What day is it?",
          "How are you?",
          "You're welcome.",
        ],
        answer: "Can you help me?",
      },
      {
        id: "lac4",
        audio_text: "Thank you very much",
        options: [
          "Thank you very much",
          "Excuse me please help",
          "Sorry Monday Friday",
          "I don't understand you me",
        ],
        answer: "Thank you very much",
      },
    ],
  },
  fluency: {
    items: [
      { en: "Excuse me.", vi: "Xin lỗi / cho hỏi." },
      { en: "Sorry, I don't understand.", vi: "Xin lỗi, tôi không hiểu." },
      { en: "Can you help me?", vi: "Bạn giúp tôi được không?" },
      { en: "Can you repeat, please?", vi: "Bạn nói lại được không ạ?" },
      { en: "Thank you very much!", vi: "Cảm ơn rất nhiều!" },
      { en: "You're welcome.", vi: "Không có gì." },
    ],
  },
  task: {
    type: "speak",
    prompt_vi:
      "Nói chuỗi sinh tồn: (1) Excuse me (2) Sorry, I don't understand (3) Can you help me, please? (4) Can you repeat? (5) Thank you very much (6) You're welcome.",
    successCriteria_vi: [
      "Nói được Excuse me và Sorry đúng ngữ cảnh",
      "Nói I don't understand + Can you help me?",
      "Kết thúc bằng Thank you / You're welcome",
    ],
    scaffold_en: [
      "Excuse me.",
      "Sorry, I don't understand.",
      "Can you help me, please?",
      "Can you repeat?",
      "Thank you very much!",
      "You're welcome.",
    ],
  },
  review: {
    quiz: [
      {
        id: "q1",
        type: "mcq",
        question: "Gọi chú ý trước khi hỏi:",
        options: ["Excuse me", "Good night", "Today is Sunday", "My name is…"],
        answer: "Excuse me",
      },
      {
        id: "q2",
        type: "mcq",
        question: "I don't ___.",
        options: ["understand", "Monday", "welcome", "morning"],
        answer: "understand",
      },
      {
        id: "q3",
        type: "true-false",
        question: "'Can you help me?' lịch sự hơn 'Help!'",
        options: ["True", "False"],
        answer: "True",
      },
      {
        id: "q4",
        type: "mcq",
        question: "Cảm ơn ai đó:",
        options: [
          "Thank you.",
          "I don't understand.",
          "What day is it?",
          "This is my father.",
        ],
        answer: "Thank you.",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Trả lời Thank you:",
        options: [
          "You're welcome.",
          "Excuse me.",
          "Sorry, Monday.",
          "Can you help me?",
        ],
        answer: "You're welcome.",
      },
    ],
    spiral: [
      {
        id: "s1",
        type: "mcq",
        question: "Chào buổi sáng (ôn a0-03/06):",
        options: [
          "Good morning!",
          "I don't understand.",
          "Can you help me?",
          "You're welcome.",
        ],
        answer: "Good morning!",
      },
      {
        id: "s2",
        type: "mcq",
        question: "What day is it? — trả lời (ôn a0-07):",
        options: [
          "Today is Friday.",
          "It's nine o'clock.",
          "Excuse me.",
          "Thank you.",
        ],
        answer: "Today is Friday.",
      },
      {
        id: "s3",
        type: "mcq",
        question: "What time is it? — trả lời (ôn a0-06):",
        options: [
          "It's nine o'clock.",
          "Today is Monday.",
          "This is my sister.",
          "Can you help me?",
        ],
        answer: "It's nine o'clock.",
      },
      {
        id: "s4",
        type: "mcq",
        question: "Giới thiệu người nhà (ôn a0-05):",
        options: [
          "This is my mother.",
          "Excuse me, Monday.",
          "I don't understand Friday.",
          "Thank you o'clock.",
        ],
        answer: "This is my mother.",
      },
      {
        id: "s5",
        type: "mcq",
        question: "Hỏi tên (ôn a0-04):",
        options: [
          "What's your name?",
          "What day is it?",
          "Can you help me?",
          "You're welcome.",
        ],
        answer: "What's your name?",
      },
      {
        id: "s6",
        type: "mcq",
        question: "P0 gate — survival khi không hiểu:",
        options: [
          "Sorry, I don't understand. Can you help me?",
          "Today is alphabet Monday.",
          "Good night number five.",
          "This is my o'clock.",
        ],
        answer: "Sorry, I don't understand. Can you help me?",
      },
    ],
  },
  pronunciationFocus: {
    phoneme: "/θ/ & /z/ in Thank / Excuse",
    description_vi:
      "Thank: th /θ/ lưỡi giữa răng. Excuse me: s giữa = /z/ (hữu thanh). Luyện chậm rồi nối.",
    examples: [
      {
        word: "Thank you",
        ipa: "/ˈθæŋk juː/",
        tip_vi: "θ — hơi ra giữa răng, không /s/ hay /t/.",
      },
      {
        word: "Excuse me",
        ipa: "/ɪkˈskjuːz miː/",
        tip_vi: "skjuːz — z cuối excuse trước me.",
      },
      {
        word: "Sorry",
        ipa: "/ˈsɒri/",
        tip_vi: "Trọng âm SOR-ry.",
      },
    ],
  },
};
