import type { LessonSpec } from "@/lib/v2/lesson-spec";

/** P0 — days of the week + Today is… / What day is it? */
export const lessonA007: LessonSpec = {
  id: "l-a0-07",
  phase: "P0",
  cefr: "A0",
  title_vi: "Ngày trong tuần",
  estimatedMin: 32,
  canDo: [
    "Nói 7 ngày trong tuần: Monday … Sunday",
    "Hỏi và trả lời: What day is it? — Today is…",
    "Dùng ngày tuần trong lịch họp / lịch làm việc cơ bản",
  ],
  situation:
    "Bạn làm việc với đồng nghiệp hoặc khách nước ngoài. Họ hỏi What day is it? hoặc nhắc họp on Monday. Bạn cần nói đúng ngày trong tuần và trả lời Today is Friday.",
  culturalNote_vi:
    "Ở nhiều nước phương Tây, tuần bắt đầu Monday (thứ Hai); Sunday là cuối tuần. Viết hoa tên ngày: Monday, không monday. on Monday = vào thứ Hai (không in Monday). weekend = Saturday + Sunday.",
  jobAngle: "Xác nhận ngày họp: The meeting is on Monday / Today is Friday",
  lexis: [
    {
      id: "v1",
      word: "Monday",
      phonetic: "/ˈmʌndeɪ/",
      meaning_vi: "thứ Hai",
      example_en: "Today is Monday.",
      l1_note_vi: "Viết hoa Monday. on Monday = vào thứ Hai (không in Monday).",
    },
    {
      id: "v2",
      word: "Tuesday",
      phonetic: "/ˈtjuːzdeɪ/",
      meaning_vi: "thứ Ba",
      example_en: "The meeting is on Tuesday.",
      l1_note_vi: "Tuesday ≈ thứ Ba. Trọng âm TUESday.",
    },
    {
      id: "v3",
      word: "Wednesday",
      phonetic: "/ˈwenzdeɪ/",
      meaning_vi: "thứ Tư",
      example_en: "Today is Wednesday.",
      l1_note_vi: "Phát âm /ˈwenzdeɪ/ (Wens-day), không đọc đủ 'Wed-nes-day'.",
    },
    {
      id: "v4",
      word: "Thursday",
      phonetic: "/ˈθɜːrzdeɪ/",
      meaning_vi: "thứ Năm",
      example_en: "See you on Thursday.",
      l1_note_vi: "Thursday — âm th /θ/ khó cho người Việt; luyện th.",
    },
    {
      id: "v5",
      word: "Friday",
      phonetic: "/ˈfraɪdeɪ/",
      meaning_vi: "thứ Sáu",
      example_en: "Today is Friday.",
      l1_note_vi: "Friday = thứ Sáu. Happy Friday! hay dùng văn phòng.",
    },
    {
      id: "v6",
      word: "Saturday",
      phonetic: "/ˈsætərdeɪ/",
      meaning_vi: "thứ Bảy",
      example_en: "We work on Saturday.",
      l1_note_vi: "Saturday thuộc weekend ở nhiều nước.",
    },
    {
      id: "v7",
      word: "Sunday",
      phonetic: "/ˈsʌndeɪ/",
      meaning_vi: "Chủ nhật",
      example_en: "Today is Sunday.",
      l1_note_vi: "Sunday = Chủ nhật. Viết hoa; on Sunday.",
    },
    {
      id: "v8",
      word: "today",
      phonetic: "/təˈdeɪ/",
      meaning_vi: "hôm nay",
      example_en: "Today is Monday.",
      l1_note_vi: "Today is + ngày. Không: Today Monday (thiếu is).",
    },
    {
      id: "v9",
      word: "What day is it?",
      phonetic: "/wɒt deɪ ɪz ɪt/",
      meaning_vi: "Hôm nay là thứ mấy?",
      example_en: "What day is it? — Today is Friday.",
      l1_note_vi: "Hỏi ngày trong tuần. Khác What time is it? (mấy giờ).",
    },
    {
      id: "v10",
      word: "weekend",
      phonetic: "/ˌwiːkˈend/",
      meaning_vi: "cuối tuần",
      example_en: "The weekend is Saturday and Sunday.",
      l1_note_vi: "weekend = Sat + Sun. on the weekend / at the weekend.",
    },
  ],
  grammar: {
    title: "Today is… / What day is it?",
    rule: "What day is it? → Today is + day. on + day (on Monday).",
    examples: [
      { en: "What day is it?", vi: "Hôm nay là thứ mấy?" },
      { en: "Today is Monday.", vi: "Hôm nay là thứ Hai." },
      { en: "The meeting is on Friday.", vi: "Cuộc họp vào thứ Sáu." },
      { en: "See you on Tuesday.", vi: "Hẹn gặp thứ Ba." },
    ],
    vnNote:
      "Today is + Monday…Sunday (có is). on + day = vào ngày đó. Lỗi L1: Today Monday; in Monday; What time is it? khi muốn hỏi thứ.",
    ccq: {
      question: "Hỏi 'Hôm nay là thứ mấy?' — câu nào đúng?",
      options: [
        "What day is it?",
        "What time is it?",
        "Who is this?",
        "Where are you from?",
      ],
      answer: "What day is it?",
      explanation_vi: "What day = hỏi thứ; What time = hỏi giờ.",
    },
  },
  controlled: [
    {
      id: "c1",
      type: "mcq",
      prompt_vi: "Hỏi hôm nay là thứ mấy:",
      options: [
        "What day is it?",
        "What time is it?",
        "How are you?",
        "Who is this?",
      ],
      answer: "What day is it?",
    },
    {
      id: "c2",
      type: "mcq",
      prompt_vi: "Hôm nay là thứ Sáu — nói:",
      options: [
        "Today is Friday.",
        "Today Friday.",
        "It's Friday o'clock.",
        "Good Friday morning night.",
      ],
      answer: "Today is Friday.",
    },
    {
      id: "c3",
      type: "scramble",
      prompt_vi: "Sắp xếp: is / Today / Monday",
      words: ["Today", "is", "Monday"],
      answer: "Today is Monday",
    },
    {
      id: "c4",
      type: "mcq",
      prompt_vi: "Cuộc họp vào thứ Hai:",
      options: [
        "The meeting is on Monday.",
        "The meeting is in Monday.",
        "The meeting is Monday on.",
        "Meeting Monday is the.",
      ],
      answer: "The meeting is on Monday.",
    },
    {
      id: "c5",
      type: "mcq",
      prompt_vi: "Wednesday nghĩa là…",
      options: ["thứ Tư", "thứ Hai", "thứ Sáu", "Chủ nhật"],
      answer: "thứ Tư",
    },
  ],
  input: {
    dialogues: [
      {
        id: "d1",
        title_vi: "Hỏi ngày họp",
        context_vi: "Văn phòng; đồng nghiệp xác nhận lịch tuần này.",
        lines: [
          {
            id: "1",
            speaker: "Alex",
            text: "Good morning, Lan!",
            translation_vi: "Chào buổi sáng, Lan!",
          },
          {
            id: "2",
            speaker: "Lan",
            text: "Good morning, Alex!",
            translation_vi: "Chào buổi sáng, Alex!",
          },
          {
            id: "3",
            speaker: "Alex",
            text: "What day is it?",
            translation_vi: "Hôm nay là thứ mấy?",
          },
          {
            id: "4",
            speaker: "Lan",
            text: "Today is Wednesday.",
            translation_vi: "Hôm nay là thứ Tư.",
          },
          {
            id: "5",
            speaker: "Alex",
            text: "OK. The meeting is on Friday.",
            translation_vi: "OK. Cuộc họp vào thứ Sáu.",
          },
          {
            id: "6",
            speaker: "Lan",
            text: "Great. See you on Friday!",
            translation_vi: "Tuyệt. Hẹn gặp thứ Sáu!",
          },
        ],
      },
    ],
    listenItems: [
      {
        id: "lac1",
        audio_text: "What day is it?",
        options: [
          "What day is it?",
          "What time is it?",
          "Who is this?",
          "Where are you from?",
        ],
        answer: "What day is it?",
      },
      {
        id: "lac2",
        audio_text: "Today is Monday",
        options: [
          "Today is Monday",
          "Today Monday",
          "Monday is today",
          "It's Monday o'clock",
        ],
        answer: "Today is Monday",
      },
      {
        id: "lac3",
        audio_text: "Today is Friday",
        options: [
          "Today is Friday",
          "Today is Sunday",
          "Good Friday",
          "It's Friday morning",
        ],
        answer: "Today is Friday",
      },
      {
        id: "lac4",
        audio_text: "on Tuesday",
        options: ["on Tuesday", "in Tuesday", "at Tuesday", "to Tuesday"],
        answer: "on Tuesday",
      },
    ],
  },
  fluency: {
    items: [
      { en: "What day is it?", vi: "Hôm nay là thứ mấy?" },
      { en: "Today is Monday.", vi: "Hôm nay là thứ Hai." },
      { en: "Today is Friday.", vi: "Hôm nay là thứ Sáu." },
      { en: "The meeting is on Monday.", vi: "Cuộc họp vào thứ Hai." },
      { en: "See you on Tuesday.", vi: "Hẹn gặp thứ Ba." },
      { en: "Today is Sunday.", vi: "Hôm nay là Chủ nhật." },
    ],
  },
  task: {
    type: "speak",
    prompt_vi:
      "Nói theo chuỗi: (1) What day is it? (2) Today is Monday (3) Today is Wednesday (4) Today is Friday (5) The meeting is on Tuesday (6) See you on Saturday.",
    successCriteria_vi: [
      "Hỏi được What day is it?",
      "Trả lời Today is + ít nhất 3 ngày trong tuần",
      "Dùng on + day cho lịch họp",
    ],
    scaffold_en: [
      "What day is it?",
      "Today is Monday.",
      "Today is Wednesday.",
      "Today is Friday.",
      "The meeting is on Tuesday.",
      "See you on Saturday.",
    ],
  },
  review: {
    quiz: [
      {
        id: "q1",
        type: "mcq",
        question: "Hỏi hôm nay thứ mấy:",
        options: [
          "What day is it?",
          "What time is it?",
          "How are you?",
          "Who is this?",
        ],
        answer: "What day is it?",
      },
      {
        id: "q2",
        type: "mcq",
        question: "Today is ___.",
        options: ["Friday", "fridays", "on Friday is", "Friday is today it"],
        answer: "Friday",
      },
      {
        id: "q3",
        type: "true-false",
        question: "Tên ngày viết hoa: Monday, Tuesday…",
        options: ["True", "False"],
        answer: "True",
      },
      {
        id: "q4",
        type: "mcq",
        question: "Cuộc họp vào thứ Hai:",
        options: [
          "The meeting is on Monday.",
          "The meeting is in Monday.",
          "Meeting Monday.",
          "It's Monday o'clock meeting.",
        ],
        answer: "The meeting is on Monday.",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Sunday nghĩa là…",
        options: ["Chủ nhật", "thứ Hai", "thứ Sáu", "buổi sáng"],
        answer: "Chủ nhật",
      },
    ],
    spiral: [
      {
        id: "s1",
        type: "mcq",
        question: "What time is it? — trả lời:",
        options: [
          "It's nine o'clock.",
          "Today is Monday.",
          "This is my sister.",
          "I'm from Vietnam.",
        ],
        answer: "It's nine o'clock.",
      },
      {
        id: "s2",
        type: "mcq",
        question: "Chào lúc 8 giờ sáng:",
        options: [
          "Good morning!",
          "Good night!",
          "Today is Monday.",
          "What day is it?",
        ],
        answer: "Good morning!",
      },
      {
        id: "s3",
        type: "mcq",
        question: "This is ___ mother.",
        options: ["my", "me", "Monday", "today"],
        answer: "my",
      },
    ],
  },
};
