import type { LessonSpec } from "@/lib/v2/lesson-spec";

/** P0 — basic family lexis + This is my… */
export const lessonA005: LessonSpec = {
  id: "l-a0-05",
  phase: "P0",
  cefr: "A0",
  title_vi: "Gia đình cơ bản",
  estimatedMin: 32,
  canDo: [
    "Nói tên các thành viên: mother, father, sister, brother, family",
    "Giới thiệu: This is my…",
    "Hỏi Who is this? và trả lời ngắn",
  ],
  situation:
    "Bạn đang xem ảnh gia đình với đồng nghiệp mới hoặc khách nước ngoài. Họ chỉ vào ảnh và hỏi Who is this? Bạn cần chỉ người và nói This is my mother / father / sister / brother — rõ, ngắn, lịch sự.",
  culturalNote_vi:
    "This is my… rất phổ biến khi giới thiệu người hoặc chỉ ảnh. Người bản ngữ hay dùng mom/dad thân mật; mother/father trang trọng hơn hoặc trong lớp học. Trả lời ngắn là đủ — không cần giải thích dài về họ hàng.",
  jobAngle: "Small talk ảnh gia đình / ice-breaker team",
  lexis: [
    {
      id: "v1",
      word: "family",
      phonetic: "/ˈfæməli/",
      meaning_vi: "gia đình",
      example_en: "This is my family.",
      l1_note_vi: "family = cả nhà. Không: my families khi chỉ một gia đình.",
    },
    {
      id: "v2",
      word: "mother",
      phonetic: "/ˈmʌðər/",
      meaning_vi: "mẹ",
      example_en: "This is my mother.",
      l1_note_vi: "mother trang trọng; mom thân mật. /ð/ lưỡi giữa răng.",
    },
    {
      id: "v3",
      word: "father",
      phonetic: "/ˈfɑːðər/",
      meaning_vi: "bố / cha",
      example_en: "This is my father.",
      l1_note_vi: "father / dad. Cùng khung This is my…",
    },
    {
      id: "v4",
      word: "sister",
      phonetic: "/ˈsɪstər/",
      meaning_vi: "chị / em gái",
      example_en: "This is my sister.",
      l1_note_vi: "sister không phân chị/em — thêm older/younger sau (A1+).",
    },
    {
      id: "v5",
      word: "brother",
      phonetic: "/ˈbrʌðər/",
      meaning_vi: "anh / em trai",
      example_en: "This is my brother.",
      l1_note_vi: "brother ≠ bro chỉ slang. Phát âm /ð/ giống mother.",
    },
    {
      id: "v6",
      word: "This is my",
      phonetic: "/ðɪs ɪz maɪ/",
      meaning_vi: "đây là … của tôi",
      example_en: "This is my mother.",
      l1_note_vi: "Khung cố định: This is my + người. Không: This my mother (thiếu is).",
    },
    {
      id: "v7",
      word: "Who is this?",
      phonetic: "/huː ɪz ðɪs/",
      meaning_vi: "Đây là ai?",
      example_en: "Who is this?",
      l1_note_vi: "Hỏi khi chỉ người/ảnh. Who is this? → This is my…",
    },
    {
      id: "v8",
      word: "my",
      phonetic: "/maɪ/",
      meaning_vi: "của tôi",
      example_en: "my family",
      l1_note_vi: "my + danh từ. Không: me family.",
    },
    {
      id: "v9",
      word: "parents",
      phonetic: "/ˈpeərənts/",
      meaning_vi: "bố mẹ",
      example_en: "These are my parents.",
      l1_note_vi: "parents = mother + father. Số nhiều → These are… (gợi ý nhẹ).",
    },
    {
      id: "v10",
      word: "photo",
      phonetic: "/ˈfoʊtoʊ/",
      meaning_vi: "ảnh",
      example_en: "This is a photo of my family.",
    },
  ],
  grammar: {
    title: "This is my… / Who is this?",
    rule: "Who is this? → This is my + family word.",
    examples: [
      { en: "Who is this?", vi: "Đây là ai?" },
      { en: "This is my mother.", vi: "Đây là mẹ tôi." },
      { en: "This is my father.", vi: "Đây là bố tôi." },
      { en: "This is my family.", vi: "Đây là gia đình tôi." },
    ],
    vnNote:
      "Cặp hỏi–đáp: Who is this? → This is my…. Lỗi L1 hay gặp: This my mother (thiếu is); This is me mother (me → my).",
    ccq: {
      question: "Câu nào đúng?",
      options: [
        "This my mother.",
        "This is my mother.",
        "This is me mother.",
        "My is this mother.",
      ],
      answer: "This is my mother.",
      explanation_vi: "Cần is + my trước danh từ người.",
    },
  },
  controlled: [
    {
      id: "c1",
      type: "mcq",
      prompt_vi: "Chỉ vào ảnh mẹ — nói gì?",
      options: [
        "This is my mother.",
        "This my mother.",
        "Who is my mother.",
        "I'm from mother.",
      ],
      answer: "This is my mother.",
    },
    {
      id: "c2",
      type: "mcq",
      prompt_vi: "Hỏi 'Đây là ai?'",
      options: [
        "Who is this?",
        "Where are you from?",
        "How are you?",
        "How much is it?",
      ],
      answer: "Who is this?",
    },
    {
      id: "c3",
      type: "scramble",
      prompt_vi: "Sắp xếp: my / This / is / brother",
      words: ["This", "is", "my", "brother"],
      answer: "This is my brother",
    },
    {
      id: "c4",
      type: "mcq",
      prompt_vi: "sister nghĩa là…",
      options: ["chị / em gái", "bố", "mẹ", "gia đình"],
      answer: "chị / em gái",
    },
    {
      id: "c5",
      type: "mcq",
      prompt_vi: "This ___ my father.",
      options: ["is", "are", "am", "from"],
      answer: "is",
    },
  ],
  input: {
    dialogues: [
      {
        id: "d1",
        title_vi: "Xem ảnh gia đình",
        context_vi: "Hai đồng nghiệp xem ảnh trên điện thoại lúc nghỉ giải lao.",
        lines: [
          {
            id: "1",
            speaker: "Alex",
            text: "Hi Lan! Is this a photo?",
            translation_vi: "Chào Lan! Đây có phải là ảnh không?",
          },
          {
            id: "2",
            speaker: "Lan",
            text: "Yes. This is my family.",
            translation_vi: "Đúng. Đây là gia đình tôi.",
          },
          {
            id: "3",
            speaker: "Alex",
            text: "Who is this?",
            translation_vi: "Đây là ai?",
          },
          {
            id: "4",
            speaker: "Lan",
            text: "This is my mother. And this is my father.",
            translation_vi: "Đây là mẹ tôi. Và đây là bố tôi.",
          },
          {
            id: "5",
            speaker: "Alex",
            text: "Nice! Who is this?",
            translation_vi: "Hay quá! Còn đây là ai?",
          },
          {
            id: "6",
            speaker: "Lan",
            text: "This is my sister. This is my brother.",
            translation_vi: "Đây là chị/em gái tôi. Đây là anh/em trai tôi.",
          },
        ],
      },
    ],
    listenItems: [
      {
        id: "lac1",
        audio_text: "This is my mother",
        options: [
          "This is my mother",
          "This my mother",
          "This is me mother",
          "This is my brother",
        ],
        answer: "This is my mother",
      },
      {
        id: "lac2",
        audio_text: "Who is this?",
        options: [
          "Who is this?",
          "Who this is?",
          "Where is this?",
          "How is this?",
        ],
        answer: "Who is this?",
      },
      {
        id: "lac3",
        audio_text: "This is my family",
        options: [
          "This is my family",
          "This is my father",
          "This my family",
          "These is my family",
        ],
        answer: "This is my family",
      },
      {
        id: "lac4",
        audio_text: "This is my brother",
        options: [
          "This is my brother",
          "This is my sister",
          "This is my mother",
          "This my brother",
        ],
        answer: "This is my brother",
      },
    ],
  },
  fluency: {
    items: [
      { en: "This is my family.", vi: "Đây là gia đình tôi." },
      { en: "This is my mother.", vi: "Đây là mẹ tôi." },
      { en: "This is my father.", vi: "Đây là bố tôi." },
      { en: "This is my sister.", vi: "Đây là chị/em gái tôi." },
      { en: "This is my brother.", vi: "Đây là anh/em trai tôi." },
      { en: "Who is this?", vi: "Đây là ai?" },
    ],
  },
  task: {
    type: "speak",
    prompt_vi:
      "Tưởng tượng chỉ ảnh: (1) This is my family (2) Who is this? (3) This is my mother / father (4) This is my sister / brother.",
    successCriteria_vi: [
      "Nói được This is my + ít nhất 2 từ gia đình",
      "Hỏi hoặc trả lời Who is this?",
      "Không bỏ is trong This is my…",
    ],
    scaffold_en: [
      "This is my family.",
      "Who is this?",
      "This is my mother.",
      "This is my father.",
      "This is my sister.",
      "This is my brother.",
    ],
  },
  review: {
    quiz: [
      {
        id: "q1",
        type: "mcq",
        question: "This ___ my sister.",
        options: ["is", "are", "am", "from"],
        answer: "is",
      },
      {
        id: "q2",
        type: "mcq",
        question: "Hỏi 'Đây là ai?'",
        options: [
          "Who is this?",
          "Where are you from?",
          "How are you?",
          "My name is?",
        ],
        answer: "Who is this?",
      },
      {
        id: "q3",
        type: "true-false",
        question: "mother = mẹ",
        options: ["True", "False"],
        answer: "True",
      },
      {
        id: "q4",
        type: "mcq",
        question: "brother nghĩa là…",
        options: ["anh / em trai", "chị / em gái", "mẹ", "bố"],
        answer: "anh / em trai",
      },
      {
        id: "q5",
        type: "mcq",
        question: "This is ___ father.",
        options: ["my", "me", "I", "from"],
        answer: "my",
      },
    ],
    spiral: [
      {
        id: "s1",
        type: "mcq",
        question: "I'm ___ Vietnam.",
        options: ["from", "my", "family", "this"],
        answer: "from",
      },
      {
        id: "s2",
        type: "mcq",
        question: "Where are you from? — trả lời:",
        options: [
          "I'm from Hanoi.",
          "This is my mother.",
          "Who is this?",
          "I'm fine, thanks.",
        ],
        answer: "I'm from Hanoi.",
      },
      {
        id: "s3",
        type: "mcq",
        question: "My name ___ Lan.",
        options: ["is", "are", "my", "from"],
        answer: "is",
      },
    ],
  },
};
