import type { LessonSpec } from "@/lib/v2/lesson-spec";

/** P0 — name & nationality / origin */
export const lessonA004: LessonSpec = {
  id: "l-a0-04",
  phase: "P0",
  cefr: "A0",
  title_vi: "Tên & quốc tịch",
  estimatedMin: 32,
  canDo: [
    "Nói tên và nơi đến: My name is… / I'm from…",
    "Hỏi Where are you from?",
    "Nói quốc tịch / thành phố đơn giản (Vietnam, Hanoi…)",
  ],
  situation:
    "Bạn đang điền form hoặc gặp đồng nghiệp mới. Họ hỏi tên và bạn đến từ đâu. Bạn cần trả lời rõ, hỏi lại lịch sự, và hiểu các từ country / city cơ bản.",
  culturalNote_vi:
    "I'm from Vietnam rất phổ biến hơn I come from… trong chào hỏi nhanh. Người bản ngữ hay hỏi Where are you from? cả khi đã biết bạn sống ở đâu — có thể nghĩa quê quán hoặc quốc tịch. Trả lời ngắn là đủ: I'm from Vietnam. / I'm from Hanoi.",
  jobAngle: "Form HR / gặp team quốc tế lần đầu",
  lexis: [
    {
      id: "v1",
      word: "name",
      phonetic: "/neɪm/",
      meaning_vi: "tên",
      example_en: "My name is Lan.",
      l1_note_vi: "Ôn từ bài chữ cái. My name is… — đừng bỏ is.",
    },
    {
      id: "v2",
      word: "from",
      phonetic: "/frɒm/",
      meaning_vi: "từ / đến từ",
      example_en: "I'm from Vietnam.",
      l1_note_vi: "I'm from + nơi. Không: I from Vietnam (thiếu am/'m).",
    },
    {
      id: "v3",
      word: "country",
      phonetic: "/ˈkʌntri/",
      meaning_vi: "quốc gia",
      example_en: "Vietnam is my country.",
      l1_note_vi: "country ≠ city. Vietnam = country; Hanoi = city.",
    },
    {
      id: "v4",
      word: "city",
      phonetic: "/ˈsɪti/",
      meaning_vi: "thành phố",
      example_en: "Hanoi is a city.",
    },
    {
      id: "v5",
      word: "Vietnam",
      phonetic: "/ˌvjetˈnæm/",
      meaning_vi: "Việt Nam",
      example_en: "I'm from Vietnam.",
      l1_note_vi: "Tiếng Anh: Vietnam (một từ). Vietnamese = người/ngôn ngữ Việt.",
    },
    {
      id: "v6",
      word: "Hanoi",
      phonetic: "/hæˈnɔɪ/",
      meaning_vi: "Hà Nội",
      example_en: "I'm from Hanoi.",
    },
    {
      id: "v7",
      word: "Where are you from?",
      phonetic: "/weər ɑːr juː frɒm/",
      meaning_vi: "Bạn đến từ đâu?",
      example_en: "Where are you from?",
      l1_note_vi: "Cố định: Where are you from? Không: Where you from? (thiếu are).",
    },
    {
      id: "v8",
      word: "I'm from",
      phonetic: "/aɪm frɒm/",
      meaning_vi: "tôi đến từ",
      example_en: "I'm from Vietnam.",
      l1_note_vi: "I'm = I am. Lỗi hay gặp: I from…",
    },
    {
      id: "v9",
      word: "nice",
      phonetic: "/naɪs/",
      meaning_vi: "tốt / dễ chịu (trong Nice to meet you)",
      example_en: "Nice to meet you.",
      l1_note_vi: "Ôn chào hỏi: Nice to meet you khi gặp lần đầu.",
    },
    {
      id: "v10",
      word: "too",
      phonetic: "/tuː/",
      meaning_vi: "cũng",
      example_en: "Nice to meet you too!",
      l1_note_vi: "too ở cuối câu = also. Nice to meet you too!",
    },
  ],
  grammar: {
    title: "I'm from… / Where are you from?",
    rule: "Where are you from? → I'm from + country/city.",
    examples: [
      { en: "Where are you from?", vi: "Bạn đến từ đâu?" },
      { en: "I'm from Vietnam.", vi: "Tôi đến từ Việt Nam." },
      { en: "I'm from Hanoi.", vi: "Tôi đến từ Hà Nội." },
      { en: "My name is Lan. I'm from Vietnam.", vi: "Tên tôi là Lan. Tôi đến từ Việt Nam." },
    ],
    vnNote:
      "Cặp hỏi–đáp cố định. Thiếu BE là lỗi L1: Where you from? / I from Vietnam → Where are you from? / I'm from Vietnam.",
    ccq: {
      question: "Câu nào đúng?",
      options: [
        "I from Vietnam.",
        "I'm from Vietnam.",
        "I am Vietnam from.",
        "From I Vietnam.",
      ],
      answer: "I'm from Vietnam.",
      explanation_vi: "Cần 'm/am trước from.",
    },
  },
  controlled: [
    {
      id: "c1",
      type: "mcq",
      prompt_vi: "Hỏi nơi đến",
      options: [
        "Where are you from?",
        "Where you from?",
        "How much is it?",
        "How are you from?",
      ],
      answer: "Where are you from?",
    },
    {
      id: "c2",
      type: "mcq",
      prompt_vi: "Trả lời: đến từ Việt Nam",
      options: [
        "I'm from Vietnam.",
        "I from Vietnam.",
        "My name is Vietnam.",
        "I'm Vietnam from.",
      ],
      answer: "I'm from Vietnam.",
    },
    {
      id: "c3",
      type: "scramble",
      prompt_vi: "Sắp xếp: from / I'm / Hanoi",
      words: ["I'm", "from", "Hanoi"],
      answer: "I'm from Hanoi",
    },
    {
      id: "c4",
      type: "mcq",
      prompt_vi: "Vietnam là…",
      options: ["a country", "a city", "a number", "a letter"],
      answer: "a country",
    },
    {
      id: "c5",
      type: "mcq",
      prompt_vi: "My name ___ Lan.",
      options: ["is", "are", "am", "from"],
      answer: "is",
    },
  ],
  input: {
    dialogues: [
      {
        id: "d1",
        title_vi: "Gặp đồng nghiệp mới",
        context_vi: "Hai người chào và hỏi quê quán.",
        lines: [
          {
            id: "1",
            speaker: "Alex",
            text: "Hi! My name is Alex. Nice to meet you.",
            translation_vi: "Chào! Tên tôi là Alex. Rất vui được gặp bạn.",
          },
          {
            id: "2",
            speaker: "Lan",
            text: "Hi Alex! My name is Lan. Nice to meet you too.",
            translation_vi: "Chào Alex! Tên tôi là Lan. Rất vui được gặp bạn.",
          },
          {
            id: "3",
            speaker: "Alex",
            text: "Where are you from?",
            translation_vi: "Bạn đến từ đâu?",
          },
          {
            id: "4",
            speaker: "Lan",
            text: "I'm from Vietnam. I'm from Hanoi.",
            translation_vi: "Tôi đến từ Việt Nam. Tôi đến từ Hà Nội.",
          },
          {
            id: "5",
            speaker: "Alex",
            text: "Nice! I'm from the USA.",
            translation_vi: "Hay quá! Tôi đến từ Mỹ.",
          },
          {
            id: "6",
            speaker: "Lan",
            text: "Nice to meet you. Bye!",
            translation_vi: "Rất vui được gặp. Tạm biệt!",
          },
        ],
      },
    ],
    listenItems: [
      {
        id: "lac1",
        audio_text: "Where are you from?",
        options: [
          "Where are you from?",
          "Where you from?",
          "Who are you from?",
          "How are you?",
        ],
        answer: "Where are you from?",
      },
      {
        id: "lac2",
        audio_text: "I'm from Vietnam",
        options: [
          "I'm from Vietnam",
          "I from Vietnam",
          "I'm form Vietnam",
          "I'm from city",
        ],
        answer: "I'm from Vietnam",
      },
      {
        id: "lac3",
        audio_text: "I'm from Hanoi",
        options: [
          "I'm from Hanoi",
          "I'm from Hano",
          "I from Hanoi",
          "My name is Hanoi",
        ],
        answer: "I'm from Hanoi",
      },
      {
        id: "lac4",
        audio_text: "My name is Lan",
        options: [
          "My name is Lan",
          "My name Lan",
          "My game is Lan",
          "By name is Lan",
        ],
        answer: "My name is Lan",
      },
    ],
  },
  fluency: {
    items: [
      { en: "My name is Lan.", vi: "Tên tôi là Lan." },
      { en: "Where are you from?", vi: "Bạn đến từ đâu?" },
      { en: "I'm from Vietnam.", vi: "Tôi đến từ Việt Nam." },
      { en: "I'm from Hanoi.", vi: "Tôi đến từ Hà Nội." },
      { en: "Nice to meet you too!", vi: "Rất vui được gặp bạn!" },
      { en: "Vietnam is my country.", vi: "Việt Nam là quốc gia của tôi." },
    ],
  },
  task: {
    type: "speak",
    prompt_vi:
      "Nói to: (1) My name is + tên (2) Where are you from? (3) I'm from Vietnam / thành phố bạn (4) Nice to meet you.",
    successCriteria_vi: [
      "Nói được My name is…",
      "Hỏi hoặc trả lời Where are you from? / I'm from…",
      "Nói được Vietnam hoặc một city",
    ],
    scaffold_en: [
      "My name is…",
      "Where are you from?",
      "I'm from Vietnam.",
      "I'm from Hanoi.",
      "Nice to meet you.",
    ],
  },
  review: {
    quiz: [
      {
        id: "q1",
        type: "mcq",
        question: "Where ___ you from?",
        options: ["are", "is", "am", "be"],
        answer: "are",
      },
      {
        id: "q2",
        type: "mcq",
        question: "I'm ___ Vietnam.",
        options: ["from", "for", "form", "of"],
        answer: "from",
      },
      {
        id: "q3",
        type: "true-false",
        question: "Hanoi is a city.",
        options: ["True", "False"],
        answer: "True",
      },
      {
        id: "q4",
        type: "mcq",
        question: "Vietnam is a…",
        options: ["country", "city", "number", "letter"],
        answer: "country",
      },
      {
        id: "q5",
        type: "mcq",
        question: "My name ___ Lan.",
        options: ["is", "are", "from", "too"],
        answer: "is",
      },
    ],
    spiral: [
      {
        id: "s1",
        type: "mcq",
        question: "How much is it? dùng để…",
        options: ["hỏi giá", "hỏi quê", "chào hỏi", "đánh vần"],
        answer: "hỏi giá",
      },
      {
        id: "s2",
        type: "mcq",
        question: "I'm fine, thanks — trả lời câu nào?",
        options: ["How are you?", "Where are you from?", "How much is it?", "How do you spell it?"],
        answer: "How are you?",
      },
      {
        id: "s3",
        type: "mcq",
        question: "How do you ___ your name?",
        options: ["spell", "from", "city", "country"],
        answer: "spell",
      },
    ],
  },
};
