import type { LessonSpec } from "@/lib/v2/lesson-spec";

/** P0 — minimal greetings before full A1 intro lesson */
export const lessonA003: LessonSpec = {
  id: "l-a0-03",
  phase: "P0",
  cefr: "A0",
  title_vi: "Chào hỏi đơn giản",
  estimatedMin: 30,
  canDo: [
    "Chào và tạm biệt bằng Hi / Hello / Bye",
    "Nói My name is… và Nice to meet you",
    "Hỏi How are you? và trả lời ngắn I'm fine",
  ],
  situation:
    "Bạn gặp người nước ngoài ở sảnh công ty hoặc quán cà phê. Họ mỉm cười và nói Hello. Bạn cần chào lại, nói tên, hỏi thăm ngắn, rồi tạm biệt — không cần hội thoại dài.",
  culturalNote_vi:
    "Hi / Hello thường kèm nụ cười ngắn. How are you? nhiều khi là xã giao — trả lời ngắn I'm fine, thanks là đủ. Bye thân mật hơn Goodbye khi chia tay đồng nghiệp gần gũi.",
  jobAngle: "Gặp khách / đồng nghiệp lần đầu ở sảnh",
  lexis: [
    {
      id: "v1",
      word: "Hello",
      phonetic: "/həˈloʊ/",
      meaning_vi: "xin chào",
      example_en: "Hello! My name is Mai.",
      l1_note_vi: "An toàn mọi lúc. Hơi trang trọng hơn Hi.",
    },
    {
      id: "v2",
      word: "Hi",
      phonetic: "/haɪ/",
      meaning_vi: "chào (thân mật)",
      example_en: "Hi! How are you?",
      l1_note_vi: "Dùng nhiều hơn Hello trong đời thường và team trẻ.",
    },
    {
      id: "v3",
      word: "My name is",
      phonetic: "/maɪ neɪm ɪz/",
      meaning_vi: "tên tôi là",
      example_en: "My name is Hung.",
      l1_note_vi: "Có thể rút I'm Hung. Cả hai đều đúng.",
    },
    {
      id: "v4",
      word: "Nice to meet you",
      phonetic: "/naɪs tə miːt juː/",
      meaning_vi: "rất vui được gặp bạn",
      example_en: "Nice to meet you too!",
      l1_note_vi: "Chỉ dùng khi GẶP LẦN ĐẦU. Lần sau: Nice to see you.",
    },
    {
      id: "v5",
      word: "How are you?",
      phonetic: "/haʊ ɑːr juː/",
      meaning_vi: "bạn khỏe không?",
      example_en: "Hi! How are you?",
      l1_note_vi: "Xã giao — không cần kể bệnh dài. Trả lời ngắn rồi hỏi lại And you?",
    },
    {
      id: "v6",
      word: "I'm fine",
      phonetic: "/aɪm faɪn/",
      meaning_vi: "tôi ổn / khỏe",
      example_en: "I'm fine, thank you.",
      l1_note_vi: "fine = ổn, không phải 'phạt'. Thiếu 'm: I fine là sai.",
    },
    {
      id: "v7",
      word: "Thank you",
      phonetic: "/ˈθæŋk juː/",
      meaning_vi: "cảm ơn",
      example_en: "Thank you! Bye!",
      l1_note_vi: "Thanks ngắn hơn. /θ/ lưỡi giữa răng.",
    },
    {
      id: "v8",
      word: "Goodbye",
      phonetic: "/ɡʊdˈbaɪ/",
      meaning_vi: "tạm biệt",
      example_en: "Goodbye! See you!",
    },
    {
      id: "v9",
      word: "Bye",
      phonetic: "/baɪ/",
      meaning_vi: "tạm biệt (ngắn)",
      example_en: "Bye! See you later.",
      l1_note_vi: "Thân mật, dùng nhiều hơn Goodbye giữa đồng nghiệp.",
    },
    {
      id: "v10",
      word: "And you?",
      phonetic: "/ænd juː/",
      meaning_vi: "còn bạn?",
      example_en: "I'm fine, thanks. And you?",
      l1_note_vi: "Hỏi lại lịch sự sau How are you? — đừng bỏ qua bước này.",
    },
  ],
  grammar: {
    title: "Hi + name + How are you?",
    rule: "Hi/Hello! My name is… Nice to meet you. How are you? → I'm fine, thanks. And you?",
    examples: [
      { en: "Hi! My name is Mai.", vi: "Chào! Tên tôi là Mai." },
      { en: "Nice to meet you.", vi: "Rất vui được gặp bạn." },
      { en: "How are you?", vi: "Bạn khỏe không?" },
      { en: "I'm fine, thanks. And you?", vi: "Tôi ổn, cảm ơn. Còn bạn?" },
    ],
    vnNote:
      "Thứ tự an toàn: chào → tên → Nice to meet you → How are you? → trả lời + And you? → Bye. Không bỏ BE: I fine ✗ → I'm fine ✓.",
    ccq: {
      question: "Câu nào đúng?",
      options: [
        "I fine, thank you.",
        "I'm fine, thank you.",
        "I am fine thank.",
        "Fine I am thanks.",
      ],
      answer: "I'm fine, thank you.",
      explanation_vi: "Cần am/'m trước fine.",
    },
  },
  controlled: [
    {
      id: "c1",
      type: "mcq",
      prompt_vi: "Chào thân mật",
      options: ["Hi", "Bye", "Dollar", "Spell"],
      answer: "Hi",
    },
    {
      id: "c2",
      type: "mcq",
      prompt_vi: "Tự giới thiệu tên",
      options: [
        "My name is Mai.",
        "My name Mai.",
        "Name is my Mai.",
        "I name Mai.",
      ],
      answer: "My name is Mai.",
    },
    {
      id: "c3",
      type: "scramble",
      prompt_vi: "Sắp xếp: are / How / you",
      words: ["How", "are", "you"],
      answer: "How are you",
    },
    {
      id: "c4",
      type: "mcq",
      prompt_vi: "Trả lời How are you?",
      options: [
        "I'm fine, thanks.",
        "I fine, thanks.",
        "My name is fine.",
        "How much is it?",
      ],
      answer: "I'm fine, thanks.",
    },
    {
      id: "c5",
      type: "mcq",
      prompt_vi: "Gặp lần đầu — nói gì?",
      options: [
        "Nice to meet you.",
        "How much is it?",
        "Please repeat.",
        "It is five dollars.",
      ],
      answer: "Nice to meet you.",
    },
  ],
  input: {
    dialogues: [
      {
        id: "d1",
        title_vi: "Gặp ở sảnh",
        context_vi: "Hai người gặp lần đầu trước giờ làm.",
        lines: [
          {
            id: "1",
            speaker: "Alex",
            text: "Hello! My name is Alex.",
            translation_vi: "Xin chào! Tên tôi là Alex.",
          },
          {
            id: "2",
            speaker: "Mai",
            text: "Hi Alex! My name is Mai. Nice to meet you.",
            translation_vi: "Chào Alex! Tên tôi là Mai. Rất vui được gặp bạn.",
          },
          {
            id: "3",
            speaker: "Alex",
            text: "Nice to meet you too! How are you?",
            translation_vi: "Rất vui được gặp bạn. Bạn khỏe không?",
          },
          {
            id: "4",
            speaker: "Mai",
            text: "I'm fine, thank you. And you?",
            translation_vi: "Tôi ổn, cảm ơn. Còn bạn?",
          },
          {
            id: "5",
            speaker: "Alex",
            text: "I'm fine too. See you!",
            translation_vi: "Tôi cũng ổn. Hẹn gặp lại!",
          },
          {
            id: "6",
            speaker: "Mai",
            text: "Bye!",
            translation_vi: "Tạm biệt!",
          },
        ],
      },
    ],
    listenItems: [
      {
        id: "lac1",
        audio_text: "Nice to meet you",
        options: [
          "Nice to meet you",
          "Nice to meat you",
          "Nice two meet you",
          "Name to meet you",
        ],
        answer: "Nice to meet you",
      },
      {
        id: "lac2",
        audio_text: "How are you?",
        options: [
          "How are you?",
          "How much are you?",
          "Who are you?",
          "How old are you?",
        ],
        answer: "How are you?",
      },
      {
        id: "lac3",
        audio_text: "I'm fine, thank you",
        options: [
          "I'm fine, thank you",
          "I fine, thank you",
          "I'm five, thank you",
          "I'm find, thank you",
        ],
        answer: "I'm fine, thank you",
      },
      {
        id: "lac4",
        audio_text: "My name is Mai",
        options: [
          "My name is Mai",
          "My name Mai",
          "My game is Mai",
          "By name is Mai",
        ],
        answer: "My name is Mai",
      },
    ],
  },
  fluency: {
    items: [
      { en: "Hello!", vi: "Xin chào!" },
      { en: "Hi! My name is Mai.", vi: "Chào! Tên tôi là Mai." },
      { en: "Nice to meet you.", vi: "Rất vui được gặp bạn." },
      { en: "How are you?", vi: "Bạn khỏe không?" },
      { en: "I'm fine, thanks. And you?", vi: "Tôi ổn, cảm ơn. Còn bạn?" },
      { en: "Bye!", vi: "Tạm biệt!" },
    ],
  },
  task: {
    type: "speak",
    prompt_vi:
      "Đóng vai gặp mặt lần đầu: chào → My name is… → Nice to meet you → How are you? → I'm fine… And you? → Bye.",
    successCriteria_vi: [
      "Chào bằng Hi hoặc Hello",
      "Nói được My name is + tên",
      "Có How are you? hoặc I'm fine / Bye",
    ],
    scaffold_en: [
      "Hi! / Hello!",
      "My name is…",
      "Nice to meet you.",
      "How are you?",
      "I'm fine, thanks. And you?",
      "Bye!",
    ],
  },
  review: {
    quiz: [
      {
        id: "q1",
        type: "mcq",
        question: "My name ___ Mai.",
        options: ["is", "are", "am", "be"],
        answer: "is",
      },
      {
        id: "q2",
        type: "mcq",
        question: "Gặp lần đầu:",
        options: [
          "Nice to meet you.",
          "How much is it?",
          "Please spell it.",
          "It is five dollars.",
        ],
        answer: "Nice to meet you.",
      },
      {
        id: "q3",
        type: "true-false",
        question: "I'm fine = tôi ổn / khỏe",
        options: ["True", "False"],
        answer: "True",
      },
      {
        id: "q4",
        type: "mcq",
        question: "How ___ you?",
        options: ["are", "is", "am", "be"],
        answer: "are",
      },
      {
        id: "q5",
        type: "mcq",
        question: "Tạm biệt ngắn:",
        options: ["Bye", "Hello", "How much", "Spell"],
        answer: "Bye",
      },
    ],
    spiral: [
      {
        id: "s1",
        type: "mcq",
        question: "How much is it? dùng để…",
        options: ["hỏi giá", "chào hỏi", "đánh vần", "tạm biệt"],
        answer: "hỏi giá",
      },
      {
        id: "s2",
        type: "mcq",
        question: "Please ___ . (bài chữ cái)",
        options: ["repeat", "fine", "meet", "bye"],
        answer: "repeat",
      },
    ],
  },
};
