#!/usr/bin/env bash
# Read latest product-radar report → ensure AGENT_ROADMAP has follow-up tasks.
# Does NOT invent empty maintenance. Safe to run every daemon cycle (idempotent).
#
# Usage:
#   bash scripts/agent-plan-from-radar.sh
#   bash scripts/agent-plan-from-radar.sh --dry-run
# Env:
#   RADAR_MD  default logs/agent/product-radar-latest.md

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ROADMAP="$ROOT/AGENT_ROADMAP.md"
BACKLOG="$ROOT/AGENT_BACKLOG.md"
PLAN="$ROOT/AGENT_PLAN.md"
RADAR_MD="${RADAR_MD:-$ROOT/logs/agent/product-radar-latest.md}"
DRY=0
[[ "${1:-}" == "--dry-run" ]] && DRY=1

log() { echo "[plan-from-radar] $*"; }

if [[ ! -f "$RADAR_MD" ]]; then
  log "⚠️  No radar report at $RADAR_MD — run product-radar.sh first"
  exit 0
fi

if [[ ! -f "$ROADMAP" ]]; then
  log "❌ Missing ROADMAP"
  exit 1
fi

RESULT=$(python3 - "$RADAR_MD" "$ROADMAP" "$BACKLOG" "$PLAN" "$DRY" <<'PY'
import re
import sys
from datetime import date
from pathlib import Path

radar_path, roadmap_path, backlog_path, plan_path, dry_s = sys.argv[1:6]
dry = dry_s == "1"

radar = Path(radar_path).read_text(encoding="utf-8")
roadmap = Path(roadmap_path).read_text(encoding="utf-8")
backlog = Path(backlog_path).read_text(encoding="utf-8") if Path(backlog_path).is_file() else ""

existing = set(re.findall(r"### (TASK-\d+)", roadmap + "\n" + backlog))

def max_task_n() -> int:
    nums = [int(x) for x in re.findall(r"TASK-(\d+)", roadmap + "\n" + backlog)]
    return max(nums) if nums else 300

def has_title_fragment(frag: str) -> bool:
    return frag.lower() in (roadmap + backlog).lower()

# Parse FAIL summary
fail_m = re.search(r"\*\*Summary:\*\* PASS=(\d+) WARN=(\d+) FAIL=(\d+)", radar)
fail_count = int(fail_m.group(3)) if fail_m else 0
pass_count = int(fail_m.group(1)) if fail_m else 0

# Extract failed paths from table rows with FAIL
failed_paths = []
for line in radar.splitlines():
    if "| FAIL |" in line or "| FAIL |" in line.replace(" ", ""):
        # | `/path` | label | code | ...
        m = re.search(r"\|\s*`([^`]+)`\s*\|\s*([^|]+)\s*\|\s*(\d+)", line)
        if m:
            failed_paths.append((m.group(1).strip(), m.group(2).strip(), m.group(3)))

new_blocks = []
n = max_task_n()

def add_task(title: str, desc: str, done: str) -> None:
    global n
    # skip if similar title already in pool/backlog
    key = title[:40].lower()
    if any(key in (roadmap + backlog).lower() for _ in [0]):
        # stronger: exact title substring
        if title.lower() in (roadmap + backlog).lower():
            return
    n += 1
    tid = f"TASK-{n}"
    if tid in existing:
        n += 1
        tid = f"TASK-{n}"
    block = (
        f"### {tid} — {title}\n"
        f"- **Mô tả:** {desc}\n"
        f"- **Done khi:** {done}\n"
    )
    new_blocks.append((tid, block))
    existing.add(tid)

# P0 from radar fails
for path, label, code in failed_paths[:5]:
    title = f"P0 fix prod HTTP {code} on {path}"
    if title.lower() in (roadmap + backlog).lower():
        continue
    add_task(
        title,
        f"Radar FAIL: `{path}` ({label}) returned {code} on live. Reproduce, fix route/proxy/deploy, re-run product-radar.",
        f"`{path}` returns 200 on BASE_URL; product-radar PASS for path; lint+test.",
    )

# Ensure core product loop tasks exist if missing (idempotent seeds)
seeds = [
    (
        "Author l-a1-03",
        "Author l-a1-03 Gia đình & bạn bè (LessonSpec)",
        "Full LessonSpec for l-a1-03; L1 100%; registry + sequential after a1-02.",
        "schema + registry + path test; lint+test",
    ),
    (
        "product-radar in CI",
        "CI/local: run product-radar after deploy gate",
        "Wire product-radar.sh into orchestrator post-deploy or npm script; fail cycle on critical FAIL.",
        "script in package.json; docs; optional ORCHESTRATOR_RADAR=1",
    ),
]

for frag, title, desc, done in seeds:
    if frag.lower() in (roadmap + backlog).lower():
        continue
    add_task(title, desc, done)

added_ids = [t for t, _ in new_blocks]
section = ""
if new_blocks:
    section = (
        "\n## Pool — From product radar (auto)\n\n"
        "> Generated by `agent-plan-from-radar.sh`. Feature-only; no maintenance sweeps.\n\n"
        + "\n".join(b for _, b in new_blocks)
        + "\n"
    )

# Update AGENT_PLAN brief
plan_snip = f"""## Product loop (radar)

| Field | Value |
|-------|-------|
| Last radar | `{Path(radar_path).name}` |
| PASS / FAIL | {pass_count} / {fail_count} |
| Auto tasks added | {", ".join(added_ids) if added_ids else "—"} |
| Date | {date.today().isoformat()} |

**Focus:** {"P0 prod HTTP fails" if fail_count else "UI 262–264 then A1 content"} — see `logs/agent/product-radar-latest.md`.

"""

if not dry:
    if section and "## Pool — From product radar (auto)" not in roadmap:
        # Insert after first heading block
        if re.search(r"^## Pool —", roadmap, re.M):
            roadmap2 = re.sub(
                r"(^## Pool —)",
                section + r"\1",
                roadmap,
                count=1,
                flags=re.M,
            )
        else:
            roadmap2 = roadmap.rstrip() + "\n" + section
        Path(roadmap_path).write_text(roadmap2, encoding="utf-8")
    elif section and "## Pool — From product radar (auto)" in roadmap:
        # Append new tasks before next ## if not duplicate
        for tid, block in new_blocks:
            if tid not in roadmap:
                roadmap = roadmap.replace(
                    "## Pool — From product radar (auto)",
                    "## Pool — From product radar (auto)\n\n" + block,
                    1,
                )
        Path(roadmap_path).write_text(roadmap, encoding="utf-8")

    if Path(plan_path).is_file():
        plan = Path(plan_path).read_text(encoding="utf-8")
        if "## Product loop (radar)" in plan:
            plan = re.sub(
                r"## Product loop \(radar\).*?(?=\n## |\Z)",
                plan_snip.rstrip() + "\n\n",
                plan,
                count=1,
                flags=re.S,
            )
        else:
            plan = plan.replace(
                "# Agent Plan — Tự cập nhật mỗi phiên\n",
                "# Agent Plan — Tự cập nhật mỗi phiên\n\n" + plan_snip,
                1,
            )
        Path(plan_path).write_text(plan, encoding="utf-8")

print(f"ADDED={len(added_ids)}")
print(f"IDS={','.join(added_ids)}")
print(f"FAIL={fail_count}")
print(f"PASS={pass_count}")
PY
)

echo "$RESULT"
ADDED=$(echo "$RESULT" | grep -oE 'ADDED=[0-9]+' | head -1 | cut -d= -f2)
ADDED=${ADDED:-0}
log "Radar→plan done (ADDED=$ADDED dry=$DRY)"
exit 0
