#!/usr/bin/env bash
# Product radar — smoke live URLs → report for planner + agents.
# Usage: bash scripts/product-radar.sh
# Env: BASE_URL (default https://atoenglish.vercel.app)

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BASE_URL="${BASE_URL:-https://atoenglish.vercel.app}"
BASE_URL="${BASE_URL%/}"
LOG_DIR="$ROOT/logs/agent"
mkdir -p "$LOG_DIR"

UTC="$(date -u +%Y%m%dT%H%M%SZ)"
RADAR_OUT="${RADAR_OUT:-$LOG_DIR/product-radar-$UTC.md}"
RADAR_JSON="${RADAR_JSON:-$LOG_DIR/product-radar-$UTC.json}"
LATEST_MD="$LOG_DIR/product-radar-latest.md"
LATEST_JSON="$LOG_DIR/product-radar-latest.json"

# path|expect|label|critical — critical=1 → non-zero exit if fail (orchestrator)
PATHS=(
  "/|200|Landing|1"
  "/login|200|Login|1"
  "/home|200|Home v2|1"
  "/path|200|Path B1|1"
  "/learn|200|Learn list|1"
  "/speaking|200|Speaking hub|1"
  "/dashboard|200|Dashboard|1"
  "/me|200|Me hub|1"
  "/flashcards|200|Flashcards|1"
  "/learn/v2/l-a0-01|200|V2 pilot l-a0-01|1"
  "/learn/v2/l-a1-01|200|V2 pilot l-a1-01|1"
  "/learn/v2/l-a1-02|200|V2 A1 personal info|0"
  "/robots.txt|200|robots|0"
)

log() { echo "[product-radar] $*" >&2; }

FAIL=0
WARN=0
PASS=0
TMP_ROWS="$(mktemp)"
TMP_FAILS="$(mktemp)"
TMP_CRIT="$(mktemp)"
trap 'rm -f "$TMP_ROWS" "$TMP_FAILS" "$TMP_CRIT"' EXIT

log "BASE_URL=$BASE_URL"

for entry in "${PATHS[@]}"; do
  IFS='|' read -r path expect label critical <<<"$entry"
  url="${BASE_URL}${path}"
  body="$(mktemp)"
  code=$(curl -sS -L --max-time 25 -o "$body" -w "%{http_code}" "$url" 2>/dev/null || echo "000")
  bytes=$(wc -c <"$body" | tr -d ' ')
  hints="—"
  if [[ "$code" == "200" && "$bytes" -gt 200 ]]; then
    if grep -qiE 'application error|internal server error' "$body" 2>/dev/null; then
      hints="body_error"
    elif grep -qiE 'AtoEnglish|Học|Đăng nhập|Dashboard' "$body" 2>/dev/null; then
      hints="ok_brand"
    fi
  fi
  rm -f "$body"

  status="PASS"
  if [[ "$code" != "$expect" ]]; then
    status="FAIL"
    FAIL=$((FAIL + 1))
    echo "- \`$path\` ($label) code=$code expect=$expect" >>"$TMP_FAILS"
    if [[ "$critical" == "1" ]]; then
      echo "- CRITICAL \`$path\` ($label) → $code" >>"$TMP_CRIT"
    fi
  elif [[ "$hints" == "body_error" ]]; then
    status="WARN"
    WARN=$((WARN + 1))
  else
    PASS=$((PASS + 1))
  fi
  echo "| \`$path\` | $label | $code | $bytes | $status | $hints |" >>"$TMP_ROWS"
  log "$status $code $path"
done

{
  echo "# Product radar — $UTC"
  echo
  echo "- **Base URL:** \`$BASE_URL\`"
  echo "- **When:** $(date -Iseconds)"
  echo "- **Summary:** PASS=$PASS WARN=$WARN FAIL=$FAIL"
  echo
  echo "## HTTP smoke"
  echo
  echo "| Path | Label | Code | Bytes | Status | Hints |"
  echo "|------|-------|------|-------|--------|-------|"
  cat "$TMP_ROWS"
  echo
  echo "## Critical fails"
  echo
  if [[ ! -s "$TMP_CRIT" ]]; then echo "_None._"; else cat "$TMP_CRIT"; fi
  echo
  echo "## All fails"
  echo
  if [[ ! -s "$TMP_FAILS" ]]; then echo "_None._"; else cat "$TMP_FAILS"; fi
  echo
  echo "## Planner notes"
  echo
  echo "- **Critical paths:** landing, login, home, **/path**, learn, speaking, dashboard, **/me**, **/flashcards**, v2 pilot lessons"
  echo "- **/path** = B1 sequential path (A0→B1 42 lessons) — FAIL here blocks cutover"
  echo "- **/me** hub: study/practice/account groups (Hick shell)"
  echo "- **/flashcards** SRS review surface (guest local deck + auth cards)"
  echo "- V2 CORE_PATH 42/42 authored; progress SSOT localStorage \`ato_v2_progress\` when Supabase down"
  echo "- Quiz floor ≥50% in LessonPlayerV2 — verify on prod after deploy"
  echo "- No schema/auth/FSRS/RLS changes from radar alone"
  echo
  echo "## Suggested next focus"
  echo
  if [[ -s "$TMP_CRIT" ]]; then
    echo "1. **P0** Fix **critical** HTTP fails (exit non-zero)"
    echo "2. Re-run \`npm run radar\` until FAIL=0"
  elif [[ "$FAIL" -gt 0 ]]; then
    echo "1. Fix non-critical fails"
    echo "2. Keep critical green"
  else
    echo "1. Prod smoke green — path/me/flashcards critical OK"
    echo "2. Continue backlog ready tasks (E2E guest complete, soft gamify)"
  fi
  echo
  echo "---"
  echo "Generated by \`scripts/product-radar.sh\`"
} >"$RADAR_OUT"

python3 -c "
import json
from pathlib import Path
fails = Path('$TMP_FAILS').read_text(encoding='utf-8').strip().splitlines() if Path('$TMP_FAILS').stat().st_size else []
data = {
  'base_url': '$BASE_URL',
  'utc': '$UTC',
  'pass': $PASS,
  'warn': $WARN,
  'fail': $FAIL,
  'fails': fails,
  'report_md': '$RADAR_OUT',
}
Path('$RADAR_JSON').write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf-8')
"

cp -f "$RADAR_OUT" "$LATEST_MD"
cp -f "$RADAR_JSON" "$LATEST_JSON"

log "DONE PASS=$PASS WARN=$WARN FAIL=$FAIL → $RADAR_OUT"
echo "RADAR_OUT=$RADAR_OUT"
echo "PASS=$PASS WARN=$WARN FAIL=$FAIL"

# Orchestrator / CI: fail when any critical path is down
if [[ -s "$TMP_CRIT" ]]; then
  log "CRITICAL fails present — exit 1"
  exit 1
fi
exit 0
