create table if not exists public.lesson_v2_evidence (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  user_id uuid null references auth.users(id) on delete cascade,
  anonymous_id uuid not null,
  lesson_id text not null check (char_length(lesson_id) between 3 and 120),
  module_id text not null check (char_length(module_id) between 3 and 120),
  session_kind text not null check (
    session_kind in ('encounter', 'communicate', 'retain_transfer')
  ),
  evidence jsonb not null default '{}'::jsonb check (
    jsonb_typeof(evidence) = 'object'
  ),
  completed_at timestamptz not null,
  next_review_at timestamptz null,
  source text not null default 'lesson-v2-web'
);

create index if not exists lesson_v2_evidence_user_lesson_idx
  on public.lesson_v2_evidence (user_id, lesson_id, occurred_at desc)
  where user_id is not null;

create index if not exists lesson_v2_evidence_anonymous_lesson_idx
  on public.lesson_v2_evidence (anonymous_id, lesson_id, occurred_at desc);

create index if not exists lesson_v2_evidence_next_review_idx
  on public.lesson_v2_evidence (user_id, next_review_at)
  where user_id is not null and next_review_at is not null;

alter table public.lesson_v2_evidence enable row level security;

revoke all on table public.lesson_v2_evidence from public, anon, authenticated;
revoke all on sequence public.lesson_v2_evidence_id_seq from public, anon, authenticated;

grant insert on table public.lesson_v2_evidence to anon;
grant select, insert on table public.lesson_v2_evidence to authenticated;
grant select, insert, update, delete on table public.lesson_v2_evidence to service_role;
grant usage, select on sequence public.lesson_v2_evidence_id_seq
  to anon, authenticated, service_role;

create policy "anonymous clients append lesson evidence"
  on public.lesson_v2_evidence
  for insert
  to anon
  with check (
    user_id is null
    and anonymous_id is not null
  );

create policy "users append their own lesson evidence"
  on public.lesson_v2_evidence
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
  );

create policy "users read their own lesson evidence"
  on public.lesson_v2_evidence
  for select
  to authenticated
  using (
    (select auth.uid()) = user_id
  );
