-- dictionary_entries: English headword -> Vietnamese glosses for instant
-- tier-1 lookup in the dictionary panel (SPEC 005 §Lookup two-tier).
--
-- Source data: Kaikki/wiktextract extraction of Vietnamese Wiktionary
-- (vi.wiktionary.org), licensed CC BY-SA 4.0 + GFDL. Adapted data must carry
-- attribution + license notice wherever it is served; raw dump is NOT
-- committed — it is generated by scripts/dict-import-kaikki.ts.
--
-- Trust boundary: anonymous can SELECT (dictionary is shared public content).
-- No insert/update/delete policies — rows are loaded only by the offline
-- import script running with owner credentials; app code never writes.

create table public.dictionary_entries (
  -- Lookup keys are normalized lowercase (same convention as src/lib/read/gloss.ts).
  word text not null check (word = lower(word) and char_length(word) between 1 and 120),
  pos text not null check (char_length(pos) between 1 and 30),
  -- [{glosses: string[], examples?: [{text, translation?}], form_of?: string[]}]
  senses jsonb not null check (jsonb_typeof(senses) = 'array'),
  ipa text check (ipa is null or char_length(ipa) <= 100),
  audio_url text check (audio_url is null or audio_url ~ '^https://'),
  -- Provenance marker per row; future sources (curated glossary, AI cache)
  -- can coexist with different source values.
  source text not null default 'viwiktionary' check (char_length(source) <= 50),
  updated_at timestamptz not null default now(),
  primary key (word, pos),
  -- Keep rows off TOAST; senses for the most polysemous words stay ~10-30KB.
  constraint dictionary_entries_senses_size
    check (pg_column_size(senses) <= 262144)
);

comment on table public.dictionary_entries is
  'English->Vietnamese dictionary for tier-1 instant lookup. Data: Vietnamese Wiktionary via Kaikki/wiktextract (CC BY-SA 4.0 + GFDL). Read-only for app roles; populated by scripts/dict-import-kaikki.ts.';

alter table public.dictionary_entries enable row level security;

create policy "Dictionary entries readable by anyone"
  on public.dictionary_entries
  for select
  to anonymous, authenticated
  using (true);

-- Exact-key lookups are served by the (word, pos) primary key. Prefix/trigram
-- search is deliberately deferred until a real autocomplete need exists.
