create table if not exists public.pilot_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (
    event_name in (
      'pilot_landing_viewed',
      'pilot_started',
      'unit_started',
      'first_speaking_started',
      'first_speaking_completed',
      'unit_completed',
      'day_7_returned',
      'checkpoint_completed',
      'final_speaking_completed'
    )
  ),
  occurred_at timestamptz not null default now(),
  user_id uuid references neon_auth.user(id) on delete set null,
  anonymous_id uuid not null,
  source text check (source is null or char_length(source) <= 64),
  unit_id text check (unit_id is null or char_length(unit_id) <= 64),
  day_number smallint check (day_number is null or day_number between 1 and 28),
  score smallint check (score is null or score between 0 and 100),
  star_count smallint check (star_count is null or star_count between 1 and 3),
  passed boolean
);

create index if not exists pilot_events_event_time_idx
  on public.pilot_events (event_name, occurred_at desc);
create index if not exists pilot_events_user_time_idx
  on public.pilot_events (user_id, occurred_at desc)
  where user_id is not null;
create index if not exists pilot_events_anonymous_time_idx
  on public.pilot_events (anonymous_id, occurred_at desc);

alter table public.pilot_events enable row level security;

revoke all on table public.pilot_events from anon, authenticated;
grant insert on table public.pilot_events to anon, authenticated;
grant usage, select on sequence public.pilot_events_id_seq to anon, authenticated;

drop policy if exists "pilot events insert only" on public.pilot_events;
create policy "pilot events insert only"
  on public.pilot_events
  for insert
  to anon, authenticated
  with check (
    anonymous_id is not null
    and (
      (auth.uid() is null and user_id is null)
      or (auth.uid() is not null and user_id = auth.uid())
    )
  );

comment on table public.pilot_events is
  'Minimal 28-day pilot funnel events. No audio, transcript, names, employers, email addresses, or free-text learner content.';
